ipni/storetheindex

- go.mod
- go.sum
- store/persistent/storethehash/storethehash.go
- store/persistent/storethehash/storethehash_bench_test.go
- store/persistent/storethehash/storethehash_test.go
Implements https://github.com/filecoin-project/storetheindex/issues/7
Depends on: https://github.com/ipld/go-storethehash/pull/6
> Implement Remove functions for Storethehash storage

- go.mod
- go.sum
- main.go
- version/version.go
- version/version_test.go
when setting the string in a e.g docker build with `-x` it should be on this package's import path, not dealbot
> use local version

- api/v0/finder/models/models.go
- api/v0/finder/models/models_test.go
- api/v0/ingest/models/models.go
- command/daemon.go
- go.mod
- go.sum
- internal/providers/registry.go
- internal/signature/signature.go
- internal/signature/signature_test.go
- internal/utils/utils.go
- server/admin/handler/handler.go
- server/admin/server.go
- server/finder/http/handler/finder.go
- server/finder/http/protocol_test.go
- server/finder/http/server.go
- server/finder/libp2p/handler/finder.go
- server/finder/libp2p/protocol_test.go
- server/finder/libp2p/server.go
- server/finder/test/test.go
- server/ingest/handler/handler.go
- server/ingest/handler/handler_test.go
- server/ingest/handler/ingest.go
- server/ingest/handler/providers.go
- server/ingest/server.go
- Register trusted provider without discovery
- Immediate ingestion of content over HTTP
- Signature and signature validation on registration and ingestion requests
- Unit tests for handlers
> Use new go-indexer-core interface

- Dockerfile
- Makefile
- scripts/start_storetheindex
Alos added Makefile to make building easier
> Add Dockerfile and entrypoint script

- api/v0/ingest/schema/envelope.go
- api/v0/ingest/schema/gen.go
- api/v0/ingest/schema/ipldsch_satisfaction.go
- api/v0/ingest/schema/ipldsch_types.go
- api/v0/ingest/schema/utils.go
- api/v0/ingest/schema/utils_test.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
This PR:
- Implements a simple `Advertisement` data structure.
- Fixes `ingestion/sync` with new `Advertisement` structure.
> Simpler Ingestion data structures

- api/v0/ingest/schema/utils.go
Quickfix: Adds `LinkContext` to identify Advertismeent links
> Use LinkContext to identify Ad links

- command/daemon.go
- config/addresses.go
- config/init.go
- internal/ingest/ingest_test.go
- Adds to config p2pmultiaddr.
> Add ability to config libp2p multiaddr

- api/v0/ingest/schema/utils.go
- api/v0/ingest/schema/utils_test.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
This PR:
- Changes the IPLD schema used for ingestion to a `LinkedList`
> As LinkedList as the IPLD structure for ingestion

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
This PR:
- Logs every process in the ingestion protocol. It will ease tracking bugs and weird behaviors in the code.
> Logs for ingestion protocol

- command/daemon.go
- server/admin/http/handler.go
- server/admin/http/server.go
> passing right context to admin API. Fixes #79

- command/daemon.go
- command/flags.go
- command/init.go
- e2e_test.go
- go.mod
> add first version of an end-to-end test

- e2e_test.go
> adapt e2e test to new index-provider Go module

- command/daemon.go
- command/init.go
- e2e_test.go
- Fix typo to recognize the value store name
- Allow use of "memory" valuestore (for testing)
- Logging to see time for value store to initialize/open
> Recognize pogreb valuestore name (fix typo)

- .circleci/config.yml
Use new chart verison
made some updates to the chart, just updating the verison.
> new chart version

- go.mod
- go.sum
- server/finder/http/handler.go
- server/finder/http/server.go
Also added a http endpoint to find a single index by CID.
> Update indexer core to latest

- e2e_test.go
This test failed for me because it would take > 2s to index the car. This change makes this a bit less brittle.
> [e2e test] Retry finding the car on provider with timeout

- command/daemon.go
- command/flags.go
- command/init.go
- config/addresses.go
- config/bootstrap.go
- config/datastore.go
- config/discovery.go
- config/indexer.go
- config/ingest.go
- config/init.go
- config/policy.go
- e2e_test.go
- server/admin/http/handler.go
- Config objects have NewXX function to create with defaults
- Allow topic to be set using flag at init time
- Output more useful info to user on daemon start
> Create config objects with defaults set

- config/addresses.go
- config/config.go
- config/datastore.go
- config/discovery.go
- config/indexer.go
- config/ingest.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- version.json
Cache advertisement while processing entry chunks for advertisement to prevent reloading re-validating the same data.
> Fix incorrect log messages

- .circleci/config.yml
Deploy when there is a tag to the us-east-1 cluster
> deploy instance on tag

- go.mod
- go.sum
- version.json
> Bump version for latest fix

- internal/ingest/linksystem.go
We've been hardcoding the assumption that we're dealing with dag-json bytes, but we may not be. 
This uses the codec from the cid to pick the correct decoder.
> Lookup which decoder to use instead of always using dag-json

- internal/ingest/linksystem.go
Code error was preventing ad caching.
Fixes #168 
🤦
> Fix error check is ad cache

- internal/httpserver/util.go
- server/finder/http/handler.go
- server/finder/http/index.html
- server/finder/http/server.go
* i want to be able to update the web page without having to re-deploy the daemon. this makes the index page actually be a frame over to github pages again.
* Adds a /health handler we can point pingdom to.
> add health handler. abstract web handler

- Dockerfile
- Makefile
> put versions into built binaries

- api/v0/ingest/client/http/ingest.go
- api/v0/ingest/client/interface.go
- api/v0/ingest/client/libp2p/client.go
- command/daemon.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- server/ingest/handler/ingest_handler.go
- server/ingest/http/handler.go
- server/ingest/http/handler_test.go
- server/ingest/http/protocol_test.go
- server/ingest/http/server.go
- server/ingest/libp2p/handler.go
- server/ingest/libp2p/protocol_test.go
- server/ingest/libp2p/server.go
- server/ingest/test/test.go
see if this is roughly the shape of an announce handler you'd hope for.
> Add handler for announcing new heads on the ingest server

- internal/ingest/ingest_test.go
s/getLatestSync/GetLatestSync
from an error merging a PR.
> Fix old ref

- .circleci/config.yml
use chart version 13, which adds initContainers.
https://github.com/filecoin-project/helm-charts/pull/122
Related to https://github.com/filecoin-project/lotus-infra/pull/551
> increase chart version

- deploy/infrastructure/dev/us-east-2/kms.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
Trying to access dev cluster @MarcoPolo 
Added ARN user/cmharden and user/steveFraser to aws-auth.yaml and kms.tf
No test, please verify syntax is correct
> Added  cmharden and steveFraser to access K8s 

- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
Missed out in previous PR:
- https://github.com/filecoin-project/storetheindex/pull/308
> Add `cluster-autoscaler` to list of cluster level kustomizations

- deploy/infrastructure/dev/us-east-2/kms.tf
Allow Kyle to interact with KMS keys in dev like rest of the team.
See code.
N/A
> Allow Kyle to interact with dev KMS

- .circleci/config.yml
**Do not merge until the PR linked below is merged and helm chart is published.**
See:
- https://github.com/filecoin-project/helm-charts/pull/139
bump chart version
N/A
`git revert`
> Bump chart version to include templated readiness probe

- go.mod
- go.sum
- version.json
Upgrade overwrites existing index files
> Upgrade storethehash

- go.mod
- go.sum
- version.json
Update to new core with panic fix/logging in it.
> Update to core with storehash panic filx

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
It is increasingly difficult to follow what points where and debug 
issues with infra spread across two aws accounts we don't have 
enough access to.
Destroy the cloudfront stood up manually in fil infra account and point
its alias, `infra.cid.contact` to the existing cloudfront distribution
associated to `cdn.prod.cid.contact`.
Create a fresh certificate for `cid.contact` and all all the aliases
needed by the cloudfront distribution.
Applied already and working:
```shell
curl -is https://infra.cid.contact | grep cache
x-cache: Hit from cloudfront
```
Existing endpoint still works too:
```shell
curl -is https://cdn.prod.cid.contact | grep cache
x-cache: Hit from cloudfront
```
> Point infra.cid.contact to `prod` running in sti AWS account

- doc/config.md
Create an external document that provides an example config file and describes its contents and default values.  Since the contents are already described in godoc documentation, provide links to the godoc documentation instead of duplicating that in a text file.
> Create config file description

- command/daemon.go
- command/find.go
- command/import.go
- command/init.go
- command/init_test.go
- command/register.go
- config/bootstrap.go
- config/config.go
- config/discovery.go
- config/init.go
- config/policy.go
- config/types.go
Init was not writing the current version to a new config file.  This is now fixed.
- Update config documentation
- Update command descriptions
> Fix version written by init

- doc/ingest.md
> update doc with current codes

- deploy/manifests/dev/us-east-2/tenant/storetheindex/config
Remove tailing `,` left behind in previous PRs.
> Fix invalid json in dev config

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- server/ingest/handler/ingest_handler.go
Add additional logging when a direct announce message is accepted or rejected.
> Add logging around announce messages

- internal/ingest/ingest_test.go
- test/typehelpers/typehelpers.go
Across ingest tests assert that target multihashes are eventually
indexed. Because, there is no guarantee that they are indexed after an
explicit sync returns. This should improve stability and reproducibility
of the tests.
Introduce test helper method to select entries only from a single ad
rather than a given ad and all its previous ads. This helps make the
tests more concise in that, the assertions would precisely assert which
multihashes should not have been indexed, instead of asserting partial
indexing of multihashes.
Refactor tests to use existing utility functions with less repeated
logic when it comes to asserting that multihashes are not indexed.
Fixes: https://github.com/filecoin-project/storetheindex/issues/266
> Improve test stability by asserting multihashes are eventually indexed

- doc/config.md
Describes RateLimit configuration
> Update config document for version 2

- server/reframe/reframe.go
Add metrics to the Reframe HTTP endpoint in STI.
Part of https://github.com/libp2p/hydra-booster/issues/162
> add metrics to reframe endpoint

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
In a case where a provider has a consistently growing ad chain where
each ad is explicitly announced while the indexer is in the progress of
processing previously announced ads a race-condition could occur where
the ingestion logic competes with the announce logic for syncing CIDs.
The former competes for syncing the ad entries so that they can be
processed, while the latter competes for syncing the newly announced
ads. As a result, the processing of ads slows down and CPU usage
increases significantly.
To avoid this postpone processing of any explicit announce request while
an ad chain is being processed. Once the ad chain processing finished,
then handle the announce request. Note that we only need to handle the
latest announce request because of the chaining of advertisements; as
long …
> Defer handling of announce until ad chain processing is finished

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
Prevent ingesting entries from ads that are deleted by another ad later (toward head) in chain.
When the chain of ads is first read from head to tail, remember context IDs that are deleted and mark ads deeper in the chain, that have those context IDs, as needing to be skipped.  Then when processing the chain from tail to head, skip ingesting entries for the ads that are marked for skipping and mark those ads as processed.
Fixes issue #53
> Skip ads with context deleted later in chain

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
Create a dedicated policy for routing `/reframe` requests via CloudFront
to let query strings through.
Fixes #550
> Fix `/reframe` routing through CloudFront in `prod`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-config.yaml
Add Logging configuration and other missing default values to the dev config.
> Update dev config with logging and missing settings

- deploy/manifests/base/storetheindex/indexer-config.yaml
Add Logging configuration and other missing default values to the base config.
> Update base config with logging and missing settings

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexer-config.yaml
Add Logging configuration and other missing default values to the prod config.
> Update prod config with logging and missing settings

- deploy/manifests/dev/us-east-2/cluster/autoretrieve/README.md
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/flux-cd.yaml
We're moving deploy scripts for autoretrieve that are specific to bedrocks usage to a seperate repo
Updates the cluster information in the K8s
The deployment repo is otherwise setup and ready to go with sti-bot. I think.
This is deployment changes and I'm not sure how to test
Yes?
> Update autoretrieve cluster information

- internal/ingest/ingest.go
A crash is happening due to a concurrent read and write to a map. Fix this by protecting with mutex.
Need to add protection for both the `providerAdChainStaging` and the `providersBeingProcessed` maps.
> Fix fatal error: concurrent map read and map write

- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
> expand dev disk

- command/daemon.go
- config/addresses.go
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-config.yaml
- server/finder/http/index.html
- server/finder/http/options.go
- server/finder/http/server.go
* load the static external frame as a template and inject in a new config option to set the domain.
> Configure the web page of the index page

- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
Deploy older version to investigate ingestion throughput.
> Deploy `v0.4.16` in dev to investigate slow ingestion

- command/daemon.go
- server/admin/http/server.go
Allows for pprof and metrics during startup
fix #323
> Start metric server at the beginning of the process

- command/daemon.go
- config/indexer.go
currently this is fixed at 24, but may be worth experimenting with a bigger version
> Allow init with a different STH bit prefix

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/identity.key.encrypted
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/pvc.yaml
Deploy `xabi` a fresh prod instance in us-east2b AZ that uses binary
serialization format with 30 bit bucket size.
> Deploy a fresh `prod` instance with binary valuestore codec

- deploy/infrastructure/common/ecr.tf
- deploy/infrastructure/common/github_actions.tf
Set up an ECR repo for `indexstar` and authorise image push to it via
GitHub actions run on the repo.
> Set up ECR for `indexstar` and allow Github Actions push to it

- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Give full access to both dev and prod clusters
> Give Mayank and Ivan access to the K8s clusters

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/kustomization.yaml
This has sti queue PR and sth that uses less memory
> Deploy latest to mya

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
See:
- https://github.com/filecoin-shipyard/indexstar/pull/9
> Fix reframe path join issue in indexstar prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/kustomization.yaml
Deploy GC read lock fix to prod on `tara` node.
> Deploy GC read lock fix to prod `tara`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/config.json
> More core concurrency

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/infrastructure/dev/us-east-2/monitoring.tf
- deploy/infrastructure/dev/us-east-2/vpc.tf
- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/infrastructure/prod/us-east-2/monitoring.tf
- deploy/infrastructure/prod/us-east-2/vpc.tf
- deploy/manifests/base/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/cluster/cluster-autoscaler/patch.yaml
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/cluster-autoscaler/patch.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
> Add extra private subnets to `dev` and `prod` assigned to a new node group

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Fixes https://github.com/filecoin-project/storetheindex/issues/766
> Set memory and CPU limits for indexstar in PROD

- Dockerfile
Use more recent container images.
> Update build and target container images

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Reverts filecoin-project/storetheindex#795 - causes failure increase
> Revert "deploy newer indexstar with simplified reframe strategy"

- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
Fixes #796
When ingesting entries, a "content not found" error was not always being handled or was not detected due to only matching those errors from data-transfer and not from graphsync. This handles all those cases and treats the failure as a permanent error causing ingestion of that ad to be skipped.
> Handle "content not found" when ingesting entries

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/pvc.yaml
This PR expands storage for the romi instance as per recent alert.
> Expanded storage as per recent alert

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy the latest to indexstar which provides reframe over GET request thanks to the 0.5.0 release.
> Deploy the latest to indexstar to allow reframe over GET

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
include fix for https://github.com/filecoin-shipyard/indexstar/pull/30
> use newer indexstar

- internal/ingest/ingest.go
- internal/metrics/server.go
to know how many active chains are being pulled
> add metric for number of active workers

- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/kustomization.yaml
See:
- https://github.com/filecoin-project/storetheindex/pull/816
> Deploy primary gc testing onto dev debug

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/pvc.yaml
`tara`'s PVC is now > 80% utilised.
> Increase `tara` pvc to 20Ti

- internal/ingest/ingest.go
If auto-sync is already running for a provider, do not run another one.
When auto-sync is used to keep in sync, in the absence of announce messages, then it may be run on a small interval. This prevents auto-sync goroutines from building up if auto-sync is triggered while ingesting an advertisement chain.
> Check if auto-sync is already running for a provider

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/kustomization.yaml
Disable cache on mya to see if it increases ingest rate to what arvo has. Also, use latest to check for bad advertisement data.
> Disable sth cache on mya and use latest

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-config.yaml
See what, if anym differentce writing entries synchronously makes during heavy ingestion and reasonable tuning of other params.
> Write entries synchronously to see performance

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/pvc.yaml
> Increased arvo storage

- internal/ingest/linksystem.go
> Fix log message to format publisher and provider ID the same

- deploy/infrastructure/common/github_actions.tf
Add permissions for GithubActions to publish to ECR public.
> Add ecr-public AWS permissions

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/pod-monitor.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
Stand up an instance of indexstar, similar to the set up in `prod`.
Relates to #856
> Deploy `indexstar` on `dev`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts filecoin-project/storetheindex#950 Until https://github.com/filecoin-project/storetheindex/issues/951 is resolved.
> Revert "Add indexers `0` and `1` back to `indexstar` backends"

- go.mod
- go.sum
Necessary update to stop thrashing and falling behind in GC with large freelists
> Apply gc fix in core

- go.mod
- go.sum
Fix missing index to allow primary GC to continue
> Get core missing index fix

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/kustomization.yaml
Deploy the fix to reframe response on `dido` for a test run before rolling out widely on prod.
> Deploy fix to #977 on `dido`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/kustomization.yaml
Fat fingered by @masih in earlier PR.
> Fix invalid image tag on `oden`

- command/daemon.go
- command/flags.go
- command/init.go
- command/init_test.go
- config/discovery.go
- config/indexer.go
- dagsync/announce_test.go
- dagsync/dtsync/util.go
- dagsync/subscriber_test.go
- dagsync/test/util.go
- fsutil/fsutil.go
- fsutil/fsutil_test.go
- internal/fsutil/fsutil.go
- internal/ingest/ingest_test.go
- server/admin/http/handler.go
- server/admin/http/server.go
- Make pebble the default index store
- Remove unused flags
- Reuse flags needed for multiple commands
- Fix admin server when p2p is disabled
- Cancel datatransfer if it takes too long to stop
- Stabilize tests
> Change default value store to pebble

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/kustomization.yaml
Deploy the latest onto both nodes on `dev`
> Deploy latest to both nodes on `dev`

- internal/ingest/linksystem.go
Change metadata only update log level to info
> Change metadata only update log to info

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Remove backend that no longer exist and add `cali`.
> Fix backend config in `dev` indexstar instances

- deploy/manifests/dev/us-east-2/cluster/autoretrieve/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-observer/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/github-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/github-auth.yaml
The GitHub access token was due to expire in 7 days. Refresh it.
> Refresh GitHub access token used by CD

- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
Need new container for assigner
> Deploy assigner on new container

- announce/receiver.go
- assigner/core/assigner.go
- assigner/core/assigner_test.go
This is not a functional change but only code improvement.
- simplify preconfigured assignments
- log direct announce received
- improve test code for test indexers
> Simplify assignment code for preset assignments

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
See: https://github.com/ipni/indexstar/pull/48
> Deploy latest fixes to HTTP delegated translator in `indexstar`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/dido-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/dido-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/kepa-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/oden-snapshot.yaml
> Create configuration to create indexer snapshots

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/kustomization.yaml
> Update kepa to latest version

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
Lets not underutilize this node
> Allow any peers access to oden

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
Do not merge until storetheindex v0.5.4 running in prod
> Deploy assigner v0.5.4 to prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deployed and tested on `dev` already; rolling out on `prod`.
Relates to:
- https://github.com/ipni/indexstar/issues/54
> Deploy metrics and route fix for HTTP delegated routing on `prod`

- deploy/infrastructure/common/ecr.tf
Create a new ECR repository for `dhstore` service.
> Create `dhstore` ECR repository

- api/v0/finder/client/http/dhash_client.go
- api/v0/finder/model/model.go
Align name of fields with dhstore
> Align with dhstore http api

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy latest to indexstar that checks HTTP methods in handlers.
> Deploy HTTP method check to `indexstar`

- dagsync/subscriber.go
Sync does not work if the publisher multiaddr contains a p2p peer ID. This PR detects if there is one and truncates the multiaddress at the start of the /p2p/<peerID> part of the multiaddr.
This allows the sync command to work whether or not the specified publisher multiaddress has a p2p peer ID.
Fixes #865
> Remove p2p peer ID from publisher multiaddr given to sync

- command/daemon.go
- config/indexer.go
- go.mod
- go.sum
Optionally configure core to use DHStore service.
> Configure core to use DHStore

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/infrastructure/dev/us-east-2/vpc.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/deployment.yaml
> Move double hashing node group to ue2a

- doc/scaling-design-for-indest.md
> Move scaling design doc into github

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/infrastructure/dev/us-east-2/vpc.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Increase DHStore RAM in DEV as it has been OOMKilled recently:
```
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    137
Started:      Fri, 27 Jan 2023 10:53:27 +0000
Finished:     Fri, 27 Jan 2023 10:59:44 +0000
Ready:          True
Restart Count:  97
```
> Increase dhstore RAM in dev

- internal/ingest/linksystem.go
When advertisements are not deleted, for keeping a local copy, the entries chunks and HAMTs also need to be kept.
> Keep entries when keeping ads

- deploy/manifests/base/caskadht/deployment.yaml
- deploy/manifests/base/caskadht/kustomization.yaml
- deploy/manifests/base/caskadht/labels.yaml
- deploy/manifests/base/caskadht/pdb.yaml
- deploy/manifests/base/caskadht/service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
Define base manifests for `caskadht` and deploy to `dev`.
> Deploy `caskadht` to `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Include `caskadht` as a backend of `indexstar` on `dev` environment and deploy the latest.
> Add `caskadht` as a backend to `dev.cid.contact`

- server/finder/http/server.go
Check HTTP request header for accepted media types before responding. Only respond if the request accepts the supported media type, i.e. `application/json`, or accepts any, i.e. `*/*`. As a special case, fall back on JSON response if the request has not specified any accepted media types.
Fixes #1209
> Respect HTTP `Accept` header with fallback to JSON

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
> Deploy `Accept` parsing fix to indexstar

- deploy/infrastructure/dev/us-east-2/cloudfront.tf
Adjust cache policy in `dev` so that requests are cached relative to `Accept` and `cascade` query parameter.
> Adjust caching behaviour  on `dev` relative to cascading DHT lookup

- api/v0/finder/client/http/dhash_client.go
* Add extended providers to double hashed client;
* Maintain `ProviderInfo`s cache at the client level instead of per-request. This is done to save up some time on roundtrips as well as to index `ContextualExtendedProviders` by `ContextID` for faster lookup times.
> Add ExtendedProviders to the double hashed client

- version.json
Bump version in preparation for releasing streaming API support over ndjson.
> Bump version to release ndjson support

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/kustomization.yaml
Upgrade services on prod and set up cache config for ndjson on prod.
While at it, upgrade `ago` to latest.
> Upgrade indexstar and kepa on prod with ndjson

- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/identity.key.encrypted
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Deploy the `caskadht` service on prod and add it as a backend to `indexstar`.
> Deploy `caskadht` on `prod` and add to `indexstar`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/ber-snapshot.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/cali-snapshot.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/kustomization.yaml
Snapshot ber and cali PVC to prepare for experimenting with the cheaper volume classes.
> Snapshot `ber` and `cali` PVC in prep for testing with cheaper classes

- go.mod
- go.sum
Upgrade to latest IPLD to fix panic.
> Upgrade to IPLD `0.20.0` to fix panic

- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/service-external.yaml
`dev` is working, expose on prod to prepare for bifronst infra update.
> Expose `caskadht` libp2p node on `prod`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
See:
- https://github.com/ipni/indexstar/pull/76
> Deploy fix to false-positive circuit breaker opening in indexstar

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
See:
- https://github.com/ipni/indexstar/pull/79
> Deploy fix to non streaming accept header in indexstar

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Reverts ipni/storetheindex#1287
Investigating 403 in dev
> Revert "Deploy translation of all non-streaming lookups to streaming on `dev`"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy latest fixes to indexstar on dev
> Deploy latest on indexstar dev

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Test indexstar fixes on dev before rollout to `prod`. Relates to:
- https://github.com/ipni/indexstar/pull/85
> Deploy indexstar fixes to `dev`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Relates to:
- https://github.com/ipni/indexstar/pull/85
> Deploy latest fixes of indexstar to prod and scale out caskadht

- deploy/manifests/dev/us-east-2/cluster/autoretrieve/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-observer/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/github-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/github-auth.yaml
It expired today; rotate the secrets with new tokens.
> Update GitHub token used by CD

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
Update Ago poll interval to 24h as per @gammazero suggestion
> Update ago poll interval to 24h

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
Deploy latest indexer image to ago
> Deploy latets to ago

- version.json
So we can used tagged dep in index-provider
> Bump version for go-data-transfer v2.0.0

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
See:
- https://github.com/ipni/indexstar/pull/89
> Deploy latest to `indexstar` for transport metrics

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Wrong counter was being incremented for graphsync
> Deploy bug fix in indexstar metric collection

- dagsync/dtsync/util.go
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/kustomization.yaml
While at it, fix typo in logs.
Relates to:
- https://github.com/ipni/storetheindex/issues/1371
> Deploy image with extra logging on `ber` to investigate hanging

- deploy/infrastructure/common/ecr.tf
See:
- https://github.com/ipni/lookout
> Create ECR repo for `ipni/lookout`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/pod-monitor.yaml
Working on `dev`; `prod` time.
> Roll out `lookout` monitoring to `prod`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
This PR adds correct http return codes
> Deploy latest dhfind

- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Note: deploying from a commit (not from a release tag) as there have been an ongoing issue with CI.
> Deploy latest sti to prod

- deploy/infrastructure/dev/us-east-2/vpc.tf
- deploy/infrastructure/prod/us-east-2/vpc.tf
Running low on IP in prod. While at it create new ones on `dev` too as we are close to running out on some subnets.
> Create extra private subnets in dev and prod

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Add new general purpose node groups per subnet which includes the newly created subnets.
> Create general purpose node groups per subnet

- deploy/infrastructure/prod/us-east-2/eks.tf
Now that new workgroups run on new subnets, remove old ones.
> Re move migrated work groups on prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
Deploy latest dhstore to both dev and prod
> Update dhstore in dev and prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/kustomization.yaml
Bring kepa in line with the rest of the cluster
> Update kepa version

- deploy/infrastructure/common/ecr.tf
See:
- https://github.com/ipni/cassette
> Create ECR repo for `cassette`

- command/daemon.go
- config/indexer.go
- config/types.go
* add a new configuration for pebble block cache size that is equal to 1gi by default
> Add config for pebble block cache size

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
* Deploy the latest version of dhstore that supports configurable block cache size
* Set block cache to 2Gi that is double the current size
> Deploy latest dhstore to prod

- internal/ingest/ingest_test.go
Stabilize tests that occasionally get bad response from publisher.
> Ingest tests wait for publisher to be ready

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
* Deploy the latest dhfind to prod with the `/cid/` endpoint enabled
* Hook it up to indexer in simulation mode
> Deploy latest dhfind to prod and hook it up to indexstar

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Temporarily removing dhfind as it affects Hydra and NFT.storage due to timeouts.
> Temporarily remove dhfind from prod indexstar

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/service-cluster-ip.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
* Update dhfind to the latest image in prod
* Add ClusterIP service to be used instead of loadbalancer in prod
* Add dhfind to indexstar scattergather in prod
> Change dhfind to use cluster ip in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
increase number of replicas as they are struggling to cope with the volume currently
> Bump dhfind replicas to 4 in prod

- go.mod
- go.sum
This may fix some of the issues hanging on shutdown.
> Update to latest graphsync to get new fixes

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/config.yaml
Update identities for infura nodes, discovered via manual connection.
> Manually update identity for infura nodes

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reduce Inga ingest worker count as dhstore got an inverted LSM in prod
> Reduce Inga ingest worker count

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
See:
- https://github.com/ipni/cassette/pull/21
> Deploy fix to `cassette` in-flight time metric

- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
See:
- https://github.com/ipni/heyfil/pull/13
> Deploy latest heyfil to `prod` with deal list fetch from filecoin tools

- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/dido-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/kepa-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/oden-snapshot.yaml
...in preparation for move to `gp3`.
> Snapshot `prod` persistent volumes

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/kustomization.yaml
Change ber from a one-off to use the common dev sti image.
> Deploy latest on ber

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
* Inga has caught up with the load
* Inga now has volume with a better throughput and IOPS
> Re-enable dhfind in prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Deploy latest to cassette and change infura peers to peer IDs only to
test auto address discovery.
> Deploy cassette auto addr discover in `dev`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Tested in `dev` and existing infura peer addrs already stopped working.
> Roll out auto peer discovery in `cassette` on `prod`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
Deploy to dev dhfind with fix for panic: https://github.com/ipni/dhfind/pull/11
> Deploy to dev dhfind with panic fix

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
Deploy with fix https://github.com/ipni/dhfind/pull/11
> Deploy to prod dhfind with panic fix

- version.json
This is an important fix to get deployed asap.
> bump version for oom fix

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
Lets see what ago can do with latest fix
> Double workers in ago-indexer

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
Enable event logs in prod CloudFront to:
1. check gateway traffic is reaching us.
2. collect data for a research paper in the making by probelab.
Relates to:
- https://github.com/ipni/indexstar/issues/93
> Enable CloudFront logging in prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
> Deploy latest dhfind to dev

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
Update prod to the version of dhfind that supports result streaming
> Update dhfind in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/pvc.yaml
Prod dhstore is approaching 80% threshold
> Increase prod dhstore PVC to 20Ti

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/internal-service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/pdb.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Add a new instance `dhstore-helga` in prod. It's going to be used for writes while the existing one will serve reads only.
> Add dhstore-helga

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/pvc.yaml
Reverting as max volume size is 16Ti
Reverts ipni/storetheindex#1625
> Revert "Increase prod dhstore PVC to 20Ti"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/pvc.yaml
Setting the volume size back to 20Ti to fix reconciliation
Reverts ipni/storetheindex#1630
> Revert "Revert "Increase prod dhstore PVC to 20Ti""

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Deploy latest changes to recipient removal on cassette in dev and prod.
See:
- https://github.com/ipni/cassette/pull/27
> Deploy latest to Cassette

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
Reverting as inga is operational
Reverts ipni/storetheindex#1634
> Revert "Point dhfind to indexstar for provider lookup"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
See:
- https://github.com/ipni/heyfil/pull/15
> Deploy latest Heyfil with support for compressed deal snapshot

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
* Version that supports metadata deletions
> Deploy latest dhstore to dev

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
* Includes support for metadata deletes
> Deploy latest to ago

- go.mod
- go.sum
Includes fix to metadata deletes
> Update to the latest go-indexer-core

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Update both distores in prod with the version that supports deletions
> Update dhstores in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
The version that supports deletions
> Update inga to the latest version

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/kustomization.yaml
Deploying to Helga only to see the effect of the recent fixes
> Deploy latest dhfind to helga in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
Deploy the latest dhfind to the rest of the cluster
> Deploy the latest version to all dhfinds in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/deployment.yaml
* lookup success ratio should stay unchanged
* lookup latencies should go down
> Remove existing indexers in prod canary

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
Reduce dhfind spec in prod as it's underutilised on both CPU and RAM.
> Reduce dhfind spec in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
This update includes updated read latency metric with `foundCaskade` / `foundRegular` tags
> Deploy latest indexstar to prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
> Dev deploy assigner

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Move dhstore prod to the new pvc
> Use new pvc in prod dhstore

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Contains fix in metrics reporting
> Deploy latest indexstar to prod and canary

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
* Give dhfinds 60% of traffic
* Scale up dhfinds to 3 instances each
* Plug dhfinds to main indexstar
* Next step - delete canary.
> Give dhfinds 60% of traffic

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Fix mistake with scaling up indexstar instead of dhfind
> Scale up dhfind prod to 3, reduce indexstar to 2

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/kustomization.yaml
To trace down the issue with disappearing providers
> Deploy extra logging to oden

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
Scale up dhfinds as they aren't coping up with peak loads
> Scale up dhfind

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
> Bump up dhfind CPU limits in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reduce inga worker count to 1 and disconnect dhfind-hela from read path until lim tree gets back into balanced state again
> Reduce inga worker count to 1

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#1736
> Revert "Reduce inga worker count to 1"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
See how batch size of 1 affects throughput.  Doing this on ago instead of separate node, to see effect in aggregate.
> Set DHBatchSize to 1 on ago as experiment

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Reverts ipni/storetheindex#1739
> Revert "Temporarily turn inga off to trigger compaction"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
Reverts ipni/storetheindex#1744
> Revert "Shutdown ago for now to let dhstore catch up"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/pvc-gp3.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
> Stop ago-indexer and increase dhstore pvc size to max

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Increase the CPU resources for dhstore in prod to investigate effect on read amplification and compaction debt.
Cc @ischasny
> Experiment with larger CPU on `dhstore`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Dhstore ran out of space and is crunching through compaction
> Switch double hashed writes to Helga

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
Assigner was serving deprecated HTTP announce endpoint
> deploy assigner that serves correct announce path

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/envoy/envoy-deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/envoy/kustomization.yaml
> Increase CPU limit for dhstore cluster envoy in dev

- version.json
Includes Extended Providers semantics change
> Bump version

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
* Bump up dhstore CPU cores to 7
* Reduce ago ingest worker count to 5
* Temporarily disable ago writes to let dhstore do compaction
> Update dev double hashing configuration

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/kustomization.yaml
> Deploy shard concurrency to data

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
Reverts ipni/storetheindex#1787
> Revert "Revert "Start ago again""

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/pdb.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/internal-service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/pdb.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
* add dhstore-porvy of 5Ti for the time being
* add dhfind-porvy
* hook dhfind-porvy to indexstar
* point inga's write to dhstore-porvy
> Add new dhstore and point inga to it

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/config.json
> Config ago and dana with same workers and batch size

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Further reduce down read only dhstore spec to see the impact on performance
> Further reduce down read-only dhstores spec

- command/daemon.go
- command/init.go
- command/init_test.go
- config/indexer.go
- go.mod
- go.sum
Pogreb is not used by anyone so support is being removed.
> Remove support for pogreb as valuestore

- e2e_test.go
Install a release version of dhstore, instead of cloning whatever is in the current repo.
> Install release version of dhstore

- assigner/command/daemon.go
- assigner/server/option.go
- assigner/server/server.go
- command/daemon.go
- e2e_test.go
- server/find/http/handler_test.go
- server/find/http/options.go
- server/find/http/server.go
- server/ingest/http/options.go
- server/ingest/http/server.go
This makes it easy to check the indexer and assigner version.
> Include version in indexer and assigner health message

- deploy/manifests/dev/us-east-2/cluster/autoretrieve/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-observer/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/github-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/github-auth.yaml
Renew the expired GitHub token used by CI/CD.
> Renew GitHub token used by CI/CD

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-a/aada/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-a/cadi/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-a/saar/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-b/aviv/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-b/dina/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-b/vesa/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-c/bala/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-c/maja/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-c/zora/kustomization.yaml
Reverts ipni/storetheindex#1828
> Revert "Stop dhstore cluster"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#1830
> Revert "Drum Roll: disconnect old indexers from the read path"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#1833
> Revert "Disconnect old indexers: Round 2"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
See: https://github.com/ipni/dhfind/pull/17
> Reduce dhfind RAM in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
With the latest changes dhfinds are underutilised
> Reduce number of dhfinds in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Change the order of backends so that nodes with embedded iframe are first.
> Investigate web ui issue by intexstar

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#1844
> Revert "Increase ingest worker count in Inga"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
See if this makes a difference.
> Double max gs requests

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#1860
> Revert "Switch inga to Helga so that porvy can compact"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#1861
> Revert "Temporarily disconnect porvy from reads"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#1873
> Revert "Temporarily disconnect Helga from reads"

- deploy/manifests/prod/us-east-2/cluster/kustomization.yaml
In preparation for FDB deployment
> Create FDB CRDs in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/pvc_data.yaml
It has reached 80% utilisation.
> Increase `inga` indexer volume to `160G`

- go.mod
- go.sum
Get `dagsync.Subscriber` panic on close fix.
> Update to latest go-libipni

- deploy/manifests/prod/us-east-2/cluster/kube-system/gp3-storage-class.yaml
Add additional `gp3` storage classes with various IOPS and throughput for experimentation.
> Add additional `gp3` storage classes to `prod`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
See:
- https://github.com/ipni/cassette/pull/30
> Deploy latest to cassette in `dev` and `prod`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
See:
- https://github.com/ipni/cassette/pull/31
> Add separate metric for non cancel CID count in cassette

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
See:
- https://github.com/ipni/cassette/pull/32
> Deploy latest to `cassette`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Reverts ipni/storetheindex#1742
> Revert "Revert "Temporarily turn inga off to trigger compaction""

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
See:
- https://github.com/ipni/cassette/pull/34
> Deploy cassette receiver buffer config

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Reverts ipni/storetheindex#1925
> Revert "Deploy cassette receiver buffer config"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Reverts ipni/storetheindex#1927
> Revert "Revert "Revert "Revert "Temporarily turn inga off to trigger compaction""""

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Disconnecting from reads due to alert
> Temporarily disconnect the current dhstore

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
Reverts ipni/storetheindex#1931
> Revert "Pause ago as it has been imbalanced for the last 2 weeks"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/kustomization.yaml
Increase compaction workers count as suggested [here](https://github.com/cockroachdb/pebble/issues/1691#issuecomment-1190467051)
> Deploy latest dhstore experimental configuration

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
* Increase inga's number of workers so that it can catch up with new small announcements quicker while keep on ingesting larger chains.
* Disconnect kepa and dido from reads
> Increase inga ingest worker count to 15

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Inga is failing readiness probe
> Reconnect kepa and dido to reads

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Use `c6a.8xlarge` CPU optimises instanvce types in prep to run FDB on `prod`.
> Create worker node group on `prod` for FDB

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reduce inga's poll interval to be in line with other indexers
> Reduce inga poll interval

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#1946
> Revert "Reconnect kepa and dido to reads"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Account for the two side cars that run with fdb.
> Reduce FDB memory demand further

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/config.json
- e2e_test.go
> Assigner configuration for new prod indexers

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Disconnect oden from reads as we have caught up with dag.house
> Disconnect oden

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
dhstore runs out of CPU that affects read latencies
> Increase CPUs for prod dhstore

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
* Deploys new indexstar to dev
* The new indexstar can distinguish between provider, regular and double hashed lookups and forward those to correct backends
> Deploy new indexstar to dev

- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
> Deploy latest assigner to dev

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/kustomization.yaml
- Get libp2p fixes.
- Include kepa-indexer
> Deploy latest assigner

- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
See:
- https://github.com/ipni/heyfil/pull/18
> Deploy latest to `heyfil`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
See:
- https://github.com/ipni/indexstar/pull/113
> Deploy latest indexstar to serve iframe from it

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Bumping up 
* inga worker count
* inga dhstore batch size 
to see whether inga can catch up faster with more recent announcements
> Bump up inga worker count

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
See:
- https://github.com/ipni/dhfind/pull/26
> Deploy fix for bug in `dhfind` incorrect IPNI non-streaming reponse

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
See:
- https://github.com/ipni/dhfind/pull/28
> Deploy latest to `dhstore`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
See if the fix to define that we have done last night was the cause of lower success rate
See https://github.com/ipni/dhfind/pull/26
> Disconnect oden in prod

- deploy/manifests/base/foundationdb/fdbmeter/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdbmeter/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdbmeter/deployment.yaml
Upgrade to latest in order to rollout fix to process role metric
collection.
> Upgrade to the latest `fdbmeter`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
See:
- https://github.com/ipni/indexstar/pull/128
> Deploy fix to indexstar result aggregation

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reframe transaltion is no longer supported by indexstar.
> Remove no longer supported translate reframe flag

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
> Investigate extended providers records not showing

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/arya/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/bala/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/cera/config.json
Reverts ipni/storetheindex#2007
> Revert "Investigate high FDB storage lag by reducing dhstore batch to 16"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/deployment.yaml
Reduce resources on porvy slightly so that it fits in conjunction with daemonset pods.
> Reduce resources on provy slightly so that it fits

- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/registry/apiconv.go
- internal/registry/registry.go
Set the last error for the provider in the case of sync failure.
> Set last error on sync failure

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-porvy/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
See:
- https://github.com/ipni/dhfind/pull/32
> Roll out fix to dhfind provider aggregation

- go.mod
- go.sum
- version.json
Create a new release in prep for deploying new features to prod.
> new release version

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago2/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#2042
> Revert "Deploy new dhstore-ago2 and replace dhfind-ago2"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- Update indexstar backend to replace dhfind with dhstore
- Update dhstore to new image and specify
- Set dhfind replica count to 0
> Replace last dev dhfind with dhstore

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Reverts ipni/storetheindex#2056
> Revert "Deploy latest to inga"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#2064
Having trubles with inga again
> Revert "Revert "Add old indexers as provider backend while investigating `inga` issues""

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- Update to new dhstore that supports dhfind
- Configure each dhstore with providers URL
> Update to new dhstore

- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/ingress.yaml
> Fix missing subdomain in heyfil prod ingress

- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
See:  https://github.com/ipni/heyfil/pull/29
> Deploy fix to SP ID filter by peer ID in HeyFil

- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
Deploy latest to support HEAD method and fix panic in API server.
> Deploy latest to Heyfil

- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
See:
- https://github.com/ipni/heyfil/pull/33
> Deploy fix to big int aggregation in HeyFil

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Reverts ipni/storetheindex#2104
> Revert "Deploy new indexstar, with pcache, to dev"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- Uses new pcache
- Removes the need for fallbackBackend
> Deploy latest indexstar

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
Reverts ipni/storetheindex#2107
Getting error: `flag provided but not defined: -providersURL`
> Revert "Deploy new dhstore with pcache"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/kustomization.yaml
We are not using these anymore.
> Stop dido, kepa, and oden indexers

- deploy/manifests/base/foundationdb/crds/kustomization.yaml
- deploy/manifests/base/foundationdb/namespaced-manager/kustomization.yaml
Upgrade to the latest FDB controller to take advantage of bug fixes.
> Upgrade to the latest FDB controller

- deploy/manifests/base/foundationdb/namespaced-manager/rbac.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Reverts ipni/storetheindex#2124
> Revert "Increase max generations for FDB in prod during upgrade"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago2/kustomization.yaml
- New response writer
- DHFind logging fix
> Deploy latest dhstore to dhstore-ago2

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/deployment.yaml
As part of investigating the growing compaction debt which cases writes to get delayed increase stop write and max compaction concurrency.
> Increase compaction parallelism and stop wirte threshold on dhstore qiu

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
since helga is running out of space
> Switch inga-indexer to write to dhstore-qiu 

- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
Test out filtering miners by status on heyfil dev instance.
Relates to:
- https://github.com/ipni/heyfil/pull/36
> Deploy heyfil filtering by status on dev

- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
Relates to:
- https://github.com/ipni/heyfil/pull/36
> Deploy heyfil filtering by status on prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#2143
Switching back to dhstore-helga
> Revert "Switch inga-indexer to write to dhstore-qiu "

- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/pvc.yaml
The instances have run out of disk. Expand to 1Gi.
> Expand HeyFil PVC to 1Gi

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#2146
Switch back to writing to dhstore-qiu now that it has more storage.
> Revert "Revert "Switch inga-indexer to write to dhstore-qiu ""

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
This version has bootstrap panic fix
> Deploy latest indexer as ago

- deploy/infrastructure/common/.terraform.lock.hcl
- deploy/infrastructure/common/ecr.tf
> Create ECR for telemetry service

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
This one removes extra newlines between streaming json records.
> Deploy latest indexstar image to dev

- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/pod-monitor.yaml
> Dev deploy telemetry

- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
More memory efficient
Less logging
> Update telemetry service image

- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
Records over-limit distances as max.
> update telemetry service

- assigner/core/assigner.go
- assigner/core/assigner_test.go
> Allow assigner to start with zero indexers

- deploy/manifests/dev/us-east-2/cluster/index-observer/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/tornado/github-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/github-auth.yaml
Re-generate all tokens used by Flux CD.
> Rotate github tokens used by Flux CD

- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/telemetry/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
> Deploy latest telemetry with graphsync fix

- deploy/infrastructure/dev/us-east-2/index-provider.tf
- deploy/infrastructure/dev/us-east-2/kms.tf
- deploy/infrastructure/dev/us-east-2/tornado.tf
- deploy/infrastructure/prod/us-east-2/kms.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Remove references to Kyle's IAM user and aws-auth K8S config map.
Thank you Kyle for everything.
> Remove alumni user from infra

- version.json
Create new release with latest fixes.
> New version

- deploy/infrastructure/dev/us-east-2/.terraform.lock.hcl
- deploy/infrastructure/prod/us-east-2/.terraform.lock.hcl
> Update Terraform lock files with latest provider versions

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#2204
Go back to using dhstore-qiu
> Revert "Switch dhstore backend to investigating degraded ingest"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-ravi/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-ravi/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-ravi/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-ravi/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
dhstore-qiu is out of space, so create dhstore-ravi
> Create new dhstore node dhstore-ravi

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
> deploy metrics update to dev

- go.mod
- go.sum
Has a fix that will result in a slight improvement in ingestion workload.
> Use latest go-libipni

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Reverts ipni/storetheindex#2263
> Revert "Deploy latest indexstar to prod"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Reverts ipni/storetheindex#2270
> Revert "Redeploy indexstar to prod"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Reverts ipni/storetheindex#2272
> Revert "Deploy fixed indexstar to prod"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/internal-service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/pod-monitor.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/pvc.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
The current dhstore-ago3 is full, so create dhstore-ago4.
> Create a new dhstore node in dev

- test/testipnirunner.go
When this environ variable TEST_IPNI_RUNNER_OUTPUT is set to a value, and running tests with -v flag, then TestIpniRunner output is logged. Otherwise, do not log output as this makes it difficult to see output from the actual tests being run.
> Make it configurable to print testrunner output

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Both of these changes have been in use on dev
> Deploy sti with peerstore fix and no http retry

- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/deployment.yaml
> Increase memory limit for heyfil in prod

- .github/workflows/publish-ghcr.yml
- version.json
Requested by clients, additionally publish containers onto ghcr.
> Publish containers on GitHub container registry

- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/pvc.yaml
bump image in that environment to 2gb volume claim as it is in dev
> promote latest heyfil to prod

- server/admin/handler.go
> do not hold mutex over net i/o

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
temp fix until provider fix available
> super long http timeout

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#2326
> Revert "super long http timeout"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
This will take the place of dhstore-ravi as the active write dhstore
> Create dhstore-seka in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/deployment.yaml
Reverts ipni/storetheindex#2339
> Revert "try deplopy dhstore in 2a"

- deploy/infrastructure/prod/us-east-2/eks.tf
Already terraform applied and confirmed in aws.
> Resize prod eks node groups

- deploy/manifests/prod/us-east-2/cluster/cluster-autoscaler/patch.yaml
> Increase memory for cluster autoscaler

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/deployment.yaml
Reverts ipni/storetheindex#2338
> Revert "Try deploy with less cpu"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Move the last dhstore read-only node to memory optimised nodes in prod.
> Move last dhstore read-only on prod to memory optimised nodes

- deploy/manifests/dev/us-east-2/cluster/index-observer/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/tornado/github-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/github-auth.yaml
Current ones have expired; regenerate and update.
> Update Github CD secret for all pipelines

- command/admin.go
- deploy/manifests/base/storetheindex-single/config.json
- deploy/manifests/base/storetheindex/indexer-config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- internal/ingest/linksystem.go
- Remove unused config item StoreBatchSize.
> Poll less frequently as erroring providers are slowing workers

- deploy/manifests/dev/us-east-2/cluster/storetheindex/github-auth.yaml
This is preventing deployments from working.
> Fix typo in dev github-auth.yaml

- deploy/manifests/prod/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
Reverts ipni/storetheindex#2374
> Revert "shutdown telemetry as experiment"

- .github/workflows/ecr-publisher.yml
- config/discovery.go
- internal/registry/registry.go
- internal/registry/registry_test.go
> Temproarily block publishers that publish unusable ad chains

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/pvc_data.yaml
Put ago-data on gp3 pvc
Fixes #2349
> ago-data on gp3 pvc

- deploy/manifests/prod/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
Fix errors not getting cleared.
> Deploy new telemetry service

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
> Start using the new dhstore node

- e2e_test.go
- ipni-gc/cmd/ipnigc/daemon.go
- ipni-gc/cmd/ipnigc/provider.go
- ipni-gc/reaper/option.go
- ipni-gc/reaper/reaper.go
Ad chains my be very long, so it is necessary to sync them by segment.
> GC syncs ad chains by segment

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago5/deployment.yaml
Reduce resource limit and demand for dhstore on dev for better infra utilisation.
> Rightsize dhstore on dev

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago5/deployment.yaml
Remove explicit instance type selector and further reduce CPU
> Remove explicit node type selector for dhstore in dev

- config/bootstrap.go
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Remove bootstrap nodes, whose names no longer resolve, from config.
> Remove dead bootstrap nodes

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
Turn off debug logging until error seen
> Dev info logging

- command/updatemirror.go
Copy from read mirror to write mirror concurrently. This greatly improves update speed.
> Concurrent mirror updates

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
See:
* https://github.com/ipni/indexstar/pull/185
> Deploy latest changes to peer schema on `dev`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-tetra/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Also, scale down previous primary dhstore-tetra and dhstore-seka
> Change primary dhstore

- deploy/manifests/dev/us-east-2/cluster/index-observer/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/github-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/github-auth.yaml
Update the expired CD pipeline token.
> Update Github auth token used by CD pipeline

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
The dh qiu instance is almost fully utilised; switch to porvy as primary write.
> Switch to dh porvy as primary write instance

- deploy/manifests/prod/us-east-2/cluster/storetheindex/github-auth.yaml
Update the github token used by CD.
> Update CD github token

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/berg-ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Configure cloudfront to send all request to berg.
> Hook up cloundfront to berg

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
> deploy assigner

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Reverts ipni/storetheindex#2652
> Revert "update deployment config"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Reverts ipni/storetheindex#2651
> Revert "Allocate larger instance to primary write dhstore"

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/sf-ingress.yaml
Due to a freeze bug we need to re-ingest ads from all providers for the last 18 hours or so on berg.
For now switch to SF as primary.
> Set up ingress and switch to SF as primary

- command/daemon.go
- command/init.go
- config/indexer.go
- go.mod
- go.sum
Add relayx as a backing indexer interface in storetheindex.
> Integrate relayx into storetheindex daemon
