ipni/storetheindex

- store/primary/primary.go
- store/primary/primary_test.go
Needed to add items found in the previous cache to the current cache.
When an item is not found in the current cache but is found in the previous cache, that item needs to be put into the current cache.  Doing this requires a write lock on the cache. In order to avoid locking the entire cache, instead just acquire a lock for any key that would affect the same part of the tree.
Put needed to check for existing values in the previous cache.
Also added a unit test for cache rotation.
> Change locking implementation works

- node/import.go
- store/persistent/persistent.go
- store/primary/primary.go
- store/primary/primary_test.go
- store/store.go
Instead of having to release a read lock and acquire a write lock and redo a lookup, whenever an entry is put into the current cache from the previous, just exclusively lock the cache.  To lessen lock contention with concurrent access use multiple cache instances over which keys are evenly distributed.
Implement a method to remove single entry (provider-ID + piece-ID) from the cache.
> Use multiple caches to for concurrent access

- node/find.go
- node/import.go
- store/persistent/persistent.go
- store/primary/primary.go
- store/primary/primary_test.go
- store/store.go
Removed these in a previous PR, but they should be there in case an underlying implementation returns errors.
> Return errors from Storage interface

- store/primary/cache.go
- store/primary/primary.go
- store/primary/primary_test.go
Store only one copy of each distinct `IndexEntry`, per cache.  This reduces memory consumption as many identical `IndexEntry` values may be mapped to by different CIDs.
- Added `Stats` function to get cache stats. 
- Perform some operations concurrently
- Added Memory usage tests and benchmarks
> Intern entries to conserve memory

- go.mod
- go.sum
- store/persistent/benchmarks.go
- store/persistent/pogreb/pogreb.go
- store/persistent/pogreb/pogreb_bench_test.go
- store/persistent/pogreb/pogreb_test.go
- store/persistent/storethehash/storethehash.go
- store/persistent/storethehash/storethehash_bench_test.go
- store/persistent/storethehash/storethehash_test.go
- store/persistent/tests.go
Depends on: https://github.com/filecoin-project/storetheindex/pull/10
This PR: 
- Implements `StorageFlusher` interface for Pogreb.
- Organizes the code so persistent storage implementation can reuse core unit tests and benchmarks code.
__Sidenote regarding storetheindex storage interface: Is true that pogreb and storethehash are quite alike, but implementing a new k-v storage for our interface has been quite straightforward and no changes have been needed in the interface. It may be worth doing this same exercise with a full-fledge database like PostgreSQL to further validate this.
Also, worth checking this out for alternatives to Pogreb: https://github.com/akrylysov/pogreb/issues/38#issuecomment-850852472__
//cc @gammazero
> Pogreb-backed persistence

- go.mod
- node/import.go
- store/primary/cache.go
- store/primary/primary.go
- store/primary/primary_test.go
- store/store.go
The information associated with a CID will depend on the provider protocol.  This has been changed from storing PieceID to storing a byte slice that starts with a uvarint  to encode a protocol number that will indicate how to decode the following bytes.
- IndexEntry does not have PieceID, but now has uvarint + data
- Add Memory use tests for primary (run with `TEST_MEM_USE=1 go test -v`)
- Rename IndexEntry.ProvID -> IndexEntry.ProviderID
> API takes IndexEntry instead of providerID + data

- README.md
- commands/flags.go
- commands/import.go
- store/persistent/benchmarks.go
- store/persistent/pogreb/pogreb.go
- store/persistent/storethehash/storethehash.go
- store/persistent/tests.go
- store/store.go
This is a follow-up PR to finish propagating the interface changes, that use IndexEntry instead of provider and piece ID.
> Finish propagating interface changes through code

- README.md
- commands/find.go
- commands/flags.go
- commands/synthetic.go
- node/find.go
- node/import.go
- node/node.go
- node/storage.go
- node/storage_test.go
- store/persistent/benchmarks.go
- store/persistent/pogreb/pogreb.go
- store/persistent/pogreb/pogreb_bench_test.go
- store/persistent/pogreb/pogreb_test.go
- store/persistent/storethehash/storethehash.go
- store/persistent/storethehash/storethehash_bench_test.go
- store/persistent/storethehash/storethehash_test.go
- store/persistent/tests.go
- store/primary/primary.go
- store/primary/primary_test.go
- store/store.go
- Add `nodeStorage`, which wraps the combination of a cache and a persistent storage and implements the `Storage` interface. It includes the pass-through logic, and is the backend storage for `node`. It has been decoupled from the daemon so this logic can be used as a library instead of embedding it in the node's daemon. 
- Add a slight modification to `Put` and `Remove` in `Storage` (changing output from `err` to `(bool, err)`) for convenience.
- Renamed `StorageFlusher` to `PersistentStorage` in case we end up adding (as briefly discussed) a `CacheStorage` interface.
- Refactored `synthetic`commands.
- Fixed issue with flags, and storage config in daemon.
- Update README.
- Additional benchmarks for persistent storage.
Next: 
- Add stats for `nodeStorage` (cache hits/miss, persistence …
> Implemented node storage. Fixed synthetic. Interface changes

- store/persistent/pogreb/pogreb.go
- store/persistent/storethehash/storethehash.go
- store/persistent/storethehash/storethehash_test.go
- store/store.go
- Fixes a bug where `storethehash` persistence wasn't starting its sync routine and was not periodically flushing from memory.
- Adds unit test.
> Fix storethehash periodic flush

- utils/load/README.md
- utils/load/load.py
- utils/load/run.sh
- Include assets to run load tests against a `storetheindex` daemon using https://locust.io/
- Add README to guide through how to replicate the tests
> Assets to run load tests using locust

- command/daemon.go
- command/flags.go
- command/fsutil.go
- command/init.go
- command/init_test.go
- config/addresses.go
- config/config.go
- config/datastore.go
- config/indexer.go
- config/init.go
- config/providers.go
- main.go
- server/finder/http/protocol_test.go
- Only use CLI flags for overriding some config values, otherwise all values come from config file
- Store datastore and valuestore config in config so it can be read by future migrations
- Unit test for init command
- Reorg command flags
- Fix daemon signal handling and shutdown
> Read daemon config values from config file

- api/v0/ingest/schema/gen.go
- api/v0/ingest/schema/ipldsch_satisfaction.go
- api/v0/ingest/schema/ipldsch_types.go
- api/v0/ingest/schema/utils.go
- api/v0/ingest/schema/utils_test.go
- go.mod
- go.sum
This PR:
- Adds support for `CarEntries` in schema and utils.
- Removes graphSupport field.
> Added support for CAR entries in schema and utils

- command/flags.go
- command/ingest.go
- main.go
- server/admin/http/handler/ingester.go
- server/admin/http/server.go
This PR:
- Adds a few commands in CLI to interact with the indexer's admin API to manually trigger ingestion operations. These commands are mainly targeted for testing purposes.
> Integrate ingest admin interface into CLI

- command/ingest.go
The constructed path otherwise would not include protocol and is off.
> Construct correct path when calling `ingest sbuscribe` with `-i`

- api/v0/ingest/schema/gen.go
- api/v0/ingest/schema/ipldsch_satisfaction.go
- api/v0/ingest/schema/ipldsch_types.go
- api/v0/ingest/schema/utils.go
- api/v0/ingest/schema/utils_test.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
This PR:
- Updates the schema to use a linked list of bytes for ingestion.
- Adds utils to generate advertisements from a list of multihashes
- Integrates the new schema into the ingestion protocol.
> Ingest multihashes as a linked list of Bytes instead of a list of CIDs

- command/register.go
- config/config.go
- config/init.go
- config/policy.go
- internal/providers/policy/policy.go
- internal/providers/policy/policy_test.go
- internal/providers/registry.go
- internal/providers/registry_test.go
- server/finder/test/test.go
- server/ingest/http/handler_test.go
- server/ingest/test/test.go
Trusting a provider means that if the provider is allowed, then on-chain varification of the trusted provider's ID is not required.
Policy can now specify both "allow" by default and "trust" by default.  These can be inverted to make it necessary to explicitly specify allowed and trusted providers.  The default config, generated by init, sets policy to allow all and trust all.
Fixes issue #73
> Provide a way to trust all providers by default

- api/v0/ingest/client/http/ingest.go
- api/v0/ingest/client/interface.go
- api/v0/ingest/client/libp2p/client.go
- api/v0/ingest/models/ingest_request.go
- api/v0/ingest/models/ingest_request_test.go
- api/v0/ingest/models/register_request.go
- api/v0/ingest/models/register_request_test.go
- command/register.go
- server/ingest/http/handler_test.go
- server/ingest/test/test.go
- Fix Register to use intrinsic and model data types only
- Fix IndexContent to use intrinsic and model data types only
> Use api model data types only in client api

- internal/metrics/server.go
This is what is running to create this 
https://protocollabs.grafana.net/d/pPROWOD7z/providers?orgId=1
The metrics don't appear until they are first used, but as soon as you index something you see them. 
```
▶ indexer-reference-provider index -i localhost  -a /ip4/3.143.149.162/tcp/3103 -cid QmPNHBy5h7f19yJDt7ip9TvmMRbqmYsa6aetkrsc1ghjLB -meta "demo-data"
OK Indexed content
▶ curl -s localhost:3002/metrics | grep store
storetheindex_provider_count 1
```
> register the views

- api/v0/ingest/model/provider_info.go
- api/v0/ingest/schema/utils.go
- e2e_test.go
- go.mod
- go.sum
- internal/handler/ingest_handler.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- server/finder/http/options.go
When a remove advertisement does not contain a list of entries, then remove all entries that have the context ID specified by the advertisement.
Other changes included:
- Update last advertisement in registry
- Record last contact time for each provider in registry (in prep for polling)
- Periodically update storage size metric
- Simplify batch update logic (only need to do remove or put, not both)
- Do not use "i" as the name of a receiver
- Provider info API returns LastAdvertisement instead of LastIndex
- Misc. code cleanup
> Remove indexed content by context ID

- e2e_test.go
Need to work around the inability to `go install` the provider cmd module that has replace directive.
> Make e2e test work with provider cmd module

- config/config.go
- config/config_test.go
- config/datastore.go
- config/indexer.go
This is needed to be able to have the valuestore and datastore located outside the storetheindex repo.
> Recognize absolute paths in config

- command/fsutil.go
- go.mod
- go.sum
This update provides a critical performance fix to the storethehash valuestore.
- Unrelated error message fix included in PR.
> Update to go-indexer-core v0.2.5

- go.mod
- go.sum
This is backwards compatible with a provider that uses an older version of go-legs, because the latest go-legs can still decode messages that do not include the address data.  It just means that the provider and indexer must be directly connected, until the provider also using the latest go-legs.
> Update to latest go-legs

- Makefile
- api/v0/admin/client/http/client.go
- api/v0/ingest/client/http/ingest.go
- api/v0/ingest/client/libp2p/client.go
- command/find.go
- command/flags.go
- command/import.go
- command/ingest.go
- command/init_test.go
- command/synthetic.go
- config/bootstrap.go
- config/ingest.go
- e2e_test.go
- internal/httpclient/client.go
- internal/importer/cidlist.go
- internal/importer/manifest.go
- server/admin/http/handler.go
- server/admin/http/server.go
- test/load/README.md
The storetheindex commands needed a number of fixes for errors and inconsistencies.  The changes include the following:
- Makefile build target builds without running tests.
- Remove unused endpoints from `ingest` client.
- Add `Sync`, `Subscribe`, and `Unsubscribe` to admin client.
- Add comment about specifying port to http client.
- Admin client needed to return after http.Error
- Return proper error on sync failure.
- Fix misnamed command flags in `import` command.
- Used admin client in `ingest` command.
- Only `daemon` command should write to log.
- Fix progress output in `synthetic` command.
- Fix error handling in init test.
- The `find` command takes multiple `--cid` and `--mh` flags.
> Make a number of fixes to the indexer commands

- test/load/README.md
- test/load/load.py
The README now contains instructions on how to generate test data to use for load tests.  So, it is not necessary to store a large (16MB) data file in this repo.
> Generate test data when/if needed

- go.mod
- go.sum
Upgrade to the latest go-legs which uses the same version of
go-libp2p-pubsub as the sofia miner
> Upgrade to latest go-legs

- e2e_test.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
Configure the background leg sync to only sync advertisement chain. Sync
entries separately via storage hook by first checking if they are
present already.
Note that the semantics of explicit Sync is changed by this commit where
Sync returns when the advertisement is synced _excluding_ entries.
Change ingest tests to assert that expected multihashes are indexed
eventually. Remove evil `time.Sleep`s where possible in existing tests.
Fixes #136
> Selectively sync advertisements then entries only if absent

- api/v0/ingest/schema/utils.go
- config/discovery.go
- config/policy.go
- go.mod
- go.sum
- internal/handler/ingest_handler.go
- internal/httpclient/client.go
- internal/lotus/discovery.go
- internal/registry/registry.go
- server/ingest/http/protocol_test.go
- server/ingest/libp2p/protocol_test.go
- server/ingest/test/test.go
Want to limit contextID length sooner rather than later so that the indexer does not store content that is no longer updatable because the contextID becomes unacceptable in the future.
Fixes #112
> Limit contextID length, and misc fixes

- command/find.go
- e2e_test.go
- internal/ingest/linksystem.go
If a removal advertisement has a context, then remove content by contextID, regardless of whether the add includes an entries link or not.  Individual entries will only be removed if an empty context ID is given.
Other changes:
- Added removal test to end-to-end test.
- Do not output raw binary contextID from find command.
> Remove by contextID for removal ads that have contextID

- internal/ingest/linksystem.go
- internal/ingest/linksystem_test.go
Multiple ad in a chain of advertisements may have the same entries CID.  This caused reverse mapping of entries CID to ad CID, for the first ad received to get stepped on by the same mapping for the sencond ad received having that same entries CID.  This fixes this by maintaining a mapping of entries CID to a stack of ad CIDs.
> Allow multiple ads in a chain to have the same entries CID

- internal/ingest/linksystem.go
The previous change removed the dagjson import which unregistered the codec.
> Side effect import to register the dagjson codec

- api/v0/finder/model/model_test.go
- api/v0/ingest/model/ingest_request_test.go
- api/v0/ingest/schema/utils_test.go
- config/ingest.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- server/finder/test/test.go
- server/ingest/test/test.go
- test/util/util.go
Add a configuration value that allows limiting the recursion depth when
syncing the advertisement entries with default value of 400. The default
of 400 in conjunction with default chunk size of 16384 in index-provider
would accommodate a default total of 6,553,600 multihashes, which seems
like a reasonably large number.
> Limit the depth of recursion when syncing advertisement entries

- e2e_test.go
This is a good example of why non-reproducible tests are tricky. I spent at least half an hour debugging this before I realized it was because of something **outside** this repo. Specifically this commit: https://github.com/filecoin-project/index-provider/commit/e5a9c5499341c48bcb86466ee656cacbb692b8b6
I get that it's annoying if this was a specific hash of the other repo. But there's probably a better solution.
> [e2e_test] Change pubsub topic name because indexprovider changed

- config/ingest.go
- go.mod
- go.sum
- internal/ingest/ingest.go
By default sync at most 400 unseed advertisements and expose ingest
config parameter to override it.
> Limit the recursion depth when syncing advertisements

- api/v0/ingest/schema/envelope.go
- e2e_test.go
The wrong function was being used to create a multihash of the advertisement, resulting in signing the ad data instead of a hash of it.
Fixes #164
> Sign a hash of the advertisement data

- server/finder/http/handler.go
Otherwise, we see big latency times for large batch finds.
> Make FindLatency metric per multihash

- api/v0/admin/client/http/client.go
- api/v0/finder/client/http/client.go
- api/v0/ingest/schema/envelope.go
- internal/ingest/ingest_test.go
- version.json
There are still many advertisements that are using the deprecated signature format.  Since these ads are still valid, allow the indexer to process them.  Log when an ad with a deprecated signature format is seen.
This will allow the new indexer to be deployed without requiring an update to any data providers/publishers.
Other changes:
- Removed some unwanted/unneeded logging from finder and admin client
- Update version
> Add compatibility with old signature format

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- server/finder/handler/finder_handler.go
When reading a chain of advertisements, the indexer uses the addresses from the last ad received, which is the earliest on the chain.  This PR fixes this so that the indexer updates to provider address using the last ad on the chain.
Fixes #193 
Other features in this PR:
- Cleanup any temproary entry cit to ad cid mappings.  The could be leftover from an unexpected termination of indexer and need to be cleaned up on restart.
- When processing a chain of advertisements, a removal of content by contextID causes the indexer to skip syncing entries from previous ads in the chain that have that same contextID. Fixes #124
> Update provider addrs using latest advertisement

- internal/ingest/linksystem.go
When skipping ads, the initial reverse mapping of entry cid to ad cid needs to be deleted.  Also, when deleting by context ID the ad will have no entries, so a reverse mapping should not be created.
> Cleanup entry to ad reverse mapping when skipping ads

- api/v0/protocol_ids.go
- command/daemon.go
- command/flags.go
- config/addresses.go
The admin, finder, and ingest servers can be individually disabled by using the keyword "none" as their http listen address. They can also be disabled by the `--noadmin`, `--nofinder`, and `--noingest` flags to the daemon.
> Optionally disable individual servers in config or CLI

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
Fixes a deadlock when we call `Ingester.Close`. This happens because we close
the subscriber before waiting for all the syncAdEntries goroutines to finish.
This means you can have a goroutine waiting hopelessly for a go-legs'
`subscriber.Sync` call to finish. By flipping the order you wait for the
goroutine to finish before shutting down go-legs.
Also adds  a test that checks if we handle the duplicate entries chunk case correctly.
(Adding this test uncovered the bug since it would hang after the test seemingly finished).
> Handle deadlock on ingester close

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/metrics/server.go
Just a couple tweaks around the metrics to make them more useful or give them a better description.
- Set hasUpdate to be initially true so that we set the storeSize on restart
- Ad a new metric for count of successful ad syncs
- Add a new metric for total latency of ad ingest
I'm hesitant to add any more metrics until we have a need for them. Also there's probably a couple things we want to record inside go-legs (like httpsync vs. dtsync which should be transparent to the ingester).
> A couple of metric tweaks

- server/ingest/handler/ingest_handler.go
- server/ingest/http/handler.go
If you called the Announce endpoint you'd get some error like:
```
Failed to execute fetch request {"err": "Get \"http://127.0.0.1:8070/head\": context canceled"}
```
This is because the `h.ingester.Sync` function was called with the context of
the http request. And as soon as the http response was returned the request
context was cancelled.
Pass a context.Background() instead since this is a background task.
this is built on top of @gammazero's https://github.com/filecoin-project/storetheindex/pull/207 update legs PR to avoid conflict thrashing.
> Use context background so background task can continue

- api/v0/ingest/schema/envelope.go
- api/v0/ingest/schema/utils.go
- version.json
Export the function that is used to sign advertisements so that it can
be reused for testing purposes in `index-provider`.
Note that its counterpart verify function is already exported.
Bump version in preparation for release.
> Export function that signs advertisements

- api/v0/admin/client/http/client.go
- command/admin.go
- command/flags.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- server/admin/http/handler.go
- server/ingest/handler/ingest_handler.go
Add the ability to specify the recursion depth when syncing from a
provider via `admin sync` command. The flag `depth` now takes a
recursion depth limit. If non-zero, the depth is used to construct a
custom selector that:
1. Recurses to the specified depth
2. Stops at the currently latest synced ad
Fixes: #222
> Add admin `sync` with custom recursion depth

- go.mod
- go.sum
- internal/ingest/linksystem.go
There is no longer any ability to provide specific entries to remove as part of a removal advertisement.  Now all entries, associated with the removal advertisement's context ID are removed.  The value of entries is ignored for a removal advertisement.
> Removal advertisements always delete all content for context ID

- api/v0/admin/client/http/client.go
- command/admin.go
- command/flags.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- server/admin/http/handler.go
- server/ingest/handler/ingest_handler.go
Add an option that allows an explicit sync to continue beyond the CID of
an advertisement that is already synced.
This is useful for cases where the ad recursion limit is expanded and
already synced advertisements need to be re-synced beyond the previous
recursion limit.
Relates to: #222
> Allow explicit sync to proceed beyond the latest synced advertisement

- api/v0/admin/client/http/client.go
The depth and nolatest query params were not getting set in the URL. This fixes the the issue.
> Encode query params into URL

- e2e_test.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
A special case check to see if the current head is already synced is needed when using a selector with a stop node, because the selector only checks if the previous node is the stop node.
> Need special case check if already synced

- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
When resyncing or syncing to a new head, the latest synced ad should be recorded.
When not doing a resync, and only setting a custom depth, make sure that go-legs still sends a sync done event since a non-nil selector is used for the custom depth.
> Explicit Sync always updates latest synced

- command/daemon.go
- config/addresses.go
- go.mod
- go.sum
- version.json
We were hitting this bug: https://github.com/libp2p/go-yamux/issues/79
This updates the go-libp2p dep to fix that bug
> Fix nil ptr crash on websocket conns

- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
Ads were not being cached correctly due to inverted logic about when to cache.
Delete ad from datastore as soon as it is read into cache.
> Fix use of ad cache

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- test/typehelpers/typehelpers.go
There was no way to exit early if we encountered an error while processing ads. It would just skip the ad that errored, and keep ingesting the ad chain. This is a problem in the case where we temporarily can't get an ad (network is temporarily down). Previously we would skip the ad and try ingesting the next one. That would lead to many wrongfully skipped ads.
Instead, when encountering a network flake, we should stop processing the whole ad chain. Then we can try again later.
Of course there are some errors we encounter while processing an ad that aren't temporary. For example, the ad could be malformed. In that case we do want to skip the ad.
Create a new adIngestError type. This type includes the general kind of error this was (was it a permanent error or a temporary sync error). The …
> Return more information on ad ingest errors

- internal/ingest/ingest.go
- internal/metrics/server.go
We need more obs into our ingest process.
This uses the changes from #237 to give us better obs into errors around adIngest. Also cleans up the ambiguity with the adSyncedCount metric (which conflated success and skipped).
> Record errors during ad ingest

- server/ingest/handler/ingest_handler.go
Now that cbor-gen correctly reads from an io.Reader we can drop this workaround.
> Remove readBeforeErr hack now that cbor-gen bug is fixed

- internal/ingest/ingest.go
Accidentally increased error metrics when the error wasn't a special error. So error metric would increase on `err == nil`.
This fixes it.
> Only increase error metric on error

- config/discovery.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/ingest/handler/ingest_handler.go
If the indexer has had no contact with any publisher for a provider, the indexer attempts to sync with the provider's last known publisher.  As long as there is no contact with a publisher for the provider, the indexer continues retrying to sync periodically until contact is made or until the indexer gives up after a configurable abount of time.
> Indexer auto-syncs after period of no contact with publisher

- command/daemon.go
- command/flags.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- Reduce logging by logging some facilities at info or debug
- Log progress when processing chain of ads
Log volume is reduced when logging at info or debug level, by setting the log level to "warn" level.  This can be canceled by using the "log-all" flag.
> Reduce log volume and log progress

- go.mod
- go.sum
- server/finder/http/server.go
as you can see at https://cid.contact currently, query requests fail to load the json due to lack of cors cross-domain.
> add cors headers to find interface

- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/ingest/synchandler.go
- internal/metrics/server.go
- test/typehelpers/typehelpers.go
This hooks up the changes from https://github.com/filecoin-project/go-legs/pull/106. See that PR for more context.
The latestSync state of go-legs now asks the indexer what the last ad processed was. The indexer ignores updates on latestSync from legs, since the indexer is the source of truth here.
Added a test that repros that bug.
> Set latestsynchandler on go legs

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
This fixes a bug where an ingest loop loads an ad (and thereby deleting it) and for whatever reason fails to finish ingesting the ad. The next time the loop tries to ingest the ad it will fail to load the ad and skip it.
Note this happens if we are ingesting the same ad chain back to back.
Don't delete the ad when we load it. Instead only delete the ad when we've finished processing it, since that's really the only time we'll know that we'll never need this ad again.
Most of this diff is the test. The actual fix is just deleting the delete call in `loadAd`.
This also adds a test to make sure we correctly ingest all ads in the case that we are given the same adChain back to back. Which can happen in at least the following cases:
1. A publisher broadcast the same head twice in gossipsub
2. …
> Don't optimistically delete an Ad

- e2e_test.go
This reverts commit 537eb37a1285ba065dfbfc669df83244eabe1f03 now that
the index-provider is upgraded.
See:
- https://github.com/filecoin-project/index-provider/pull/198
> Revert "Skip e2e tests until provider side is upgraded."

- api/v0/ingest/schema/utils.go
- server/ingest/handler/ingest_handler.go
- server/ingest/test/test.go
Set the maximum number of bytes acceptable as advertisement metadata to
`1KiB`, i.e. `1024` bytes. This value is a fixed upper limit and not
configurable by design to ensure interoperability across indexer nodes.
Fixes: #261
> Set the maximum acceptable length for advertisement metadata

- command/flags.go
- config/ingest.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- test/typehelpers/typehelpers.go
Limiting traversal depth for advertisement chains and entry chains is not a reliable mechanism for preventing DoS, and can cause the indexer to serve incorrect content if advertisements are missed, and incomplete content if entries are missed when the limits are configured too low.  Rate limiting will be used to prevent busy publishers from starving others, instead of depth limiting.
A large non-configurable depth limit is still in effect for the entries list but is large enough that it should only apply to misconfigured badly-behaving publishers.
> Remove recursion depth limits for sync

- go.mod
- go.sum
Update to the latest version with the leak fix.
> Fix a goroutine leak in go-libp2p-swarm

- go.mod
- go.sum
Fix go-routine leak in go-statemachine, used by go-data-transfer, that can result in thousands of unrecoverable goroutines in the indexer after a few days of operation.
> Fix goroutine leak in go-statemachine

- config/ingest.go
- e2e_test.go
- internal/ingest/linksystem.go
Deliver a slice of multihashes to the batch processing goroutine, instead of one multihash at a time.  Reuse alternating slices of multihashes so that one is filling while the other is written to the indexer.
> More efficient batch processing of multihashes

- version.json
IPLD bindnode integration makes API changes in the Ingest schema. Bump
version in preparation for release.
> Bump version to `0.4.0` after bindnode merge

- internal/metrics/server.go
- server/finder/http/handler.go
- server/finder/libp2p/handler.go
We were only recording the find latency when we actually found the multihash. This lead to a huge discrepancy between the indexer.get and the find calls.
We should always be recording this.
I also added another tag on whether we found the thing or not, which should highlight if 404s are more expensive than found items.
> Fix find latency metric

- deploy/manifests/base/ingress-nginx/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
Install `nginx` ingress controller onto dev K8S cluster using an overlay
on top of base `ingress-nginx` kustomization.
Note that this should get automatically installed once merged to main now that we have a CD pipeline running for cluster level changes.
See context.
N/A
`git revert`, commit and merge to `main`. CD would then remove it from dev cluster.
> Install `nginx` ingress controller on dev K8S cluster

- config/identity.go
- config/identity_test.go
Right now the container deployment entails using `envsubst` just to populate secret values in a json file, the only way indexer reads peer identity.
In order to reduce complexity and improve security when deploying the indexer in containerized environment, provide a way to set the private key via a path spevified as `STORETHEINDEX_PRIV_KEY_PATH` environment variable.
This then allows private key to be generated separately by an admin and mounted as a file with limited permissions.
The config was also not checking whether the given peer ID matches the private key which this PR fixes.
It is unclear why indexer asks for peer ID at all since it can always be generated from private key. For now this PR keeps the scope of changes small by keeping the peer ID as is..
* allow the identity to be …
> Allow the ability to configure private key via file

- deploy/infrastructure/dev/us-east-2/kms.tf
- deploy/infrastructure/dev/us-east-2/outputs.tf
- deploy/infrastructure/dev/us-east-2/versions.tf
- deploy/manifests/base/flux-system/kustomization.yaml
- deploy/manifests/base/storetheindex/config
- deploy/manifests/base/storetheindex/finder-service.yaml
- deploy/manifests/base/storetheindex/indexer-statefulset.yaml
- deploy/manifests/base/storetheindex/ingest-service.yaml
- deploy/manifests/base/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/flux-system/cluster-cd.yaml
- deploy/manifests/dev/us-east-2/cluster/flux-system/kust-ctrlr-sa-patch.yaml
- deploy/manifests/dev/us-east-2/cluster/flux-system/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/flux-cd.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/flux-rbac.yaml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/.sops.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/identity.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
Define `kustomization` base for storetheindex as a statefulset along with overlay that deploys it to the dev cluster. This work also adds encrypted secret management via [sops](https://github.com/mozilla/sops) and KMS to securely check in encrypted secrets into code, and have the CD pipeline decrypt them on the fly by assuming roles that permit it to do so.
* Define base storetheindex manifest overlay
* Define dev concrete overlay to deploy storetheindex
* Set up secret management and generate a random libp2p identity for the dev instance  
N/A
`git revert` then `terraform apply` for infrastructure part.
Relates to: #287
> Deploy storetheindex to dev cluster

- api/v0/finder/model/provider_info.go
- e2e_test.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/finder/handler/finder_handler.go
- server/ingest/handler/ingest_handler.go
The publisher addresses may be different than the provider addresses, and will not remain in the peerstore across restarts.  This PR stores the last publisher ID and addresses as part of the provider information.  When triggering an auto-sync, the publisher address is now used.
- ProviderInfo has additional string field that is persisted
- Publisher address is used by autoSycn
- Publisher info returned in response to `/providers` query
Validate that publisher address is saved and correct publisher address is loaded.
> Store publisher address with publisher ID

- api/v0/ingest/schema/envelope.go
- api/v0/ingest/schema/envelope_test.go
Added comments to document that the advertisement does not have to be signed by the provider, and a test to show this.
This addresses #257
Demonstrates that it is still necessary to check that the signer of an advertisement is allowed to sign the advertisement.
- Added comments
- Added test to show valid signature on advertisement, when not signed by provider.
- Show valid signature on advertisement, when not signed by provider
> Add comments and tests for ad signature

- internal/metrics/pprof/pprof.go
- server/admin/http/server.go
The /debug/pprof endpoint was serving an index html, but the links were incorrect.  The handlers were also not available at the correct links.  This fixed these problems, and all pprof functionality, including profiling and tracing, is available through the admin interface.
Correct how `/debug/pprof` endpoint is registered with the admin server.
Manual testing with all endpoints
> Fix pprof handlers

- deploy/infrastructure/dev/us-east-2/couldfront.tf
Hitting `dev.cid.contact` makes a call to indexer every time. Considering the nature of data being served, this PR sets up caching using CloudFront accessible via `cdn.dev.cid.contact`
Define:
* CloudFront distribution for dev
* New viewer certificate in `us-east-1`; existing cert used by ingress only lives in K8S.
* `A` records for `cdn.dev.cid.contact`
```sh
$ curl -kIs https://cdn.dev.cid.contact | grep x-cache
x-cache: Hit from cloudfront
```
`git revert` then `terraform apply`
Relates to: #286
> Set up caching layer for dev endpoint using CloudFront

- deploy/infrastructure/dev/us-east-2/cloudfront.tf
Cache 404s for 5 minutes in cloudfront
Tested this in my own cloudfront setup.
`git revert` and `terraform apply`
> Cache 404s in cloudfront

- deploy/infrastructure/dev/us-east-2/autoscaler.tf
- deploy/infrastructure/dev/us-east-2/outputs.tf
- deploy/manifests/base/cluster-autoscaler/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/cluster-autoscaler/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/cluster-autoscaler/patch.yaml
Use [autoscaler](https://github.com/kubernetes/autoscaler) to automatically manage EC2 instances in `dev` EKS cluster node group depending on the workload that's running.
**Note: to avoid destroying resources already applied in #301, that PR is merged into this PR.**
* Add base layer for `cluster-autoscaler`
* Configure roles necessary for the autoscaler to do its job.
* Define overlay in dev cluster for autoscaler, assign the role to its service account and make configuration changes specific to dev for the auto-scaler deployment object
N/A
`git revert` then `terraform apply`
> Set up cluster-autoscaler in `dev`

- internal/registry/registry.go
When registering or updating the registry with provider information that does not have provider addresses or publisher addresses, an out-of-bounds panic could happen because it was assumed that the provider info would at least have provider addresses.
This is not assumed now.  If the situation is detected it is logged.
> Fix out of bounds panic in registery

- deploy/infrastructure/dev/us-east-2/monitoring.tf
- deploy/infrastructure/dev/us-east-2/outputs.tf
- deploy/manifests/base/monitoring/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/monitoring/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/monitoring/patch.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/pod-monitor.yaml
Set up stack to monitor the K8S cluster, worker nodes and extra K8S metrics. Add pod monitor for indexer instance.
Install [`kube-prometheus`](https://github.com/prometheus-operator/kube-prometheus) stack which gives us:
* prometheus operator 
* grafana
* node exporter
* adapter for k8s metrics
* kube-state-metrics
Set up monitoring for pods belonging to the `indexer` running in dev cluster.
This PR also creates an AWS managed prometheus along with necessary roles to interact with it. But the `remote_write` is not hooked up because, the version of operator installed does not support `SigV4` authentication. K8S cluster needs to be upgraded for us to install a newer version, and that will be done in future PRs. For now, this PR installs a grafana instance accessible locally via port …
> Set up K8S monitoring for `dev` cluster

- deploy/manifests/base/monitoring/kustomization.yaml
See: https://github.com/prometheus-operator/kube-prometheus/issues/1708
Changing to SSH seems to fix the problem; I am not sure why. Captured:
- https://github.com/prometheus-operator/kube-prometheus/issues/1708
Many thanks to @marcopolo for pointing this out.
local build with the same version of `kusotmize` as flux cd works after the change to SSH.
`git revert`
> Fix `MalformedYAMLError` when kustomization uses HTTPS to clone repo

- deploy/manifests/base/monitoring/kustomization.yaml
Using SSH for remote build in kustomize requires SSH key set-up which `kustomize-controller` is not shipped with, expectedly.
Try a different format to specify remote build in kustomization to work around a rendering issue in kustomization and avoid using SSH since it requires extra setup in flux.
remote build URL reformat but using HTTPS
Local build with the same version of `kustomize` used by `kustomize-controller` works.
`git revert`
> Specify remote build for `monitoring` in HTTP but different format

- deploy/manifests/dev/us-east-2/cluster/kube-system/io2-storage-class.yaml
- deploy/manifests/dev/us-east-2/cluster/kube-system/kustomization.yaml
Define `io2` storage class with reasonable defaults in `dev` cluster
`io2` storage class offers better performance in terms of storetheindex requirements.
Define `io2` storage class with reasonable defaults in `dev` cluster
N/A
`git revert`
> Add `io2` storage class to dev cluster

- command/daemon.go
- config/indexer.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- version.json
Use a new version of go-indexer-core that includes the latest go-storethehash with index garbage collection.
- Update dependency on go-storethehash
- Make storethehash GC interval configurable
Included in go-storethehash
This is not safe to revert since it automatically upgrades the storethehash index format.
To revert, it would be necessary to write a converter that converts multiple index files back into a single index file.  This would be relatively simple as it would mean writing the old header to a file and appending all the index files to that file.  However, this is not available immediately and would need to be written.
> Use storethehash that has index GC

- go.mod
- go.sum
- version.json
It may be possible to corrupt an index file if the indexer crashes while they are being written.  This fixes this situation by trimming the unusable portion of an index file.
> Use storethehash with corrupted file fixer

- deploy/manifests/README.md
- deploy/manifests/prod/us-east-2/cluster/cert-manager/issuer.yaml
- deploy/manifests/prod/us-east-2/cluster/cert-manager/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/cert-manager/sa-patch.yaml
- deploy/manifests/prod/us-east-2/cluster/cluster-autoscaler/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/cluster-autoscaler/patch.yaml
- deploy/manifests/prod/us-east-2/cluster/external-dns/deploy-patch.yaml
- deploy/manifests/prod/us-east-2/cluster/external-dns/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/external-dns/namespace.yaml
- deploy/manifests/prod/us-east-2/cluster/external-dns/sa-patch.yaml
- deploy/manifests/prod/us-east-2/cluster/flux-system/cluster-cd.yaml
- deploy/manifests/prod/us-east-2/cluster/flux-system/kust-ctrlr-sa-patch.yaml
- deploy/manifests/prod/us-east-2/cluster/flux-system/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/io2-storage-class.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/patch.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/flux-cd.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/flux-rbac.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/namespace.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/.sops.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexer-0-identity.encrypted
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexer-1-identity.encrypted
- deploy/manifests/prod/us-east-2/tenant/storetheindex/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/pod-monitor.yaml
K8S manifests to deploy cluster level and sit to self-Managed prod cluster.
Define the prod kustomization overlay, which is pretty much the same as
dev overlay, with the following differences:
- storetheindex demands specific taints to run on r5b instance type
- indexer replica count is increased to 2
https://prod.cid.contact 
Currently deployed with CD pipelines pointing to this PR for testing.
`git revert`
> Define prod kustomization overlay

- deploy/infrastructure/prod/us-east-2/.terraform.lock.hcl
- deploy/infrastructure/prod/us-east-2/autoscaler.tf
- deploy/infrastructure/prod/us-east-2/backend.tf
- deploy/infrastructure/prod/us-east-2/cert_manager.tf
- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/infrastructure/prod/us-east-2/external_dns.tf
- deploy/infrastructure/prod/us-east-2/kms.tf
- deploy/infrastructure/prod/us-east-2/locals.tf
- deploy/infrastructure/prod/us-east-2/main.tf
- deploy/infrastructure/prod/us-east-2/outputs.tf
- deploy/infrastructure/prod/us-east-2/route53.tf
- deploy/infrastructure/prod/us-east-2/versions.tf
- deploy/infrastructure/prod/us-east-2/vpc.tf
production environment infrastructure set up in storetheindex aws account region `us-east-2` while we wait for the PL managed clusters to be created.
Define terraforms that instantiate production infrastructure pretty much
identical to dev environment with following changes:
- larger instance types in EKS nodegroup
- a dedicated r5b instance type node group to take advantage of high
IOPS of io2 type EBS volumes supported by this type.
The terraform also removes duplicate tags by setting them all once in
the terraform `aws` provider. It also changes the naming convention for
IAM resources by using `path` that includes both region and environment
name to avoid naming conflicts across multiple environments created in
the same region of the same AWS account.
Applied.
`terraform destroy` `git …
> Define production infrastructure in `us-east-2`

- deploy/infrastructure/prod/us-east-2/ebs_csi_driver.tf
- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/infrastructure/prod/us-east-2/outputs.tf
- deploy/manifests/base/aws-ebs-csi-driver/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/aws-ebs-csi-driver/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/aws-ebs-csi-driver/patch.yaml
- deploy/manifests/prod/us-east-2/cluster/kustomization.yaml
The EBS CSI controller installed by EKS as addon doesn't seem to provide
taint control configuration. Install the controller directly so that:
1. we have better control over its configuration.
2. we avoid clash with CD-managed manifests applied via gitops
With this change, the controller daemonset is configured to run on all
nodes regardless of their taint. Before this change, the daemonset was
not being scheduled on r5b nodes which meant we could not create io2
volumes on those nodes which defeated the whole point of having r5b node
types.
The changes here also create the IAM role needed by the controller to do
its job and patches the corresponding controller service account. This
was missing in earlier PRs.
Tried out manually on cluster.
`git revert` and `terraform apply`
> Configure EBS CSI controller to run on all nodes

- .github/workflows/ecr-publisher.yml
- deploy/infrastructure/common/.terraform.lock.hcl
- deploy/infrastructure/common/backend.tf
- deploy/infrastructure/common/ecr.tf
- deploy/infrastructure/common/github_actions.tf
- deploy/infrastructure/common/locals.tf
- deploy/infrastructure/common/main.tf
- deploy/infrastructure/common/outputs.tf
Use public ECR to make `storetheindex` containers available.
Create an IAM role with minimal permissions for GitHub Actions that
allows it to publish images to public ECR repositories owned by
storetheindex. The role uses GitHub OIDC provider for authentication and
is only allowed to be assumed for builds in storetheindex repo.
Set up a GitHub Actions build that is triggered on either merge to main
branch or tag `v*` that builds and publishes container images to the
storetheindex public ECR repo. The container image tag is determined
based on the event that starts up the build:
- if the build is triggered by a tag starting with `v` then the
container image will be whatever came after the `v` in tag, i.e. semver.
- otherwise, it will be a timestamp at which build was run plues `-`
plus the …
> Set up public ECR and publish containers via CI

- deploy/infrastructure/dev/us-east-2/ecr.tf
- deploy/infrastructure/modules/ecr/main.tf
- deploy/infrastructure/modules/ecr/variables.tf
Reverting back to private ECR repo, because:
* despite AWS docs claim that public ECR supports Docker Registry HTTP API, it does not provide `tags/list` endpoint. 
* that endpoint is needed by flux cd to list the available tags to then automate image updates.
See issue: https://github.com/aws/containers-roadmap/issues/1262
Reverts filecoin-project/storetheindex#347
> Revert "Remove redundant private ECR repo"

- .github/workflows/ecr-publisher.yml
- deploy/infrastructure/common/ecr.tf
- deploy/infrastructure/common/github_actions.tf
- deploy/infrastructure/dev/us-east-2/ecr.tf
Move the private ECR repo creation from `dev` to `common` infra folder,
because it is used by both production and dev environment.
Remove the public ECR since it does not fully support docker registry
API despite docs claiming so.
Adjust github actions role and CI job to now publish images to the
private ECR repo.
Manually tested
`git revert`
> Remove public ECR and publish images to the private repo instead

- .github/workflows/ecr-publisher.yml
- deploy/manifests/dev/us-east-2/cluster/storetheindex/flux-cd.yaml
Deploy automation loop caused by image build on all merges to main
For updates pushed by `sti-bot` do not build and publish images to ECR.
This is because it causes an infinite loop of PRs and deployments since
every merge to main builds and pushes docker images.
Skip CI for changes pushed by flux image update automation.
N/A
`git revert`
> Do not publish to ECR if pusher is `sti-bot`

- command/flags.go
- go.mod
- go.sum
- internal/ingest/linksystem.go
When retrieving an advertisement over HTTP, the indexer gets the wrong publisher address.  The indexer should get the address that the advertisement was retrieved from as the publisher address.
When an advertisement is retrieved via HTTP, the publisher address is not in the peerstore.  The indexer then uses the provided address as the publisher address, since it cannot find an address for the publisher.  To get the HTTP address it is necessary to get the http peerstore from go-legs and look there first.
Also, revised command flags to correctly specify publisher or provider peer ID.
Manual testing
Safe to revert.
> Fix wrong publisher address when using HTTP

- deploy/manifests/base/storetheindex/indexer-statefulset.yaml
- deploy/manifests/base/storetheindex/kustomization.yaml
- deploy/manifests/base/storetheindex/pdb.yaml
We want to maintain availability during deployment, and during other admin operations like worker node drainage.
* Specify readiness probe so that pods are not used to serve incoming requests unless ready.
* Specify pod disruption budget so that we tell the cluster the maximum unavailable pods allowed.
N/A
`git revert`
> Configure readiness probe and pod disruption budget

- deploy/manifests/dev/us-east-2/cluster/storetheindex/flux-cd.yaml
Seems like the skip message stops running the Dev CD job too.
see commit message
N/A
`git revert`
> Remove skip message from image update automation

- .github/workflows/ecr-publisher.yml
- deploy/manifests/README.md
ECR build seem to still run when merging CD created PRs.
Ignore the entire `deploy` director in ECR build.
> Fix ECR build still running on sti bot pushes to `deploy` directory

- deploy/infrastructure/dev/us-east-2/cloudfront.tf
- deploy/infrastructure/dev/us-east-2/ebs_csi_driver.tf
- deploy/infrastructure/dev/us-east-2/locals.tf
- deploy/infrastructure/dev/us-east-2/outputs.tf
- deploy/manifests/dev/us-east-2/cluster/aws-ebs-csi-driver/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/aws-ebs-csi-driver/patch.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
PVC IOPS improvement for storetheindex in `dev`. Tying this out first in `dev` before `prod` changes. 
Deploy EBS CSI controller to be able to provision io2 storage class and
patch the storetheindex manifests to use `io2` instead of the existing
`gp2` for better performance.
N/A
> Use io2 storage class for indexer pods in `dev`

- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
Include CSI manifests in dev cluster kustomization.
Missed out in previous PR.
> Add AWS EBS CSI to dev cluster manifests

- command/daemon.go
- command/flags.go
- command/init.go
- config/config.go
- config/discovery.go
- config/ingest.go
- config/policy.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/registry/errors.go
- internal/registry/policy/policy.go
- internal/registry/policy/policy_test.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/finder/test/test.go
- server/ingest/handler/ingest_handler.go
- server/ingest/http/handler_test.go
- server/ingest/test/test.go
Some advertisement publishers what to have a different provider specified in advertisements.
Have a list of `exemptfromselfpublish` peers, who are exempt from needing to only list themselves in advertisements
> support a list of peers from which we accept advertisements for other providers

- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
CSI controller has already been installed. Patch the statefulset to use
`io2` storage class for better performance
See commit message.
Running the same on dev.
`git revert`. Note change to statefulset needs to be handled manually since it is editing an immutable field.
> Use `io2` storage class for `prod` instances

- deploy/manifests/prod/us-east-2/cluster/storetheindex/flux-cd.yaml
An inline image is specified in prod kustomization. But it gets
overridden by flux.
Remove the override so that prod deployment can proceed until we
automated deployment is set up for prod, like it has for dev.
> Don't override image in prod until auto deploy is set up

- .github/workflows/dev-cd.yml
The dev CD job that creates a PR to trigger deployment fails if the pr
is already open. 
Check if the error we get is caused by that and if so
end job gracefully.
Manually tested
`git revert`
> Skip dev CD job if PR it should create exists already

- .github/workflows/ecr-publisher.yml
ECR build is not triggered on tag. Quote the glob format to see if that
fixes it.
While at it, ignore changes to `doc` in ECR build.
> Quote glob format to select tags

- deploy/manifests/dev/us-east-2/cluster/kube-system/io2-storage-class.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/io2-storage-class.yaml
`dev` and `prod` run in the same region, and the IOPS quota for io2
volumes in a region is `100,000`. 
To unblock deployment, reduce IOPS per GiB across storage classes in both dev and prod so that volumes can be
provisioned.
Higher quota is requested already.
N/A
`git revert`
> Reduce iops per GiB for storage classes to unblock deployment

- deploy/infrastructure/dev/us-east-2/.terraform.lock.hcl
- deploy/infrastructure/dev/us-east-2/ebs_csi_driver.tf
- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
See commit message.
Upgrade the dev cluster to latest so that we can install the latest
monitoring overlay that supports sigv4 auth.
Rename node groups in dev clsuter to have human readable name.
Update minimum instance count to 3 so that we have one node per az.
N/A
> Upgrade dev cluster to 1.22

- deploy/manifests/base/monitoring/kustomization.yaml
Now that both clusters are upgraded to 1.22, upgrade the kube-prometheus
manifests to run the latest compatible with the clusters which comes
with upgraded prometheus operator allowing us to specify SigV4 auth to
forward monitoring info to AWS managed prometheus.
See commit message.
This change updates the base manifests which means both `prod` and `dev` environments will be upgraded.
N/A
`git revert`
> Upgrade monitoring manifests now that K8S clusters are on 1.22

- deploy/infrastructure/dev/us-east-2/monitoring.tf
- deploy/infrastructure/dev/us-east-2/outputs.tf
- deploy/manifests/dev/us-east-2/cluster/monitoring/patch.yaml
- deploy/manifests/dev/us-east-2/cluster/monitoring/prometheus-patch.yaml
Use AWS managed services to store metrics collected in dev cluster
Configure service account credentials and remote write settings for the
`dev` prometheus instance to write metrics to the aws managed
prometheus.
N/A
> Set up remote write for dev metrics to aws managed prometheus

- command/admin.go
- command/providers.go
Some flags were previously renamed but commands needed to use new names.
Update commands to use new flag names
manual
safe to revert
> Use new flag names in commands

- deploy/infrastructure/dev/us-east-2/monitoring.tf
- deploy/infrastructure/dev/us-east-2/vpc.tf
- deploy/manifests/dev/us-east-2/cluster/monitoring/kustomization.yaml
For better security, use AWS PrivateLink to talk to internal AWS services from VPC.
Avoid sending metrics over internet gateway, and instead set up a vpc
endpoint interface for accessing AWS managed Prometheus workspaces in
dev.
Add the missing patch resource to monitoring kustomization missed out in
earlier PR.
N/A
> Send metrics to AWS managed prometheus via private link

- deploy/manifests/base/promtail/config.yaml
- deploy/manifests/base/promtail/daemonset.yaml
- deploy/manifests/base/promtail/kustomization.yaml
- deploy/manifests/base/promtail/rbac.yaml
Machinery to forward logs from K8S clusters to Loki
While waiting for access to PL grafana, define the base kustomization
overlay that adds promtail used for forwarding container logs to a Loki
server.
Relates to #392
N/A
`git revert`
> Define base promtail kustomization used for log forwarding

- .github/workflows/ecr-publisher.yml
Originally the ECR publisher CI job was configured to publish images to the ECR repo when a new tag `v*` was published. But it did not get triggered.
The issue is that tags in this repository are handled  by CI automation,
and it is a bot account that pushes the tag. In Github Actions events
generated by bot accounts do not trigger other jobs unless they use a
PAT that belongs to a non-bot user. Ideally, we want to avoid having PAT
in CI secrets that belong to individuals, and instead want to use the
built-in GitHub CI token.
To work around this, the ECR publisher is changed to publish container
images tagged with semver when a GitHub Release is published. Because,
in this repo the releases are made by the contributors and creating a
release should trigger the job.
Update paths-ignore …
> Publish containers to ECR repo when a release is created

- deploy/infrastructure/prod/us-east-2/.terraform.lock.hcl
- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
To improve resilience against AZ failure, we want the indexer instances
to be spread across multiple AZs. So that, failure of one AZ does not
result in downtime.
Increase worker count of type r5b in prod so that e have one in each AZ.
Configure topology spread constraints for indexer statefulsets in dev
and prod such that they are _preferably_ spread across the AZ in which
each worker node runs.
N/A
> Spread indexer instances across AZs when possible

- deploy/infrastructure/common/outputs.tf
- deploy/infrastructure/common/pl-grafana.tf
- deploy/infrastructure/dev/us-east-2/monitoring.tf
The metrics produced by the dev K8S cluster are written to an AWS
managed Prometheus instance.
In order to integrate with the central PL grafana account we need an IAM
user credentials, since the only supported authentication mechanism
between Grafana cloud and AWS managed prometheus is SigV4.
Create authentication credentials for integration of sti prometheus
instance with PL grafana via SigV4 authentication.
Create a group with read-only access to Prometheus and add pl-grafana
user to it.
Applied already and tested with integrating PL grafana with dev prometheus instance.
> Create pl-grafana IAM user to integrate with PL Grafana

- deploy/infrastructure/prod/us-east-2/monitoring.tf
- deploy/infrastructure/prod/us-east-2/outputs.tf
- deploy/manifests/prod/us-east-2/cluster/monitoring/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/patch.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/prometheus-patch.yaml
`prod` cluster monitoring and integration with PL grafana
Connect the separated prod monitoring stack to write to a dedicated AWS
managed prometheus instance.
Same setup running on `dev`.
> Write `prod` metrics to a dedicated AWS managed prometheus

- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
Use resources consistent with what is set in fil environments.
> Configure resources for `dev` amd `prod`

- command/admin.go
- command/find.go
- command/flags.go
- command/import.go
- command/providers.go
- command/register.go
This removes the need to specify the `indexer` CLI flag when running commands against a local indexer.
Usually, the indexer listens on a port other than 80, but if the `indexer` flag is not specified for CLI commands, then localhost:80 is used as the default.  This PR changes CLI the behavior so that when no `indexer` flag is given, the value is read from the config file if available.  Depending on the command, either the finder address or the admin address is read.
> If no value for "indexer" CLI flag, then read from config

- go.mod
- go.sum
- version.json
Update storethehash to version with buffer flushing and corrupted index recovery logic.
Storethehash was susceptible to corruption due to unflushed write buffers during non-graceful termination.  This parblem has been addressed, and code has been added to recover from corrupted index or primary.
Unit tests included with storethehash
Safe to revert
> Update storethehash to get index recovery fix

- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
The CD pipeline for prod environment is not set up yet. In the meantime,
use the latest release commit in the prod manifests:
- `f93b333c402b71820b04efdd2629884eaa636cf7`
Once CD is set up this will be updated automatically just like it is
now for `dev` environment.
> Deploy the latest release to `prod` environment

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-1-identity.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
In order to match the number of replicas running in `prod` environment
and provide better resilience against AZ failure.
> Scale up `dev` to 2 instances

- .github/workflows/cd.yml
- deploy/manifests/prod/us-east-2/cluster/storetheindex/flux-cd.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/github-auth.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Automate image update and deployment PR for `prod`.
Configure an image update automation mechanism, so that it:
- scans the ECR repo for image tags in semver format
- updates the image tag of `prod` Kustomization with the latest found
semver
- commits the changes to `cd/prod` branch
- opens a PR, the merge of which would result in the rollout of that
semver to `prod` environment.
Manually tested.
`git revert`
> Configure image update automation for `prod`

- .github/workflows/cd.yml
Use branch name instead of full ref to extract environment name
> Fix regex replacement in automated PR creation template

- command/flags.go
- command/init.go
- config/config.go
- config/datastore.go
- config/indexer.go
- config/ingest.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- server/admin/http/handler.go
- server/finder/test/test.go
* Put depth limit settings back into config as means to protect against endless chains.
It may be necessary to have depth limits to protect against unreasonably long chains of advertisements and entries.  Might as well make this configurable, so added them back to config.
* Log publisher of advertisements that fail to parse.
If publishers create advertisements that fail to decode, logs should indicate who that publisher is.
* Upgrading the config works even if config file is at current version.
If items from a config are missing or have been removed so that default values are used, it can be useful to recreate those items in the config file to see what values are available.  This can now be done by running `./storetheindex init --upgrade`  at anytime.
* Config upgrade renames previous …
> Log and config update

- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
Worker node types are r5b.xl which have maximum of 32GB. The nodes are
dedicated to indexer but run other administrative daemonsets, like log
forwarder EBS controller and kubelet nodes.
Leaving some head room for other controllers.
> Increase memory and CPU for indexer on `prod`

- deploy/manifests/prod/us-east-2/cluster/cluster-autoscaler/kustomization.yaml
Extra worker nodes are span up and the ones running indexer get selected
as candidate for eviction. disable the autoscaler while investigating
why.
This will avoid unnecessary re-deployments in the meantime.
> Disable autoscaler in prod to investigate the selection policy

- api/v0/ingest/schema/schema.go
cids are truncated to the first half of the sha256 digest
Use the default mhlength on the cid prototype
go test continues to pass
revert
> use default cidlink length

- deploy/infrastructure/common/ecr.tf
- deploy/infrastructure/common/github_actions.tf
- deploy/infrastructure/common/pl-grafana.tf
Define a dedicated ECR repository for `index-observer` in `us-east-2`
and allow GitHub Actions to assume the roles necessary to build and push
container images to it.
While at it reformat terraform files in `common` via `terraform fmt`.
> Define `index-observer` ECR repo and CI to build and push images

- deploy/manifests/dev/us-east-2/cluster/index-observer/README.md
- deploy/manifests/dev/us-east-2/cluster/index-observer/flux-cd.yaml
- deploy/manifests/dev/us-east-2/cluster/index-observer/flux-rbac.yaml
- deploy/manifests/dev/us-east-2/cluster/index-observer/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/index-observer/namespace.yaml
Configure cluster-level Flux CRDs for `index-observer` with the same
policies used for `storetheindex`.
Add README to clarify that application-level manifests will live in the
`index-observer` repo.
> Configure flux cd for `index-observer` on `dev` cluster

- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
Add the index-observer to the list of manifests applied to the dev
cluster.
> Add `index-observer` to dev cluster manifests

- deploy/infrastructure/common/ecr.tf
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/.sops.yaml
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/README.md
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/flux-cd.yaml
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/flux-rbac.yaml
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/namespace.yaml
- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
While `autoretrieve` is being developed, provide a temporary place it
can be deployed in such that metrics could be forwarded to PL grafana
along with logs etc. All of this is already set up in sti EKS clusters.
Create a dedicated ECR repository for automating the build and push of
`autoretrieve` container images. It looks like the exising one is
manually created and pushed to. Here we create a separate one to avoid
any conflicts.
> Onboard `autoretrieve` as a temporary tenant of sti `dev` cluster

- deploy/infrastructure/common/github_actions.tf
Allow the GitHub Actions running from
`application-research/autoretrieve` and push container images to ECR
repos at storeteindex AWS account.
While access on the repo is being granted, also allow builds from a
personal fork of `autoretrieve` so that progress can be made. This will
be removed once access is granted.
> Allow GitHub Actions from ARG autoretrieve repo to publish to ECR

- deploy/infrastructure/dev/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/cloudfront.tf
`cid.contact` should allow `PUT` to `/ingest/announce` for go-legs HTTP
publishers. Further, `cid.contact` is fronted by the cloudfront caching
and `PUT` was not allowed in the cloudfront behaviour, which was causing
`announce` requests from go-legs HTTP publishers to fail with `403`.
Allow all methods on cloudfront caching, because we need `GET` and `PUT`
to be allowed but they can't be configured explicitly. CloudFront only
supports `GET, HEAD` or` GET, HEAD, OPTIONS` or
`GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE` hence the exhaustive
allowed methods list.
Same is applied to `dev` while we are at it.
> Allow `put` via cloudfront sitting in front of `cid.contact`

- deploy/infrastructure/common/github_actions.tf
- deploy/infrastructure/dev/us-east-2/autoretrieve.tf
- deploy/infrastructure/dev/us-east-2/kms.tf
- deploy/infrastructure/dev/us-east-2/outputs.tf
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/README.md
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/flux-cd.yaml
Define dedicated KMS key to encrypt application level secrets for
autoretrieve.
Change `main` to `master` for autoretrieve, since that is the default
branch.
Remove temporarily granted access to autoretrieve fork now that access
to main repo is sorted out.
> Define dedicated KMS keys used to encrypt autoretrieve secrets

- deploy/manifests/base/storetheindex/config
Upgrade configuration format to the latest, consistent with the config
used in lotus infra deployment. The change is applied to the `base`
overlay which will update the config in both `dev` and `prod`.
See:
- https://github.com/filecoin-project/lotus-infra/blob/master/kubernetes/mainnet-us-east-1-eks/helm/ntwk-mainnet-storetheindex/filecoin/lotus-bundle/storetheindex-0.yaml
> Upgrade indexer config base layer

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/config
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
The dev instances are still running on 10GiB memory because the maximum
available on the worker node type is 16. It also uses a configuration
identical to prod, which means it would ingest everything prod does.
Here we whitelist only a selected number of providers to reduce load on
the `dev` instance since it is meant to be for development purposes.
This should shield it from failures that say prod instance goes through
due to excessive ingest load.
The memory given to the instances as well as the instance types are
upgraded to match production. Taint is set on the dev instance to use
r5b instance types just like prod. This will allow us to change the dev
config as we see fit to match the prod config or selectively ingest from
specific providers for debuging purposes without having to …
> Use larger instance types and override config in dev to limit providers

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/tenant/storetheindex/config
In order to understand the scalability of ingest from high-volume
providers, only whitelist a specific high-volume provider so that we
learn whether a dedicated indexer instance can work through long chanins
of advertisement.
Increase r5b minimum instance count to assure that there is one in each
AZ otherwise the pods will fail to schedule since PVCs might be in AZs
that is different from the EC2 worker instance AZ.
> Only whitelist ingestion from a specific provider in `dev` for testing

- config/config.go
- config/ingest.go
- config/policy.go
- config/ratelimit.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/registry/policy/policy.go
- internal/registry/policy/policy_test.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/finder/test/test.go
- server/ingest/handler/ingest_handler.go
- server/ingest/http/handler_test.go
- server/ingest/test/test.go
The indexer needs the rate limit rate, and the peers that rate limiting is applied, to be configurable.  See: #486 
- Create new RateLimit config in `config.Ingest.RateLimit`
- Remove old rate limit config items in `config.Discovery.Policy`
- Add `BlocksPerSecond` to rate limit config
- Update config file version
- Add code in ingester to create late limiter for go-legs Subscriber
- Add unit tests to check that limiter is created with values according to config
> Configure rate limit

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
In order to accommodate resource limits for `autoretrieve` running in
`dev` environment, add new workers that can accommodate 32Gi memory for
pods.
Used `r5a.2xlarge` because it is the cheapest memory optimised instance
type with x86_64 arch needed by `autoretrieve`.
Relates to: https://github.com/application-research/autoretrieve/pull/61
> Add memory optimized `r5a.2xlarge` workers to `dev`

- e2e_test.go
- internal/ingest/ingest_test.go
- internal/ingest/synchandler.go
- internal/registry/registry_test.go
In `TestEndToEndWithReferenceProvider` reset `Stdin` and `Stderr` for
the command before running it in a combined output. Otherwise,
`CombinedOutput` will return an error. Increase total E2E test timeout
to 2 minutes, since it seems to intermittently fail on MacOS.
In `TestMultiplePublishers`, assert indices from each test publisher are
eventually indexed since the background ad processing might not have
finished when the sync returns. Assert Synced CID is equal to the
expected head before checking reference to the latest synced.
In `TestPollProvider` registry tests close the registry to avoid failure
in Windows when tests attempt to remove temporary files that otherwise
will be in use and cannot be deleted.
> Fix intermittent test failures

- config/ingest.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/ingest/seg_sync_test.go
Syncing excessively long advertisement or entry chunk chains from an
HTTP publisher results in out of memory error. This is caused by an
internal state maintained by IPLD during `traversal.Progress`, where the
traversal path is updated in memory until the traversal completes.
To avoid memory issues as a result of syncing long chains in one go
use the segmented sync mechanism introduced in go-legs, where a chain is
synced in segments with a configurable segment depth limit. The sync
process is then repeated until the desired total depth limit is
traversed or we reach the end of traversal. At each segmented sync
cycle, depending on the kind of node being synced, the latest synced
node is decoded, and based on its type (either `Advertisement` or
`EntryChunk`) the next segment link is …
> Sync ads and entries in configurable segments

- go.mod
- go.sum
Use the latest released version of go-legs that has segmented sync
feature.
> Use concrete `go-legs` version with segmented sync

- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
Fix an issue where the tail of a chain, either ad or entry chunk is
resynced. Block hook was never calling the actions if the next link was
nil, meaning we have reached the end of the chain.
As a result the CID before last was being left as the CID to try in the
next segmented sync and therefore the segmented sync cycle continued.
The fix explicitly sets the next CID to `Undef` when we have reached the
end of a chain which then signals that segmented sync cycle must stop.
Upgrade to the latest go-legs.
> Fix bug where tail of chain is synced twice

- internal/ingest/ingest.go
`retriablehttp` log every request by default in DEBUG level. Disable it
to reduce noise in logs since HTTP failures are what we want to see in
logs, not access logs and that is already being logged by go-legs
loggers.
> Reduce verbose logging of HTTP sync requests

- config/ingest.go
- internal/ingest/ingest.go
The default client used by `retryablehttp` is a wrapper HTTP client
called `cleanhttp` which comes with warnings about how it could leak
file descriptors in specific situations.
Revert back to `http.Client`, same as the default in go-legs, but
keep the wrapped retry logic.
Relates to: #523
> Use `http.Client` instead of `cleanhttp` in `retryablehttp`

- go.mod
- go.sum
Upgrade to the latest version of go-legs that learns HTTP publisher
addresses from announce requests. This fixes an issue where ingester
could end up using the wrong transport when syncing ad or entries.
> Upgrade go-legs to fix HTTP publisher address issue

- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
The worker nodes dedicated to indexer nodes in `dev` have 4 compute
capacity. Around 500 millicpu is spent on daemon sets and other cluster
related pods.
Up the CPU to 3.5 in dev first to make sure the new CPU demand is
scheduled as expected before rolling the same changes on prod.
> Increase CPU limit in `dev` to `3.5`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
The CPU usage in `prod` is at limit and the advertisement processing
is relatively slow. The worker nodes running the `prod` instances have
4 compute capacity and we can increase the CPU limit for indexers to
3.5, leaving 0.5 for the cluster related pods.
The `dev` environment is using the same worker type as prod with the
same cluster set up. Earlier commits confirmed that 3.5 CPU was
successfully scheduled by the K8S cluster.
Relates to: https://github.com/filecoin-project/storetheindex/issues/523
> Increase CPU resources in `prod` to `3.5`

- go.mod
- go.sum
Depend on storethehash that has:
- Recovery logic for bad keys.
- Fix for `freelist.Close` and`freelist.Flush` not writing buffered data to file.
- Error messages that give more information about problems reading data.
> Use sth with bad key recovery

- internal/ingest/ingest_test.go
Add a test that asserts the entries ingestion pipeline does not deadlock
when an announce is handled just after the ad chain sync has finished
and just before its entries are processed.
Relates to:
- https://github.com/filecoin-project/storetheindex/commit/cf70a62e2ece09f18021fa940cb0c9fe2238d045#r75038778
> Assert ongoing announce does not deadlock ingestion

- README.md
- api/v0/admin/client/http/client.go
- command/admin.go
- command/daemon.go
- command/flags.go
- doc/config.md
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/admin/http/handler.go
- server/admin/http/server.go
Use the admin sub-command `reload-config`, or send the daemon process a SIGHUP signal, to reload policy and rate limit settings from the config file.
- New command `admin reload-config` to reload parts of config.
- Handles SIGHUP to signal daemon to reload portions of config.
Manual testing for success and failure
> Reload policy and rate limit settings without restarting daemon

- .github/workflows/cd.yml
The CI job that creates PRs from the `cd/*` branches is triggered on
push. If a push is made to those branches where the is no commit from
the main branch to create a PR the build will fail.
Check the error message for a case where the CD branch is pushed to but
has no commits ahead of the main branch and gracefully terminate the
build.
> Do not create a PR in CD branches if there is no commit

- internal/ingest/invalid_mh_ingest_test.go
- internal/ingest/linksystem.go
- test/typehelpers/typehelpers.go
Test that invalid multihashes are ignored.
**Only merge this if we _do not want_ to allow invalid multihashes**. Compare with #554
> Ignore invalid multihashes

- go.mod
- go.sum
Use the newest Reframe library, which moves the query from the URL to the HTTP body.
Addresses https://github.com/ipfs/go-delegated-routing/issues/22
> update dependecy on delegated routing

- command/daemon.go
- command/flags.go
- config/config.go
- config/init.go
- config/logging.go
Log levels are now configurable in the config file. An overall log level setting is configurable, as well as the settings for any logger that should not have the same level as the overall setting. These config settings are reloaded when the config file is reloaded at runtime.
If there is no logging configuration, the default log level is set to "info" and the loggers "basichost", "bootstrap", "dt_graphsync", "dt-impl", and "graphsync" are set to level "warn".
> Log levels are configurable in config file and reloadable

- command/daemon.go
- command/flags.go
- config/indexer.go
- config/ingest.go
- doc/config.md
Some additional time settings were moved into the config file in order to change them without a software update. The `ShutdownTimeout` may need to be adjusted as it can take longer to shutdown an indexer if it is very busy.
Automatic config reload is now enabled by default.  There really is no reason to have this disabled, and it is much worse to accidentally not enable it should it become necessary to reload config items without a restart.
Fixed a problem configuring indexer core cache to be disabled.  Previously, setting the cache size to 0 was supposed to disable the cache, but instead only configured the default.  Now, `-1` is used to disable the cache, and the meaning of value 0 (use default) is consistent with all other `Indexer` config items.
- Move `CheckConfigInterval` into …
> More config items

- api/v0/admin/client/http/client.go
- command/admin.go
- command/flags.go
- e2e_test.go
- internal/registry/registry.go
- server/admin/http/handler.go
- server/admin/http/server.go
The "admin import-providers" subcommand imports providers from another indexer. The other indexer is specified using the `--from` flag and specifying the host:port of the other indexer.
After importing publishers, sync with them immediately.
> Add command to import providers from another indexer

- go.mod
- go.sum
Now that there is a tagged release of the latest IPLD upgrade to it
instead of depending on a commit.
> Upgrade to IPLD `0.17.0`

- config/ingest.go
- doc/config.md
- go.mod
- go.sum
- internal/ingest/ingest.go
The latest go-legs has the ability to re-publish direct announce messages over pubsub. This PR gives the indexer the ability to be configured to enable/disable this feature.
Fixes issue #582
> Add ability to configure re-publishing direct announce messages

- deploy/infrastructure/common/ecr.tf
- deploy/infrastructure/common/github_actions.tf
- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/infrastructure/dev/us-east-2/index-provider.tf
- deploy/infrastructure/dev/us-east-2/kms.tf
- deploy/infrastructure/dev/us-east-2/outputs.tf
- deploy/manifests/dev/us-east-2/cluster/index-provider/.sops.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/flux-cd.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/flux-rbac.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/github-auth.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/index-provider/namespace.yaml
- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
* Create a KMS key to encrypt index-provider application secrets.
* Create an ECR repository to which containers will be published.
* Authorize GitHub actions to accept ECR publication from index-provider
repo.
* Create a namespace and set up Flux CD pipeline for the index-provider.
Relates to:
- https://github.com/filecoin-project/index-provider/issues/246
> Onboard `index-provider` as a tenant of `dev` cluster

- deploy/manifests/dev/us-east-2/cluster/autoretrieve/flux-cd.yaml
In updating the auto retrieve flux config, I think I messed up the ImageUpdateAutomation task, as the new repo uses main.
see this line in flux logs:
```
2022-07-05T19:18:06.234Z error ImageUpdateAutomation/autoretrieve.autoretrieve - Reconciler error unable to clone 'https://github.com/filecoin-project/autoretrieve-deploy.git': reference 'refs/remotes/origin/master' not found
```
change branch to main
> fix(autoretrieve): fix flux branch

- command/daemon.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/finder/handler/finder_handler.go
- server/finder/http/protocol_test.go
- server/finder/libp2p/protocol_test.go
- server/finder/test/test.go
- server/ingest/http/handler_test.go
- server/ingest/test/test.go
Providers are currently listed at `/providers` even when not live
After polling has started and still unresponsive after at least one poll attempt, exclude provider from find responses and from `/providers` in both list and get responses (#594)
When polling has stopped with no responses remove the provider data from the indexer. (#595)
- Remove provider from registry's list of providers, in memory and datastore.
- Remove latest sync data (for provider's publisher) from ingester datastore.
- Remove handler from legs subscriber.
- Remove provider content from indexer core. Delete by contextID when removed provider seen in query result.
Fixes #594 
Fixes #595
> don't return providers after polling has stopped

- internal/httpserver/util.go
- server/finder/http/server.go
The finder server responses did not include the headers despite them
being set as part of request handling. Instead of setting headers in
handlers, which may not get applied depending on gorilla mux router
configuration, use a "middleware" provided by the gorilla mux framework
to set allowed methods extracted from the router as well as allow
origin all.
For CORS to function correctly, the endpoints also need to handle
`OPTIONS` method gracefully. This is also added, where the handling is
terminated after the headers are written.
Relates to:
- https://github.com/filecoin-project/storetheindex/issues/612
> Fix response headers and CORS OPTIONS support via middleware

- internal/httpserver/util.go
- server/finder/http/handler_test.go
- server/finder/http/server.go
Fix an issue where the set `Content-Type` by `WriteJsonResponse` handler
had no impact since HTTP status was being set before the headers.
Simplify the CORS handing in `mux` router and add tests that assert the
CORS handling as well as expected content type for every finder
endpoint.
Relates to:
- #612
> Fix handler content type and add CORS tests

- server/finder/http/handler_test.go
- server/finder/http/server.go
Add test that asserts it returns rendered content.
> Fix go template buffer issue for landing page

- internal/registry/registry.go
- internal/registry/registry_test.go
A panic is caused in registry when the publisher is changed for a known
provider with empty addrs.  An `AddrInfo` can have empty addresses. This
can happen when getting `AddrInfo` from the peerstore of a host that
does not know about a given peer ID.  Therefore, check that addresses
are not empty before attempting full registration.
Add logging to identify the provider and publisher for which this
scenario occurs. This is to help further investigate if there is
anything we might be missing in the context of legs peerstore update
(both the HTTP peerstore and libp2p peerstore).
> Check `AddrInfo` has addresses before use

- internal/registry/registry.go
- internal/registry/registry_test.go
Handle registering a new publisher for a provider, when no new provider addresses are given. Handle the case where the publisher is different from the publisher, and where the provider is the same as the publisher.
This also fixes another issue where the new provider addresses, if given, need to be applied before setting an empty publisher address to that of the provider with the same ID.
> Registration of new publisher with no addresses

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-config.yaml
Increase worker count in `dev` to investigate slow ingestion time for
ads.
> Increase worker count in dev from 10 to 20

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexer-config.yaml
Increase worker count in `prod` to investigate slow ingestion time for
ads.
> Increase worker count in prod from 10 to 20

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexer-config.yaml
Almost all the ads sent by nft.storage, one of the high-volume
providers, have just over 6K multihashes. Increase the batch size to
reduce IO operations when advertisements are ingested.
> Double the storage batch size to fit 6K multihash count

- config/discovery.go
- deploy/manifests/base/storetheindex/indexer-config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexer-config.yaml
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/ingest/handler/ingest_handler.go
Remove any private, loopback, and unspecified IP addresses from provider and publisher addresses when they are written to the registry.
> Filter non-routable IP addresses

- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
This is to avoid having nodes deployed on node types since `r5b` is
specifically optimised for hig IOPS with `io2` volume kind.
> Set node affinity for sti `dev` instance to nodes of type `r5b.xlarge`

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/indexer-config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/patch-indexer.yaml
The sth bit size is changed to 30 which should comfortably fit into the
120Gi memory available to the instances. Since there is plenty of spare
CPU available on `r5b.4xl` machines, the CPU available to the instances
is also increased to 10.
Various missed out namespace updated are alos fixed.
> Configure debug instance to run on larger machines

- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/indexer-config.yaml
kustmoize fails to match config since namespace does not match. The
namespace is later on overridden to the right one by kustomization.
> Fix kustomize build issue in sti debug

- internal/registry/registry.go
List of multiaddrs in `peer.addrinfo` may be empty. Check length before
use to avoid panic.
> Check addrs for length before use

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Instantiate `r5b.4xl` worker nodes in prod with per AZ ASG to provide
the ability to control scaling better since we run only 2 indexer nodes.
> Stand up `r5b.4xl` worker nodes in `prod` cluster

- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
Now that there are `r5b.4xl` worker nodes in the cluster, set affinity
for `prod` nodes to them and increase the memory and CPU resources to
utilise what the worker nodes offer.
> Run prod instances explicitly on `r5b.4xl` node and increase resources

- go.mod
- go.sum
- internal/registry/registry.go
- internal/registry/registry_test.go
When IP filtering is enabled and `PublisherAddr` is `null`, a slice is
constructed with the `PublisherAddr` which is then used for filtering.
We will then end up with an addr slice that has a single
`nil` element. Check `PublisherAddr` is not nil before any IP filtering.
Upgrade go-legs to fix panic during IP filtering on `nil` addrs.
> Fix `null` publisher addr causing addr slice with `nil` address

- deploy/infrastructure/prod/us-east-2/eks.tf
Now that both production nodes are running on `r5b.4xl` instances,
destroy the older unused worker group.
> Destroy `r5b.xl` worker group on `prod`

- deploy/manifests/base/storetheindex-single/config.json
- deploy/manifests/base/storetheindex-single/deployment.yaml
- deploy/manifests/base/storetheindex-single/identity.key
- deploy/manifests/base/storetheindex-single/kustomization.yaml
- deploy/manifests/base/storetheindex-single/labels.yaml
- deploy/manifests/base/storetheindex-single/pvc.yaml
- deploy/manifests/base/storetheindex-single/service.yaml
- deploy/manifests/dev/us-east-2/cluster/kube-system/io2-storage-class.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/pvc.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/pvc.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/pdb.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
The current deployment of storetheindex uses a statefulset with replica
count of 2. This makes up a simpler deployment mechanics but does not
allow the config or version of the container run by each node to be
different from one another. This makes debugging or trial of a specific
solution require an "all or nothing" change to the environment.
A new kustomization overlay is defined, which is explicitly designed to
run a single instance of storetheindex. The overlay also separates the
PVC definitions which makes expansion of volumes easier, and removes the
need for manual statefulset re-creation to work around volume claims
immutability.
Two new instances based on the new singel-node overlay are added to the
dev environment under the human readable names of `arvo` and `mya`. The
rationale …
> Deploy individually configurable sti nodes in `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
The `images` kustomization transform does not support image
transformation filtering by `kind`. Since the image name across both
single-instances are the same, the replica is changed to 2 across the
deployments and statefulsets.
Set the replica via patch for finer control over the resource it is
applied to.
> Configure replica count in `dev` via patch for finer control

- deploy/manifests/prod/us-east-2/cluster/cluster-autoscaler/kustomization.yaml
Now that worker nodes are configured to scale per AZ, re-enable the
cluster auto-scaler.
Fixes #440, #494
> Re-enable cluster auto-scaler in `prod`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/pdb.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/pod-monitor.yaml
Set up pod monitor to select pods with label `indexer-single`, used by
the single-node indexers.
> Configure prometheus monitoring for single-node indexers

- deploy/manifests/prod/us-east-2/cluster/kube-system/io2-storage-class.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/pdb.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/identity.key.encrypted
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/identity.key.encrypted
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
Deploy two new individually configurable and publicly addressable
instances of storetheindex in `prod` with 30-bit sth bucket size running
on `r5b.4xl` workers.
Define a new storage class of type `io2` with 5 IOPS per GiB and use it
as the strorage class for the new nodes.
Both of the nodes are configured to run the head of `main` branch. Note
that CD pipeline is not enabled for the nodes, and change of version
running requires explicit PR to update the image tag in each relevant
node kustomization.
> Deploy two individually configurable sti nodes in `prod`

- deploy/manifests/dev/us-east-2/cluster/monitoring/prometheus-patch.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/prometheus-patch.yaml
Clusters run two replicas of prometheus remote writers for
high-availability. By default all metrics are labeled by the collector
instance, with label name `prometheus_replica`. This results in doubling
the metric cardinality, which comes across as duplicate metrics in
grafana. Set replica external label name to empty string to drop this
labeling altogether and avoid duplicate metrics.
While at it, remove not-so-useful K8S-specific metrics with high
cardinality to reduce load and PL Grafana cost.
Fixes https://github.com/filecoin-project/storetheindex/issues/522
> Do not label metrics by replica and drop high-cardinality metrics

- command/daemon.go
- config/indexer.go
- go.mod
- go.sum
- internal/ingest/ingest_test.go
- server/finder/test/test.go
- server/ingest/test/test.go
Upgrade to the latest `go-indexer-core` which introduces binary
serialization format for values that offers much better performance in
comparison with JSON.
Add configuration values in storetheindex so that the valuestore
serialization format can be configured, with default of JSON for
backward-compatibility.
> Introduce binary format valustore serialization

- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/indexer-config.yaml
Only whitelist the peer ID of nft.storage on dev debug instance to learn
about ingest contention on a node with 30-bit bucket and 3 IOPS per GiB,
the same number of IOPS used by prod instances that serve `cid.contact`.
> Isolate ingestion on `dev/debug` instance to nft.storage

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/identity.key.encrypted
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/pvc.yaml
Deploy a fresh instance, named `vega`, in `prod` with identical config
as `xabi` except only has nft.storage whitelisted. This is to gain a new
data point on binary encoding plus zero concurrent ingest contention.
Add README with tables to make it easier to see config across instances.
> Deploy prod instance with `binary` encoding dedicated to nft.storage

- deploy/manifests/base/indexstar/deployment.yaml
- deploy/manifests/base/indexstar/kustomization.yaml
- deploy/manifests/base/indexstar/pdb.yaml
- deploy/manifests/base/indexstar/service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Define the base K8S manifests for `indexstar` as a stateless deployment
and run an instance of it on `prod` cluster proxying from every running
instance of storetheindex across both dev and prod environments.
Run the `indexstar` in the same namespace as `storetheindex` since it is
to eventually become an umbrella service which serves finds on
cid.contact.
> Define base manifests for `indexstar` and deploy to `prod`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
Increase the PVC size as we are near 90% utilisation at the moment. Note
that the statefulset needs to be manually re-created when size is
modified. We won't need to do this once the single instances catch up.
Since they use manifest that define a separate PVC resource. For now we
do the manual dance of orphaning the pods and recreating the statefulset
to apply the size increase.
> Increase PVC size in `prod` statefulset to 20Ti

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy the latest indexstar that supports other find endpoints as well
as `/multihash`.
> Deploy the latest indexstar with extra find endpoints

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
To avoid potential DAG-JSON decoding issues when multiple find provider
results are returned from a server run the latest indexstar with
upgraded reframe dependency.
> Upgrade to latest indexstar with upgraded reframe dependency

- internal/registry/policy/policy.go
- internal/registry/policy/policy_test.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/finder/handler/finder_handler.go
- server/ingest/http/handler_test.go
- server/ingest/test/test.go
When a provider is not allowed by policy, the indexer will not poll that provider and will remove it and delete its contents. This PR changes the behavior to retain blocked providers without removing them or their contents. The blocked providers will still not appear in `find` or  `provider` responses.  This makes it safe to manipulate allow/block lists without the concern of deleting content.
> Do not delist blocked providers

- go.mod
- go.sum
Upgrade to the latest go indexer code which includes sth read lock fix.
> Upgrade indexer core to roll out gc read lock fix

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/config.json
The previous value of 5 minutes seems to be too low as the container
did not shut down gracefully within the configured time limit. Double
it to see if that suffices for a graceful shutdown.
> Increase termination grace period to 10 minutes in `tara`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/kustomization.yaml
Deploy the head of main to `dev` `indexer-0` and `indexer-1`, plus
`prod` `romi` and `xabi`. It is already successfully deployed to `dev`
`mya` and prod `tara`.
> Deploy head of `main` to `dev` and two other `prod` instances

- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
- scripts/peer_id_from_priv_key.go
Add an script that accepts marshalled private key as stdin and prints
the public key associated to that identity.
Comment peer ID of dev and prod instances in code for convenience.
> Add script to get peer ID from identity file

- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/patch-indexer.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/kustomization.yaml
Deploy the latest changes to check for minimum mh len to dev and half
of prod single nodes.
> Deploy min mh length change to dev and half of prod single nodes

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/kustomization.yaml
Roll out change to GC mechanism optionally freeing files in `dev` all
nodes, and `prod` single-deployment nodes. Preliminary testing showed
that changes to the locking mechanism significantly reduces spike in
latency when the GC runs. To further study the long-term impact of the
changes, the rollout here sets the option to `true` in some nodes and
`false` in others.
> Roll out GC free files option to dev and prod single instances

- command/daemon.go
- config/indexer.go
- server/admin/http/server.go
- server/finder/http/protocol_test.go
- server/finder/http/server.go
- server/ingest/http/server.go
Storetheindex at runtime can have 2 shutdown timeouts: one from K8S,
i.e. the termination grace period, and one at application level. The two
can conflict each other. So on deployment to K8S one has to make sure
the value of latter is always higher than the value of former.
To avoid having to make sure the value is higher, simply interpret zero
as no timeout. That way, the user can disable shutdown timeout fully and
avoid conflicting config depending on runtime environment.
Change the default shutdown timeout to no-timeout.
> Interpret shutdown timeout of zero as no limit

- command/daemon.go
- config/indexer.go
- go.mod
- go.sum
- Add `Config.Indexer.STHBurstRate`
- Add `Config.Indexer.STHSyncInterval`
- Remove `Config.Indexer.GCScanFree`
The `GCScanFree` option is no longer needed since whether or not it is used is now automatically determined by a simple heuristic.
- Update to STH with scan free heuristic
When writing to the indexer-core, an exclusive lock was serializing much of the call to Put.  The locking has been changed to make it much more granular and should allow for better write concurrency.
When querying by a multihash that was deleted when its provider was delete, the indexer tries to opportunistically delete the multihash when it determines the provider is gone. Updating the value key list to remove the value-key for a provider's value can result in writing the same value that was already updated …
> Fix error writing existing value; add more STH config

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/config.json
Investigate the impact of increasing sync interval on `vega` by
increasing it from the default of 1 second to 3 seconds.
> Increase STH sync interval on `vega` to 3 seconds

- command/daemon.go
- config/indexer.go
- config/ingest.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- server/finder/test/test.go
- server/ingest/test/test.go
When configured with `Ingest.EntryPutConcurrency` > 1, concurrently/asynchronously ingest each `Put` and fetch and ingest the next chunk without waiting for the current Put to complete. Default is 16.
When configured with `Indexer.CorePutConcurrency` > 1, within each call to the core's `Put`, write each multihash-to-value mapping concurrently. Default is 64.
> Concurrently ingest core multihashes and entry chunks

- command/daemon.go
- config/ingest.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
Handle entry chunks asynchronously, unless `Config.Ingest.SyncWriteEntries` is true. The asynchronous behavior allows the indexer to fetch the next entry chunk without having to wait for the current one to complete processing. An asynchronous goroutine (one per worker) processes the entry chunks while they are being queued.
Previously, the `EntryPutConcurrency` setting configured a pool of goroutines, shared by all workers, to handle processing entry chunks. A problem with this was that one provider/worker could submit many entry chunks to his pool and keep all the goroutines busy for itself, starving the other provider/workers of the ability to process entry chunks.
With this PR, each provider/worker has its own async goroutine and can asynchronously process entry chunks without starving …
> Asynchronously handle entry chunks by default

- command/daemon.go
- config/ingest.go
- doc/config.md
- go.mod
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
The number of entry chunks queued for async processing is limited to 1. This prevents queuing large chains of entry chunks awaiting processing and exhausting memory.
Other changes:
- Daemon logs config reload
- Documentation updates
> Limit entry chunks queued for async processing

- command/daemon.go
- config/ingest.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
Configure the number of additional threads per publisher/worker to asynchronously process each incoming entry chunk. This is configured with the run-time reloadable configuration setting `Ingest.EntriesChunkConcurrency`.
The ingest workers do not compete with each other for a global pool of goroutines, since they each get this number of additional goroutines, so one provider will not starve others.
> Configurable entries chunk concurrency

- command/daemon.go
- config/ingest.go
- doc/config.md
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
Do not start and stop entries chunk worker goroutines with each ad processed. Instead, if enabled, use a global pool that is at least as big as the worker pool size. The worker goroutines compete fairly to use the entries chunk workers, so one will not starve others.
The config setting `Ingest.EntriesChunkConcurrency` controls the number of entries chunk workers and is runtime reloadable. A value of 0 (the default) sets this to the same as the ingest worker pool size. A value of -1 disables it and makes entries chunk processing synchronous.
> Keep entries chunk worker goroutines running

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
To route find requests to `dido` add it to the list of nodes in
indexstar.
While at it point indexstar to individual idnexer-0 and indexer-1 nodes
to get better repeatability over aggregated result, since otherwise the
requests from indexstar might land on only one of the two at random.
> Add `dido` to indexstart and point to individual indexer instances

- go.mod
- go.sum
A panic was observed on `dido` coming from internals of go-indexer-core,
with error: `segmentation violation code=0x1 `.
Upgrade `golang.org/x/sys` as suggested online to avoid potential future
panics.
[Logs](https://protocollabs.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%5Cn%7Benvironment%3D%5C%22prod%5C%22,%20namespace%3D%5C%22storetheindex%5C%22,%20pod_name%3D~%5C%22%28dido%29.%2B%5C%22%7D%20%7C~%20%5C%22panic%5C%22%5Cn%5Cn%5Cn%5Cn%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221662468518043%22,%22to%22:%221662468708332%22%7D%7D).
> Upgrade `golang.org/x/sys` dependency potentially related to panic

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
Disable indexer-core cache on `dido` until the following issue is
resolved:
- https://github.com/filecoin-project/go-indexer-core/issues/80
> Disable indexer-core cache on `dido`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
Change cachesize to `-1` to actually disable it. `0`  will result in
revert to default value.
> Disable indexer-core cache on `dido` by setting it to -1

- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Also remove the node groups that no longer exist.
> Fix typo in aws-auth permissions to the new node group

- api/v0/httpclient/client.go
- api/v0/httpclient/options.go
There are options on the http.Client that we don't expose currently when making a finder client,
for example, configuration of `MaxConnsPerHost` and `MaxIdleConnsPerHost` on the RoundTripper are important for a high volume connection back to a single server.
This change adds an option to allow creation of clients over an already configured http.Client.
> Add option for specifying existing client

- command/daemon.go
- config/ingest.go
- doc/config.md
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
There is no performance benefit to having a pool of goroutines over having one asynchronous goroutine per publisher/worker to asynchronously process and entries chunks. Having one additional goroutine provides a simpler implementation that uses less memory. It is also simpler to configure since the choice is to enable or disable the asynchronous behavior.
The default behavior is asynchronous.
Make the configuration setting `Indexer.CorePutConcurrency` run-time reloadable.
> Write entries chunks synchronously or asynchronously

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Observing high status 0 on hydra metrics. Reverting for now to investigate.
Reverts filecoin-project/storetheindex#777
> Revert "Deploy the latest to indexstar to cap worst-case wait time"

- go.mod
- go.sum
This is to include a fix in blockhook being called even when http traversal fails.
> Upgrade go-legs dependency

- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/kustomization.yaml
This serves as another performance datapoint and provides a place to make more wild adjustments to the configuration.
> Deploy latest to debug nodes

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/config.json
this provider is important for autoretrieve testing, and seems to have fallen off of prod pair
> Update vega policy

- go.mod
- go.sum
- server/finder/http/protocol_test.go
- server/reframe/reframe.go
Upgrade to the latest delegated routing that uses cachable GET HTTP method.
> Upgrade to latest delegated routing

- go.mod
- go.sum
Upgrade to the latest `go-legs` to check digest of blocks synced from HTTP publishers.
> Upgrade dependency to `go-legs` for httpsync fixes

- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
Increase the PVC size to 40 TiB from current 20 TiB as we are near 90% utilisation at the moment.
> Increase PVC size in prod statefulset to 40Ti

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/kustomization.yaml
Deploy the latest upgrade to go-legs on pebble backed nodes and reduce sync intervals on dido since announcements are not flowing on that node.
> Deploy latest upgrade to legs on pebble backed nodes

- deploy/infrastructure/common/ecr.tf
- deploy/infrastructure/common/github_actions.tf
- internal/ingest/ingest_test.go
This PR adds [ipfs-index-provider](https://github.com/ipfs-shipyard/ipfs-index-provider) to the terraform configuration. fixes  #828
> Added ipfs-index-provider to terraform configs

- deploy/manifests/dev/us-east-2/tenant/storetheindex-debug/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/kustomization.yaml
Has corrupted freelist fix and is rebased on latest sti with go-legs v0.4.14
> Deploy primary gc testing onto dev debug

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/pvc.yaml
Address disk utilisation alert on `romi`.
> Expand PVC in `romi` since it is over 80% utilised

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
Use peering to get republished HTTP announce messages, instead of auto-syncing every 5 minutes.
> Set peering for oden; no custom auto-sync

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
Investigate high queue times on `dido` by increasing worker count.
While at it, set the rate limit to zero to make it clear that it is disabled.
> Increase worker count on `dido`

- deploy/manifests/prod/us-east-2/cluster/ingress-nginx/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/ingress-nginx/patch.yaml
- deploy/manifests/prod/us-east-2/cluster/ingress-nginx/pod-monitor.yaml
Export prometheus monitoring port on ngnix pods and write metrics out to PL grafana.
Relates to #786
> Enable prometheus metric collection from nginx ingress

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/metrics/server.go
Report metric for average nanoseconds to store a multihash. This is the average over all the multihashes stored for the last ad processed.
Also, log a message that says how long the ad took to ingest and the count of multihashes that were ingested for that ad. Example:
```
2022-09-27T08:59:15.364-0700    INFO    indexer/ingest  ingest/linksystem.go:152        Finished syncing advertisement  {"publisher": "12D3KooWKRJVaDiWcwAvvPNbzWPH8D49qzV5ExxNAGpsdRsABLmr", "adCid": "baguqeeraeigva2nffpv4xymg7x7sssfklenb4kuoz44q4ls5cn6nt66rjlhq", "contextID": "AXESIEHjf2X4P3ruFlU8HpSIR2rH3/qx2x9nALdjIhyI3oOL", "provider": "12D3KooWKRJVaDiWcwAvvPNbzWPH8D49qzV5ExxNAGpsdRsABLmr", "entriesKind": "EntryChunk", "elapsed": "2.31674075s", "multihashes": 25481}
```
- Cleanup some log messages
- Log elapsed time …
> Record time to store multihashes

- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
This checks that the metadata and context ID is within the allowed limit, and if not causes the ad sync to fail. This was not done previously and there is evidence that some oversized data was ingested on some indexers.
The sync is ended with an error, instead of skipping the advertisement, to limit the number of possibly huge unusable ads that are downloaded for ingestion.
Verification of the advertisement metadata length and context ID length is added to the advertisement verification that is done in the linksystem `StorageWriteOpener`
A new test checks that an advertisement with too large of metadata does not get ingested.
> Validate advertisement

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
`rami` is currently going through an index file upgrade; exclude it from indexstar to avoid expensive timeouts until indexstar implements proper exclusion of unhealthy backends.
The indexstar CPU usage was hovering at 70%; increase the CPU resource to give it enough headroom at the face of request fluctuations. As a result, up the max worker count in relevant EKS nodegroup to allow scheduling of pods with higher CPU limit.
Reduce instance counts to 3 since most of the pods were mostly idle now that resource limit is elevated.
Enable compression for `/reframe` endpoint on CloudFront; unrelated to the timeout investigation. Added here since it was changed in the past and terraform update was missing.
Relates to #863
> Exclude `rami` from indexstar and adjust resources

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
There seem to be no announcements flowing while indexer-0 and indexer-1 are performing primary upgrade. Reduce poll interval in order to avoid `oden` falling behind due to lack of announcements.
Revisit when those nodes are back up.
Relates to:
- https://github.com/filecoin-project/storetheindex/pull/843#issuecomment-1262581983
> Restore small poll interval in `oden`

- README.md
- config/discovery.go
Describes the delisting policy in the README and the configuration options that control it. Additional godoc descriptions are also provided.
Fixes #127
> Document delisting policy

- internal/ingest/linksystem.go
IPLD `SkipMe` errors returned during traversal via GraphSync signal partial availability of blocks. We already skip over "content not found" errors that occur while fetching entries associated to an ad. Therefore, it makes sense to do the same on `SkipMe` errors. To summarise, this means their ingest of ads that their entries are not traversable will not be processed. Otherwise, ad ingest for a provider may halt indefinitely.
Fixes #866
> Handle IPLD `SkipMe` errors as content not found during ad ingest

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
The node is not ready and causing high lookup latency.
> Exclude `indexer-1` from indexstar backends

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
A panic occurs when comparing values returned by cache. Disable it on `oden` to avoid panic. Aside from that the cache is hardly used by the node.
See:
- https://github.com/filecoin-project/go-indexer-core/issues/80
> Disable indexer core cache on `oden` to avoid panic

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
The landing page at `cid.contact` was powered by `indexer-0` and `indexer-1`. Now that they are down it meant the landing page was returning 503.
`indexstar` includes logic to bounce off landing page requests to the first configured backend. Though not ideal this means the landing page will continue to operate as long as the list of backends in `indexstar` are maintained.
Note, this change means we cannot use `cid.contact` directly as a backend in indexstar; otherwise it will result in an infinite redirect.
> Point landing page to `indexstar`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/patch-indexer.yaml
Prod indexers 0 and 1 need more time to have a clean shutodown.
> Set termination grace period for prod indexers

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
With indexer-0 and indexer-1 back online, they should in included in the indexstar targets.
> Include indexer 0 and 1 in indexstar targets

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexer-config.yaml
#883 happened on indexer-1, so setting config to write entries synchronously until that is fixex.
> Write entries synchronously to avoid #883

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Because `xabi` is going through index file migration it is downgraded.
> Exclude `xabi` from indexstar to avoid high response latency

- command/daemon.go
- config/ingest.go
- doc/config.md
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
Do not support writing entries asynchronously as it adds complexity for little or no gain in performance.
When ingesting from a single source, asynchronously writing entries may have a small performance improvement. This is because the next entries chunk can be already loaded when the previous chunk is done being written to the value store. When ingesting from multiple sources, this does not matter since any gap between ingesting one entries chunk and the next is utilized by another worker writing data to the value store.
Since any indexer is generally ingesting from multiple sources, the added complexity of asynchronously ingesting entries chunks does not result in any advantage. When ingesting from multiple sources, avoiding the more complex asynchronous behavior appears to have a …
> Remove option to write entries synchronously

- go.mod
- go.sum
Upgrade to the latest go-indexer-core to roll out pebble merger fixes.
> Upgrade to the latest indexer-core

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexer-config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/arvo/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/mya/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexer-config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/config.json
Cleanup the config to reflect the fact that `WriteEntriesSynchronously` no longer exists.
> Remove redundant `WriteEntriesSynchronously` config value

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
High ingest worker count in dido makes no significant difference to the ingest throughput; revert it.
Relates to:
- #854
> Revert high ingest worker count in `dido` as it makes no difference

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/pvc.yaml
`tara` is on crashloopback and ran out of disk space while upgrading sth primary files.
See [alert](https://protocollabs.grafana.net/d/pPROWOD7z/providers?tab=alert&viewPanel=72&orgId=1).
> Expand `tara` PVC to 40 Ti

- command/daemon.go
- config/indexer.go
- go.mod
- go.sum
- internal/ingest/ingest_test.go
- server/finder/test/test.go
- server/ingest/test/test.go
The valuestore chooses the `BinaryValueCodec` or `BinaryWithJsonFallbackCodec` codec based on weather or not the valuestore is created new or already exists, respectively. The codec is no longer configurable in the confile.
> Valuestore codec is not configurable and always uses binary

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Exclude `dido` backend from indexstar while working on improving CPU footprint of f pebble merger. This is to offer a stable upstream find latency in indexstar.
> Exclude `dido` from indexstar while investigating merger CPU footprint

- deploy/infrastructure/dev/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/manifests/dev/us-east-2/tenant/storetheindex/ingress.yaml
Change the routing of requests in `dev` environment, such that all requests to `dev.cid.contact` go through CloudFront caching, and routed via indexstar internally. This matches the routing mechanism currently employed in `prod`.
As a result of changes, ingress to `indexer-0` and `indexer-1` is changed to point to `indexer.dev.cid.contact` instead.
Fixes #856
> Point `dev.cid.contact` to CloudFront backed by `indexstar`

- deploy/manifests/dev/us-east-2/cluster/ingress-nginx/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/ingress-nginx/patch.yaml
- deploy/manifests/dev/us-east-2/cluster/ingress-nginx/pod-monitor.yaml
- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
Enable nginx monitoring and metrics on `dev` so that we can measure upstream latency from ingress. This is already set up for `prod`.
> Enable nginx ingress metrics on `dev`

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
The node group primarily getting used by autoretrieve is configured to use all subnets. This means ASG can spin up new nodes in any AZ which may not match the AZ on which PV was originally created.
The work here creates a node group with AZ dedicated to the zone on which the autoretrieve PV is currently presenent, i.e. `us-east2a`, in order to avoid unschedulable pods caused by AZ mismatch between worker node and PV.
The minimum instance count in the existing ASG is decreased to zero in order to avoid running idle workers once the autoretrieve pod migrates to the newly set up node group.
> Define an EKS node group dedicated to us-east2a for autoretrieve

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Testing in `dev` seems fine though hard to be confident considering it receives very little traffic.
> Deploy latest indexstar to `prod` to roll out resilience improvements

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Exclude `indexer-0` and `1` from `indexstar` on prod until they are restarted. This is a measure to reduce the impact on upstream latency caused by #931.
> Exclude indexer 0 and 1 on prod from indexstar

- deploy/infrastructure/dev/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/cloudfront.tf
`indexstar` does not multiplex over `ingest/*` requests. As a result announce requests won't reach the backend unless sent to explicit instance names.
Configure cloudfront such that `ingest/*` requests are sent directly to backend nodes, more specifically `indexer-0` and `indexer-1`. Because, those nodes are configured to further propagate HTTP announce requests over gossipsub which are then picked up by other instances.
> Route `ingest/*` requests directly to backend nodes

- go.mod
- go.sum
Upgrade to the latest release of pebble backing store to take advantage of pooling.
> Upgrade to the latest go-indexer-core to use Pebble pooling

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Now that the latest is deployed on `dido` and `oden`, add them back to `indexstar` backends.
> Add `dido` and `oden` back to `indexstar`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
They were removed to reduce upstream latency caused #931. Now that the issue is resolved, add them back to indexstar.
> Add indexers `0` and `1` back to `indexstar` backends

- internal/ingest/ingest.go
A provider may be marked as inactive if its last contact time is not updated for 2x longer than a configured threshold. The last contact time was previously being updated only of there was some ads from a provider: an active provider that has not published any new ads for a while could get marked as inactive.
The changes here opportunistically marks a provider as seen: i.e. whenever sync from that provider doesn't return an error. If subscriber. Sync does not return an error it means there was some successful communication to either fetch data or get the head.
Relates to #953
> Mark provider as Seen when sync is successful

- config/discovery.go
- internal/registry/registry.go
- internal/registry/registry_test.go
Introduce a new config parameter `DeactivateAfter` to replace the hardcoded `2xretryAfter` duration after which a provider is deactivated.
Change the default behaviour to set `DeactivateAfter` to the same value as `PollStopAfter`. This effectively disables the inactive state feature for providers: i.e. providers will remain findable via query APIs until deleted when unseen after `PollStopAfter` has elapsed.
Fixes #953
> Keep providers in active state until deleted by default

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/pvc.yaml
> Expand `xabi` PVC to 40 Ti

- go.mod
- go.sum
See https://github.com/filecoin-project/go-legs/pull/167
> Update go-legs to v0.4.17 with announce cache

- command/daemon.go
- config/config.go
- config/finder.go
- config/init.go
- server/finder/http/options.go
Default values can be overridden programatically through the config function or by altering the Finder section of the config file.
Fixes #632
> Add config function to set max number of connections for http finder server

- command/daemon.go
- config/addresses.go
- config/finder.go
- doc/config.md
- server/finder/http/server.go
- Document finder config settings
- Move `Addresses.FinderWebpage` to `Finder.Webpage`
> Document finder config settings

- server/finder/test/test.go
- server/reframe/reframe.go
The reframe server implementation only returned providers that supported exactly one transport protocol in their metadata: `TransportBitswap`.
This implementation was added at the time where Provider record metadata did not support multiple transports. Later, when the feature was added in Metadata spec, the reframe server was not updated to reflect it.
The changes here fix the issue by checking if the metadata is prefixed with `TransportBitswap` codec and if so it will include the records in response. Check for prefix is sufficient here because, metadata bytes must be sorted by codec as stated by the network indexer protocol.
Fixes #977
> Include Bitswap providers with multiple transport in reframe response

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy fixes to #977 on indexstar so that bitswap poviders are returned correctly over reframe queries.
> Deploy #977 fixes to indexstar

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/kustomization.yaml
`tara` in `prod` environment ran out of space yesterday around 1400 UTC, and currently is not ingesting any data. The node also suffers from corrupt index files which means respnses to find queries from this node are slower than other nodes which ultimately contributes to higher upstream latency at the indexstar ingress.
Spin down `tara` to zero replicas and exclude it from indexstar. Once spun down and after some cool-off period of few days remove this node completely along with its PVC.
> Spin down `tara` node in `prod`

- deploy/manifests/dev/us-east-2/cluster/aws-ebs-csi-driver/kustomization.yaml
Upgrade to the latest CSI controller to take advantage of fixes and Snapshot support. Deploy first on `dev` only to test out any conflicts before changing the base overlay which will impact both dev and prod.
Relates to #891
> Upgrade to the latest CSI controller on dev

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/pvc.yaml
The node is at 100% utilisation, having grown around 50% over the last 7 days.
Potentially related to #826.
> Expand `vega` PVC to 40Ti

- deploy/manifests/base/aws-ebs-csi-driver/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/aws-ebs-csi-driver/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/external-snapshotter/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/volume-snapshot-class.yaml
- deploy/manifests/prod/us-east-2/cluster/kustomization.yaml
Upgrade to the latest CSI driver on `prod` now that it have been tested on `dev` and deploy external snapshotter on `prod` so that we can take snapshot of existing node's PVC and mount it as the state of new nodes. This then would reduce time spent on catching up as well as making testing on real data much easier.
Fixes #890
Fixes #891
> Upgrade CSI driver and install external snapshotter on `prod`

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/romi/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/tara/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/config.json
Now that `indexer-1` is retried, and `indexer-0` is on its way to be no longer, change the cloudfront routing to send all requests at `/ingest*` to `kepa`. That node has the whitelisted peer ID on Lotus Bootstrap nodes and is configured to propagate HTTP requests onto gossipsub network for other indexer nodes. To reflect this change the node peering configuration is also changed to connect to `kepa` instead of the old instances.
The changes here also include increasing the max ASG for a node group used to run indexer nodes just to have 1 node headroom, and adds missing taints to `kepa` deployment object missed in earlier PR.
The work also removes a duplicate domain entry in ACM subject alternative names to avoid redundant changes to the terraform state when it is applied, since AWS …
> Route HTTP announce requests to `kepa` for further propagation

- api/v0/finder/model/provider_info.go
- command/daemon.go
- command/providers.go
- config/indexer.go
- e2e_test.go
- internal/counter/index_counts.go
- internal/counter/index_counts_test.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/metrics/server.go
- internal/registry/registry.go
- server/finder/handler/finder_handler.go
- server/finder/http/handler.go
- server/finder/http/options.go
- server/finder/http/protocol_test.go
- server/finder/http/server.go
- server/finder/libp2p/handler.go
- server/finder/libp2p/protocol_test.go
- server/finder/libp2p/server.go
- server/finder/test/test.go
- server/ingest/http/handler_test.go
- server/ingest/test/test.go
- server/reframe/reframe.go
Keep track of the number of indexes stored for each provider. For each provider, store a map of contextID to number of associated multihashes. When that context ID is removed, remove the entry from the map.  Get the total number of multihashes for a provider by summing all the counts for their contextIDs. Get the total stored index count by summing all counts for all contextIDs for all providers.
Counts are cached in memory after the first time they are retrieved.
- New config value `Indexer.IndexCountTotalAddend `. This is a value that is added to the index count total, to account for uncounted indexes that have existed in the value store before provider index counts were tracked. This value is reloadable.
Follow-up PR can supply metric histogram showing relative index contributions from …
> Track per-provider index counts and total

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/kustomization.yaml
The fix to provider exclusion heuristic was not deploeyd on `oden`. As a result it seems to stop fetching from nft.storage and mark the provider as inactive.
Deploy the same vesion as `dido` on `oden`.
> Deploy fixes to provider exclusion on `oden`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/xabi/pvc.yaml
`xabi` has fully utilised its disk; expand it to 60Ti.
> Expand `xabi` PVC to `60`Ti

- .github/workflows/go-test-config.json
- .github/workflows/go-test.yml
Test out a configuration to skip 32-bit go test via JSON configuration.
Relates to https://github.com/protocol/.github/pull/412
> Test configuration to skip 32-bit tests in unified CI

- api/v0/ingest/schema/envelope.go
- api/v0/ingest/schema/envelope_test.go
- api/v0/ingest/schema/schema.ipldsch
- api/v0/ingest/schema/types.go
- api/v0/ingest/schema/types_test.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/finder/handler/finder_handler.go
- server/finder/http/protocol_test.go
- server/finder/libp2p/protocol_test.go
- server/finder/test/test.go
- server/finder/test/test_extended_providers.go
- server/ingest/handler/ingest_handler.go
- test/util/util.go
This PR adds implementation for extended providers. For more details refer to the spec [here](https://github.com/filecoin-project/storetheindex/pull/804/files).
This PR adds backward-compatible support on the indexer side only. There going to be a second part to it that will have user-facing changes in index-provider.
> Add Extended Providers implementation

- deploy/infrastructure/common/ecr.tf
- deploy/infrastructure/common/github_actions.tf
Create a new ECR repo to host `heyfil` images and grant access to GitHub
Actions to build and push images.
See: https://github.com/ipni/heyfil
> Create ECR repo for `heyfil` and grant access to build push images

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Add `kepa` to indexstar as an endpoint to query during find requests now that the node is up and running without issues for about a week.
> Add `kepa` to indexstar

- api/v0/finder/model/provider_info.go
- server/finder/handler/finder_handler.go
- server/finder/test/test.go
This PR adds `ExtendedProviders` to the results returned by the `provider` endpoint for both `libp2p` and `http`.
> Add ExtendedProviders to providers endpoints

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/dido-snapshot-content.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/pvc.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/patch-indexer.yaml
Replace `indexer-1` on `dev` environment with a new node called `ber` that uses the `dido` snapshot from `prod` as its initial state.
The replacing node uses the same identity as `indexer-1`, since it is whitelisted on lotus bootrstrap nodes and will receive relayed gossip. As a result, `mya` is configured to now pair with `ber` instead of `indexer-1`.
> Replace `indexer-1` on `dev` with a new node

- deploy/manifests/base/indexstar/kustomization.yaml
This was defined but not included in the `kustomization`.
> Add pod disruption budget to indexstar

- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/snapshots/ber-dido-vsc.yaml
- deploy/manifests/dev/us-east-2/cluster/snapshots/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/dido-snapshot.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/kustomization.yaml
Because inside the namespace the service account managing CD does not have permission to touch cluster-level objects.
> Move volume snapshot content to cluster-level CD

- deploy/manifests/dev/us-east-2/cluster/snapshots/cali-dido-vsc.yaml
- deploy/manifests/dev/us-east-2/cluster/snapshots/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/dido-snapshot.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/pvc.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/kustomization.yaml
The node cali also uses the dido snapshot as its initial state and replaces `indexer-0` but without reusing its identity. This provides us with total of 2 nodes in `dev` both backed by pebble in order to offer redundancy and facilitate testing of coordination over more than one node.
> Deploy a new node `cali` on dev

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/vega/kustomization.yaml
Deploy v5.0.0 to the rest of the prod cluster. 
Update to the [README](https://github.com/filecoin-project/storetheindex/tree/main/deploy/manifests/prod/us-east-2/tenant/storetheindex/instances) will be done in the follow up PR.
> Deploy v5.0.0 to the rest of the cluster

- api/v0/admin/client/http/client.go
- assigner/core/assigner.go
- assigner/server/server_test.go
- command/admin.go
- command/flags.go
- command/init.go
- config/discovery.go
- internal/registry/policy/policy.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/admin/http/handler.go
- server/admin/http/server.go
When the indexer is configured to work with an assigner service, the indexer persists assigned peers in the datastore.
Peers listed in `Discovery.Policy.Except`, in the configuration file, are included in the set of assigned peers. This allows an indexer to be pre-configured with assigned peers.
- Admin command `list-assigned` shows assigned peers configured to use assigner service
- The `/assigned/` admin endpoint gets assigned peers configured to use assigner service
- Admin `block` command can be used to administratively unassign a peer
- New init flag `use-assigner` to create configuration file with settings to use assigner service
- Test to check that assignment is persisted
> Save assignments from assigner service in datastore

- assigner/command/daemon.go
- assigner/config/config.go
This allows the assigner to be configured to peer with indexers, instead of having to peer individual indexers with the assigner node.
> Add peering to assigner service

- api/v0/ingest/schema/envelope_test.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- server/finder/handler/finder_handler.go
- server/finder/http/protocol_test.go
- server/finder/libp2p/protocol_test.go
- server/finder/test/test_extended_providers.go
- test/util/util.go
If metadata of the main provider's EP record is different from the one in the ad, then such records would be returned in the find resultset as separate entries. This feature is required if the the main provider would like to advertise some new endpoints for a different protocol.
> Use EP metadata for the main provider

- assigner/config/assignment.go
- assigner/core/assigner.go
- assigner/core/assigner_test.go
- assigner/server/server_test.go
Each indexer in the pool can have preset publisher ID assignments. This means that when a publisher ID is seen, that publisher is assigned to all indexers that have that ID as a preset assignment. Publishers with preset assignments are assigned to all preset indexers without regard to other existing assignments or to the replication value.
This PR also changes the `OnAssignment` notification to report the indexer number instead of the indexer's admin URL. Also, the `OnAssignment` notification will keep reporting assignments of the specified peer ID until no more assignments of that peer are needed, after which the channel is closed.
Fixes #1045
> Allow specification of preset publisher assignments

- config/finder.go
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
- doc/config.md
- server/finder/http/handler_test.go
- server/finder/http/options.go
`CNAME`s are unique across all GitHub Pages repos. The current one is in use by repo under `willscott` and changing it requires admin access to the repo.
For faster turnaround, switch this in code. This also avoids breaking other DNS set up under `willscott.github.io`.
> Switch static web UI url to the new repo at IPNI GitHub Org

- announce/receiver_test.go
- api/v0/admin/client/http/client.go
- assigner/core/assigner.go
- assigner/server/server_test.go
- command/init.go
- config/policy.go
- internal/registry/errors.go
- internal/registry/policy/policy.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/admin/http/handler.go
- server/admin/http/server.go
When an existing indexer is configured to work with an assigner service, automatically self-assign the publishers from all of the indexer's providers.
This PR also decouples assignment from allow/block policy, making the two independent of each other. This makes it easier to reason about what the policy does, whether or not the indexer is using an assigner service. It also means that an indexer's policy does not need to change to work with an assigner service, and allows more capabilities such as being able to reject the assignment of specific publishers on an indexer.
> Prepare existing indexer for use with assigner service

- deploy/manifests/base/heyfil/deployment.yaml
- deploy/manifests/base/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Add the deployment manifests belonging to `heyfil` to `prod` deploy folder of storetheindex so that they are version controlled.
The structure to be revisited on move to IPNI org.
> Add `heyfil` deployment manifests to VCS

- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
Deploy the latest `heyfil` which introduces the deal and provider coverage metrics.
> Deploy latest `heyfil` for coverage metrics

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy the latest `indexstar` so that it returns non-OK response when a provider is not found.
> Deploy latest indexstar with fix to get provider status code

- dagsync/announce_test.go
- dagsync/dtsync/publisher.go
- dagsync/http_test.go
- dagsync/httpsync/publisher.go
- dagsync/httpsync/sync_test.go
- dagsync/interface.go
- dagsync/subscriber_test.go
- version.json
This allows seeing what interface/port the publisher's listener is bound to.
This is needed to fix https://github.com/filecoin-project/index-provider/issues/300
> API to get addresses publisher is listening on

- Dockerfile
- deploy/manifests/base/assigner/deployment.yaml
- Docker file needs to copy assigner start script
- Revise ENTRYPOINT override.
This will require a follow-up PR to use the new docker image.
> Fix assigner deployment

- deploy/manifests/base/assigner/deployment.yaml
Since `command` is used in deployment.yaml, this overrides both `ENTRYPOINT` and `CMD` in Dockerfile.
> Provide items for Dockerfile ENTRYPOINT and CMD in deployment.yaml

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- Use latest image for dev indexers
- Configure ber and cali to use assigner service
> Configure dev indexers to use assigner service

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy latest to fix empty providers listing by `/providers` in indexstar.
> Fix empty providers listing by `indexstar`

- command/daemon.go
- config/ingest.go
- deploy/infrastructure/dev/us-east-2/cloudfront.tf
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/config.json
Direct HTTP announce messages need to be routed to the assigner node.
Also, do not have other dev indexers republish direct announce messages.
> Redirect HTTP announce messages to assigner node

- api/v0/admin/client/http/client.go
- assigner/config/assignment.go
- assigner/core/assigner.go
- assigner/core/assigner_test.go
- assigner/core/order_test.go
- command/admin.go
- command/daemon.go
- command/flags.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/admin/http/handler.go
- server/admin/http/server.go
When an indexer is reconfigured to use an assigner service, it may already have some indexed content from some publishers. Instead of automatically self-assigning all of these publishers to the indexer, these publishers will instead be seen by the assigner service as preferred assignees for the indexer. This allows the assigner to choose a subset of the indexers to assign a publisher to, preferring indexer(s) that have already indexed content from that publisher.
Changed default assignment replication to 1, so that each publisher is assigned to one indexer.
When assigning a publisher to an indexer, the candidate indexers are ordered first by "preferred" status, and then by the minimum number of publishers already assigned.
Note: Publishers that are preset for assignment to specific …
> Do not auto-assign all publishers

- assigner/server/server_test.go
- dagsync/dtsync/syncer.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/finder/handler/finder_handler.go
- server/finder/http/protocol_test.go
- server/finder/http/server.go
- server/finder/libp2p/handler.go
- server/finder/libp2p/protocol_test.go
- server/finder/libp2p/server.go
- server/finder/test/test.go
- server/ingest/test/test.go
When an existing indexer is configured to use an assigner service, that indexer may have registered providers/publishers where the publishers are not assigned. These should not be polled since the indexer does not have responsibility for them.
Also, stabilize stats tests by refreshing stats in order to have a non-zero entries count.
> Only poll assigned publishers when using assigner

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy support for the new HTTP delegated routing in `dev` environment for testing purposes.
See: https://github.com/ipni/indexstar/pull/45
> Deploy support for new delegated routing on `indexstar`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
This prevents the indexers from polling unassigned publishers.
> Deploy latest indexers to dev

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy the latest changes to translated delegated routing on `dev`, which introduces a dedicated field, `Schema`.
See:
- https://github.com/ipni/indexstar/pull/52
> Deploy latest to `indexstar` with changes to delegation routing

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy the latest `indexstar` on `prod` which introduces support for the new delegated routing HTTP protocol.
See:
- https://github.com/ipni/indexstar/pull/52
> Deploy latest to `indexstar` on `prod`

- assigner/config/daemon.go
- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/config.json
Indexers all use port 3003 for their libp2p listener, and the assigner should use this also by default.
- Update assigner to latest image
- Peer ber-indexer and cali-indexer to assigner
> Use consistent port for libp2p listener

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
- Configure assigner for replication of 2
- Configure assigner to assign NFT storage to oden node
- Configure all indexers to peer to assigner node (instead of kepa)
- Configure all indexers to use assigner service
- Configure all indexers and assigner to use v0.5.3 image
> Configure indexers to use assigner service

- config/discovery.go
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
- internal/registry/registry.go
Due to the situation described in #1116, initial configuration of the production indexers to use the assigned service resulted in a very unbalanced assignment. This PR is a way to do a one-time reset of the assignments on the production indexer.
Fixes #1118 
When persisted assignments of a previous version are present on an indexer, these are migrated to the new version. If the configuration value `Discovery.RemoveOldAssignments` is true, then the old version assignments are deleted instead.
Configuration of the production indexers is set to delete these assignments.
manual testing
Reverting will result in losing persisted assignments because they will not be recognized.
> Reset assignments on indexer

- assigner/core/assigner.go
- assigner/core/assigner_test.go
If an indexer is offline when the assigner service starts, the assigner cannot read the existing assignments or preferences from that indexer. The assigner will not know what publishers are assigned to that indexer, resulting in assigning those publishers to other indexers as announcements from them arrive.
The assigner service needs to retry getting indexer assignments before assigning a publisher to an indexer, since that publisher may already be assigned to an offline indexer. This prevents over-assigning publishers to the indexer pool.
Fixes #1118 
If the assigner starts without getting assignment information for all indexers in the pool, then it will recheck each time an announce message is received from an unassigned peer. If there are still indexers offline, the assigner assumes …
> Assigner waits to get existing assignments from indexers

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/config.json
Only the assigner should be resending direct announcements. Otherwise, there will be unnecessary noise.
> kepa should not republish direct announce messages

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy latest `indexstar` to `dev`.
Relates to:
- https://github.com/ipni/indexstar/issues/54
> Deploy HTTP delegated routing metrics  to `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Handle `PUT` to root of `/routing/v1/providers` as 501 and respond to `OPTIONS` correctly.
> Fix `PUT` route in HTTP delegated routing on `dev`

- api/v0/httpclient/client.go
- api/v0/httpclient/options.go
- assigner/server/option.go
- assigner/server/server.go
- command/daemon.go
- dagsync/dtsync/option.go
- dagsync/dtsync/publisher.go
- internal/registry/option.go
- internal/registry/registry.go
- server/admin/http/options.go
- server/admin/http/server.go
- server/finder/http/options.go
- server/finder/http/server.go
- server/ingest/http/options.go
- server/ingest/http/server.go
Use consistent options implementation through out this project.
This is a code style change, not a functional change.
> Consistent options implementation

- fsutil/disk/usage.go
- fsutil/disk/usage_unix.go
- Report percent as actual percent (need to multiply by 100).
- Convert all stats to 64bit before doing calculations, so that it works on systems that provide stats as signed or unsigned values.
> Fix reported usage percent, and make compatible with FreeBSD.

- api/v0/finder/client/http/client.go
- api/v0/finder/client/http/dhash_client.go
- api/v0/finder/model/model.go
- go.mod
- go.sum
This PR adds a dedicated dhash http client that ca be used to perform double hashed lookups (given that the ipni instance supports it)
> Add dhash http client

- assigner/core/assigner.go
- dagsync/subscriber_test.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/metrics/server.go
Maintain a disk usage metric, percent usage, for the file system located at the location of the value store.
This addresses #119 and #484
Also removed useless metrics update signaling:
Ingestion metrics are updated periodically if an update has been signaled. If the indexer has any activity, update is signaled. So in almost all cases the update is signaled. If the indexer has no activity, there is no point in avoiding the update because the indexer has nothing better to do, plus the metrics should still be updated as they may be affected by other external factors like fs usage or storage compacting.
So, remove the update signaling since it does not help anything, and only causes unnecessary context switches. Simply update the metrics periodically instead.
> Add disk usage metric for value store

- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
If an ad has no entries and no metadata, then it used only to update provider addresses and is not an error.
If an ad has entries but no metadata, then an error is logged an the ad is skipped.
Fixes #1148
> Skip advertisements that have no metadata

- Makefile
- version.json
Freeze/handoff functionality is a major feature that is the final part of the write-scalability solution. However, if does not introduce any breaking changes, so only a minor version update.
- Fixed Makefile to set version correctly.
> Update version in prep for deployment of freeze/handoff functionality

- command/daemon.go
- config/datastore.go
- config/ingest.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/ingest/option.go
- server/admin/http/server_test.go
- server/ingest/http/handler_test.go
- server/ingest/test/test.go
Separate datastore for ads and entries is optional and only done if the configuration `Datastore.DirAdvertisements` is set.
Added option, Ingest.KeepAdvertisements, to prevent advertisements and entries from being removed after ingestion.
> Option to store advertisements and entries in a separate datastore

- api/v0/libp2pclient/client.go
- dagsync/p2p/protocol/head/head.go
- Remove code to resolve address before gostream.Dial
- No longer necessary to explicitly close resource manager
> Remove unneeded code

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/internal-service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/pvc.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
Deploy `dhstore` as an internally accessible service only on `dev` with minimal resource demand and a 10Ti `io2` PVC volume.
The internal service configures an internal DNS name for the service, resolvable only within the VPC pointing at an internal NLB.
> Deploy `dhstore` to `dev` on minimal resources

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Upgrade to the latest indexstar in order to roll out encrypted results aggregation capability.
Configure `dhstore` as a backend.
> Upgrade to latest indexstar on `dev` and configure dhstore backend

- version.json
Turns out that a multiaddr with a p2p peer ID is not dialable. This new version has a fix for that.
> Update version to deploy multiaddr fix to prod

- dagsync/subscriber.go
Need to store the fixed multiaddr, with the p2p peer ID removed, in the peerstore. This is a follow-up to #1160
> Put fixed multiaddr into peerstore

- deploy/manifests/base/assigner/deployment.yaml
It appears to be causing a deployment problem: Deployment/storetheindex/assigner dry-run failed, reason: Invalid, error: Deployment.apps "assigner" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'...
> Revert assigner deployment strategy

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Try out deployment strategy `Recreate` on dev only in order to investigate earlier deployment issues.
Relates to:
- https://github.com/ipni/storetheindex/pull/1172
> Test assigner `Recreate` redeployment strategy on dev only

- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Revert changes to `dhstore` done by mistake
Try out deployment strategy `Recreate` on dev only in order to investigate earlier deployment issues.
Relates to:
- https://github.com/ipni/storetheindex/pull/1172
> Test assigner `Recreate` redeployment strategy on dev only take 2

- deploy/manifests/base/assigner/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/deployment.yaml
The assigner service should always run as a singular instance. By default, deployment objects use a rolling update strategy with 25% surge. This means when the assigner service is redeployed a pod is started first and until that pod is not `READY` the old one won't be terminated.
Kubernetes also supports a `Recreate` strategy, where pods are explicitly terminated before new ones are created, which is the one we are looking for. However, because the default keys for strategy are populated we end up with an invalid manifest if only `type` is set to `Recreate`, where we have both rolling update config and type recreate.
To avoid this, explicitly override `rollingUpdate` config to `null`. See inline code comments for related K8S issue.
The changes here fixes this for assigner overlay at …
> Override default rolling update strategy in assigner

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/pvc_addata.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/pvc_data.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/kustomization.yaml
Setup new AGO instance in dev that:
* Uses DH store
* Doesn't keep index locally
* Keeps chain of advertisements
> Add ago dev instance

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
Run the latest version of the code that recognises dhstore config and adds extra logging for debugging purposes.
> Run containers with latest code on `ago` and `dhstore`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy latest fixes to `indexstar` on `dev` that returns response to found encrypted multihash results.
Relates to:
- https://github.com/ipni/indexstar/issues/61
> Deploy `indexstar` fix to encrypted result response check

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/deployment.yaml
Increate ago memory limit as it has been OOMKilled multiple times over the weekend.
See https://github.com/ipni/storetheindex/issues/1185
> Increase ago memory limit

- api/v0/finder/client/http/dhash_client.go
- go.mod
- go.sum
* Fix a few errors that hasn't been properly checked in the double hashed flow
* Updated to the latest version of go-indexer-core that fixes a bug with splitting value keys
* Fix a bug with parsing find metadata response
> Fix dhash client bug

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
To permit `provider verify-ingest` command to execute successfully increase the max accepted body size to the default in popular HTTP servers like nginx, i.e. 1 MiB. The default value of 8 KiB in indexstar seems a bit too conservative.
> Increase max accepted request body size in indexstar

- deploy/infrastructure/common/ecr.tf
Create a private ECR repo for `caskadht` in preparation for pushing containers and deployment.
See: https://github.com/ipni/caskadht
> Create private ECR repo for `caskadht`

- api/v0/finder/model/provider_info.go
- command/providers.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/registry/apiconv.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/finder/http/handler_test.go
- server/finder/test/test.go
- server/finder/test/test_extended_providers.go
- server/ingest/handler/ingest_handler.go
In the provider info, track how far behind the current sync the indexer is.
This can be seen in the output of the providers command:
```
$ ./storetheindex providers list
Provider 12D3KooWEDBLgMaCr6ZFwjDXr7eMXzb7s7SnHJHrYRYWYbQSxMif
Addresses: [/ip4/147.75.63.129/tcp/4001 /ip4/147.75.63.129/tcp/4002/ws /ip4/147.75.63.129/udp/4001/quic /ip6/2604:1380:45f1:d800::3/tcp/4001 /ip6/2604:1380:45f1:d800::3/tcp/4002/ws /ip6/2604:1380:45f1:d800::3/udp/4001/quic]
LastAdvertisement: baguqeerasgthifu4x7fk2tp4cj37jgzcajuqe64ad22ceis36ud42i3rzhoq
LastAdvertisementTime: 2023-01-26T20:01:41Z
Lag: 884
Publisher: 12D3KooWQGDoQTwQPjWZzkJLWPErdTCPscF9bQBZB73yf8wpu9VZ
Publisher Addrs: [/ip4/147.75.63.129/tcp/3103]
IndexCount: 2300000
```
> Track index lag for each provider

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy support for streaming `ndjson` responses to `dev` environment. See:
- https://github.com/ipni/indexstar/pull/68
> Deploy the latest `indexstar` with support for streaming to `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
Deploy fixes to stream handling on `indexstar` in dev and upgrade `ago` to run on the same instance as other nodes.
> Deploy streaming fixes to indexstar on `dev` and upgrade `ago`

- api/v0/finder/client/http/client.go
- api/v0/finder/client/interface.go
- api/v0/finder/client/libp2p/client.go
- command/providers.go
- internal/registry/apiconv.go
- internal/registry/apiconv_test.go
- internal/registry/registry.go
- server/finder/handler/finder_handler.go
- server/finder/http/handler.go
- server/finder/libp2p/handler.go
- server/finder/test/test.go
Remove metadata query parameter that changed behaviour of whether metadata has been included into extended provider results. Including metadata is required so that the client can correctly assemble extended provider results.
> Remove optional metadata query parameter

- server/finder/http/server.go
Fix a bug where accept header value was not being delimited before being parsed resulting in false invalid accept header error.
> Splint accept header value before parsing

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy the latest indexstar on dev that introduces a separate config for timeout value of streaming responses.
> Update indexstar on dev with separate stream timeout config

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Configure indexstar to return `ipfs-dht` on `OPTIONS` request as allowed cascade label.
> Fix cascade labels for indexstar `OPTIONS` on dev

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
Now that dev indexer instance are migrated to smaller nodes destroy the old node groups.
> Destroy redundant r5b 4xl node groups

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
... so that we don't have to keep an instance up per subnet.
> Split general purpose `dev` node groups by subnet

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
Destroy the old workgroup now that all the pods are manually drained from all the nodes managed by it.
> Destroy now redundant workgroup on dev to save on cost

- deploy/manifests/dev/us-east-2/cluster/kube-system/io2-storage-class.yaml
Configure `gp3` storage class on dev in preparation to move io2 type indexer volumes to it.
Set it as the default volume type for the cluster.
> Add gp3 storage class to `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/pvc-gp3.yaml
Test that `gp3` volume types instantiate correctly from the snapshot on `ber` in `dev` environment before rolling out to the other node and removing the existing `io2` volume.
> Test out `gp3` volume types on `ber` in `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/pvc-gp3.yaml
Now that `ber` is happy; move `cali` to the cheaper `gp3` volume type instantiated from snapshot taken few days ago.
> Move `cali` to `gp3` volume type on dev

- api/v0/finder/client/http/dhash_client.go
- command/flags.go
- command/init.go
- e2e_test.go
* fix a bug in the double hashed client that caused an invalid memory access if extended providers are nil;
* add a new flag to `storetheindex` to specify `dhstore` url on initialisation;
* include `dhstore` and double hashed client into e2e test;
* allow specifying different urls for `dhstore` and `storetheindex` in the double hashed client so that the client can work without indexstar running in front.
Fixes https://github.com/ipni/storetheindex/issues/1214
> Include dhstore into e2e test

- internal/registry/registry.go
- internal/registry/registry_test.go
Check that extended provider and contextual exteneded providers do not have empty addresses, before updating this information in the registry.
Fixes issue #1152
> Validate that extended providers do not have empty addresses

- internal/registry/registry.go
Add a log message when provider gets deactivated
> Log when provider gets deactivated

- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/dido-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/kepa-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/oden-snapshot.yaml
Snapshot the PVC of all nodes in prod to prepare for move to the cheaper `gp3` storage class.
Relates to #1042
> Snapshot `prod` node PVC for move to `gp3` storage class

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/service-external.yaml
In order to peer `caskadht` with IPFS bootstrap nodes it needs to be accessible externally.
Test exposure of the libp2p node over `dnsaddr` in `dev`.
> Expose `caskadht` libp2p node externally needed for peering

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
It looks like we hit the outbound connection limit in caskadht accelerated DHT client. The limit is already 65.5K; it is unclear why this is still insufficient.
For now disable resource manager completely and observe the service. It is OK for the node to die because of exceeding resource usage; K8S will just restart it. Right now we want to understand weather accelerated DHT client functions in prolonged periods of time given no resource limits.
> Disable resource manager in `caskadht`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
`caskadht` is running hot on CPU, increase the limit from the minimal configured.
Disable logging for `net/identify` subsystem as it is very noisy.
> Increase CPU resources of `caskadht` and adjust logging

- carwriter/carwriter.go
- carwriter/carwriter_test.go
- config/ingest.go
- e2e_test.go
- internal/ingest/ingest.go
An advertisement and its multihash entries blocks are all stored in a single CAR file. The car file has two roots, the advertisement CID and the entries CID. The entries CID root may be omitted if the advertisement has not entries.
> Write advertisement and entries into one CAR file

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Upgrade to the latest indexstar and caskadht to roll out bug fixes and improvements, namely local address filtering, logging improvements and better unsupported media type debugging.
> Upgrade to latest indexstar and caskadht

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Put metadata latency spikes sporadically. Disable WAL to see if the spikes continue.
> Disable WAL in dhstore to investigate put metadata latency spike

- api/v0/finder/client/http/dhash_client.go
- api/v0/finder/model/model.go
- api/v0/finder/model/model_test.go
- server/finder/handler/finder_handler.go
- server/finder/http/handler_test.go
- server/finder/test/test.go
- server/finder/test/test_extended_providers.go
- server/reframe/reframe.go
Explicitly tag fields in response `structs` such that empty values are omitted. The struct types are used by `indexstar` which in the case of aggregation results in empty fields in JSON.
> Omit empty JSON keys to avoid empty values in encrypted response

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Deploy the latest `indexstar` that introduces translation of all non-streaming lookups into streaming backend requests.
Increase backend call timeouts so that the chances of at least cache getting updated even if client times out earlier.
In the case of lassie the timeout is set to 1 minute, and short timeout on server side results in false-negative 404s.
Once tested on `dev` will be rolling out to `prod`.
> Deploy translation of all non-streaming lookups to streaming on `dev`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Roll out changes that will translate all non-streaming requests to streaming backend requests to prod now that the functionality is working on `dev`.
> Roll out streaming translation of indexstar to prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
* Currently dhstore runs on `r6a.xlarge` at close to 100% CPU load
* `r5n.2xlarge` will give us 8 vCPUs (vs 4 currently) as well as 64GiB RAM (vs 32 currently)
* Compute optimised instances with 8 vCPUs have less than 32GiB RAM. Compute optimised instances with 16 vCPUs and 32 GiB RAM are at least as expensive as `r5n.2xlarge`.
> Deploy dhstore to larger instance

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
They are maxing out memory and CPU.
> Bump caskadht resources on both dev and prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
Roll out implementation of async peer routing lookups onto `dev` environment with increased resource manager limits.
Relates to:
- https://github.com/ipni/caskadht/pull/26
> Roll out async peer routing of `caskadht` on dev

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Roll out fixes to async peer routing and indexstar to prod.
Reduce timeouts for nonstreaming down to 10 seconds.
> Rollout the latest fixes to caskadht and indexstar on `prod`

- deploy/infrastructure/dev/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/eks.tf
This is so that we can accommodate the scaleup of `caskadht` on prod.
Clean up terraform files by removing redundant ttls in cloudfront config that resutls in noop updates. The ttls should only be specified in cloudfront policy if one is associated to the origin.
> Increase max instance counts for general purpose nodegroup

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
From the latest metrics observations I can correlate latency spikes with:
* peak in read amplification
* bottom in flush count
* peak in compaction estimated debt
As per the [official docs](https://www.cockroachlabs.com/docs/stable/common-issues-to-monitor.html#lsm-health) that means that pebble has an imbalanced LSM tree and falls behind on compactions. That can be either due to high concurrency or low IOPS. The latter doesn't seem to be an issue, so we need to tweak the former and see the impact.
> Reduce ago ingest worker count

- server/finder/http/handler_test.go
- server/finder/http/server.go
The find server would fallback on landing page on any request for which there was no matching path, because the handler for `/` was not checking path. This meant that requests for paths that are not offered by finder like `/metadata` would result in 200 response of content type text/html.
Instead, find server must check the path requested on fallback mux and only return landing page if either `/` or `/index.html` is requested.
The changes here strictly check the path before returning the landing page and assert it is so in tests.
> Fix a bug where unknown paths always return landing page

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/deployment.yaml
Create `c6a.8xl` worker node group in us-east2b subnet and move oden to it.
note that the memory available is halved as it was unused by oden. It is starving on CPU right now.
Relates to #1310
> Move `oden` to CPU optimised worker node group

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
Both nft.storage and pinata are assigned to the same node `oden`. Explicitly add pinata to `kepa`.
Relates to #1310
> Assign pinata to `kepa`

- assigner/server/server_test.go
- command/admin.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/admin/http/handler.go
Unassign command removes a publisher assignment from an indexer. Restarting the assigner service is required, as a separate action, to see the assignment removal.
> Add unassign command

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
It was bumped to see the behaviour of caskadht at the face of json requests. But it impacts service performace across indexstar and this should serve as encouragement for users of DHT cascadeing to move to streaming requests.
> Reduce sync result timeout back to 5 seconds on indexstar

- announce/httpsender/sender.go
- announce/httpsender/sender_test.go
- server/ingest/handler/ingest_handler.go
- server/ingest/http/server.go
Fixes https://github.com/ipni/storetheindex/issues/1093
Instead of only accepting CBOR:
Read the request Content-Type header
if it is JSON,
parse the body as JSON
convert to CBOR
and pass onto the indexer internal handlers
Otherwise, fallback on CBOR decoding as it is working currently.
TestJSONSend
> support json HTTP announce

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
After reducing the number of concurrent workers from 20 to 10 yesterday I can observe a significant improvement in latencies. There are some occasional spikes though and some of the parameters such as number of L0 open files (high thousands) and read amplifications (>50) are still elevated to what they should be. However there is a huge improvement. 
I suspect that pebble is still trying to crunch through the accumulated compaction debt that causes these occasional spikes. 
Reducing the number of concurrent workers further to give pebble some breathing room while still doing the work.
> Further reduce number of concurrent workers

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Fix client timeout to be maximum of streamin/nonstreaming timeout.
Reduce non-streaming timeout to 2 seconds in order to reduce downstream timeouts for clients. If a backend is slower than 2 seconds it is already too slow and users should use streaming response instead.
See:
- https://github.com/ipni/indexstar/pull/87
> Deploy separation of indexstar cascade backend on `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
dhstore has caught up with compactions, all metrics are back to normal, CPU is underutilised. Scale back worker count to 10.
> Scale ago ingest worker count back to 10

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Working on `dev` promoting to `prod`
See:
- https://github.com/ipni/indexstar/pull/87
> Deploy separation of indexstar cascade backend on `prod`

- command/daemon.go
- config/indexer.go
I observe that some occasional latency spikes that happen due to compaction result into http timeout on ago side. The vast majority (if not all) of them are under 10 seconds. Setting dhstore http timeout to 10 seconds so that such spikes don't result into ingestion errors.
> Add dhstore http timeout configuration option

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
Ago and dhstore perform well after all recent tunings. The last remaining issue i- s occasional latency spikes that happen due to compactions once in 1 or 2 hours. The default timeout of 10 seconds is not enough to cover for those. Bumping it up to 20s.
> Set dhstore http timeout to 20s

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
It seems there is an issue in webtransport session management that causes a panic and crashes the nodes. This was observed in one of the prod nodes at 1220 UTC.
Until fixed, disable webtransport protocol to limit exposure.
See:
- https://github.com/quic-go/webtransport-go/issues/66
> Disable webtransport protocol on `caskadht` due to panic bug

- deploy/manifests/base/k6-operator/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/monitoring/prometheus-patch.yaml
Deploy `k6` operator to `dev` environment to streamline load testing for Bedrock team. This is to be demoed later at Bedrock colo.
> Deploy k6 operator to `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
Upgrade `caskadht` with latest dependencies that includes fix to webtransport panic.
Test this on `dev` before rolling out to `prod`.
> Deploy fix to webtransport panic on `dev`

- api/v0/finder/model/provider_info.go
- command/providers.go
- internal/registry/apiconv.go
- internal/registry/registry.go
- internal/registry/registry_test.go
An indication is only shown when the provider is inactive. When active, no indication is given.
> Show inactive providers when listing or getting provider info

- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
Tested on `dev`; upgrading to prod.
> Upgrade to latest `caskadht` on `prod` with webtransport panic fix

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
If using a separate ad datastore, as ago does, then keep ad data there and do not move it into car files.
> Do not use carwriter if using separate datastore for ad data

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
This will keep ads in the ad datastore and not move them into car files.
> Deploy latest to ago

- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Scale out `caskadht` and `indexstar` to 5 instances, and reduce streaming timeout to 5 seconds to avoid too many lingering connections considering the increase in total traffic since ~0600 UTC.
> Increase capacity to cope with traffic on prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/dhstore-snapshot.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/kustomization.yaml
Take snapshot before wiping out PVC and restarting re-ingestion due to a recently discovered bug in calculation of second hash.
> Take dhstore snapshot

- carstore/carreader.go
- carstore/carreader_test.go
- carstore/carwriter.go
- carstore/carwriter_test.go
- carstore/const.go
- carstore/option.go
- config/ingest.go
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- e2e_test.go
- filestore/filestore.go
- filestore/filestore_test.go
- filestore/local.go
- filestore/option.go
- filestore/s3.go
- internal/ingest/ingest.go
There is a new config option, `Ingest.CarMirrorDestination.Compress`, to compress CAR files. If unspecified, this value defaults to "gzip". Carfiles will be compressed and be named with the suffix `.car.gz`
Other changes:
- filestore package should not depend on sti config. The filestore package is available outside of storetheindex. To be more generally useful, it should not depend on storetheindex configuration.
- Convert ads from datastore to cars without reading all ad cids first.  This will be used later when migrating from a separate ad datastore.
> Option to compress CAR files (defaults to use gzip compression)

- go.mod
- go.sum
Update to the latest version of the core that fixes the [bug](https://github.com/ipni/go-indexer-core/pull/141) with second hash calculation.
I'll update this branch to point to the release version once the linked PR is merged.
> Update to the latest core

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
Bump up Ago worker count as dhstore runs underutilised on both machine as well as db fronts
> Bump up Ago ingest worker count

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
Remove custom image tag so that ago gets updated to the latest version in dev. Also reduce number of replicas for dhstore and ago to zero as ingestion will have to be started again.
> Remove custom image tag for ago

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
Amazon Cloudfront HTTP caching of false-negative CID lookups  is DoS-ing all Saturn L1s using Lassie.
Any hiccup in content routing of a CID is cached for 5 minutes, no L11 can retrieve it, gateway can't return it.
1. The user adds content to IPFS node, then tries to open it in a browser before sharing link with a friend.  This is what every IPFS user was trained to do for the past 7 years, and tools like IPFS Companion and Brave copy shareable links to clipboard, so user can paste and load CID via gateway within seconds.
2. In Rhea gateways backed by Saturn L1s IPNI DHT proxy is used for content routing, and that creates UX papercut:
- Different Saturn L1s will ask IPNI for the same CID multiple times. 
- If a user tries to load content too fast, and one L1+Lassie fails to find …
> fix: lower 404 ttl to decrease end user failures

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
Reverts ipni/storetheindex#1344
Experimented with for ~20 minutes at prod, observed the following:
* Resulted it significant increase in find latency at p75th and above
* Did not increase 200s returned by cid.contat. just 404s shooting up
* High client latency observed by hydras
* No change in Caboose 404 fetch  errors
Cc @lidel  @willscott
> Revert "fix: lower 404 ttl to decrease end user failures"

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/deployment.yaml
Spikes of p95th lookup latency at cid.contact correlate to CPU spikes of DHT lookup cascades. The service is already given 30 CPU cores which is a lot. To maintain DHT lookup cascading as a feature we need a more efficient implementation of DHT client mode. Before any further work on optimising the accelerated DHT client, however, we should understand how the non-accelerated version behaves.
Disable accelerated DHT on `dev` and `prod` for `caskadht` instances in order to understand:
* resource consumption between the two
* lookup performance between the two
> Disable accelerated DHT on `caskadht` instances

- dagsync/dtsync/util.go
- dagsync/subscriber.go
Add logs to check that:
* DT manager starts up fully.
* onSyncFinished hooks don't deadlock on mutex.
Relates to:
- https://github.com/ipni/storetheindex/issues/1371
> Add extra logging to improve visibility into initialisation hanging

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
Ago doesn't seem to be able to cope with 12 concurrent workers. There have been a few timeouts overnight (which means that a single put took longer than 20 seconds to complete). In this commit set number of concurrent workers back to 10 (as ago showed stable performance with that number), increase batch size from 1024 to 5000 to see whether ingestion rate would improve and increase http timeout to 30s to reduce timeout rate.
> Update ago config

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/kustomization.yaml
To get the node back up. See:
- https://github.com/ipni/storetheindex/issues/1371
> Deploy wrapped data transfer datastore onto `ber`

- command/loadgen.go
- dagsync/subscriber_test.go
- filestore/filestore_test.go
- internal/ingest/ingest.go
Goroutines may be waiting for worker availability when shutdown, which causes unnecessary delay in shutting down and may even lead to a forced shutdown. This PR fixes this by also waiting on a shutdown signal when waiting for an available worker.
Include minor command description fix.
> Do not wait for worker availability when shutdown

- deploy/manifests/base/lookout/deployment.yaml
- deploy/manifests/base/lookout/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/pod-monitor.yaml
Define base manifests and deploy `lookout` on `dev`. See:
- https://github.com/ipni/lookout
> Deploy `lookout` the new monitoring service on `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/kustomization.yaml
Configure the bespoke `dev` monitoring config that checks both cached and uncached endpoints with and without cascading.
> Set `dev` specific config for `lookout` monitoring service

- filestore/filestore_test.go
- filestore/local.go
- Stabilize test on windows
- Remove unnecessary file Close
- List, does not wait for file info to be read before getting next
> Stabilize Windows test

- deploy/manifests/base/dhfind/deployment.yaml
- deploy/manifests/base/dhfind/kustomization.yaml
- deploy/manifests/base/dhfind/labels.yaml
- deploy/manifests/base/dhfind/pdb.yaml
- deploy/manifests/base/dhfind/service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/pod-monitor.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
DHFind is a http facade for dhstore that performs hashing and decryption on behalf of the client.
* deploy `dhfind` on a configuration that is similar to `caskadht`.
* `dhfind` is going to be run in "simulation" mode that is going to return 404 to all requests.
* add `dhfind` as another backend for indexstar.
> Add dhfind deployment configuration

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
Fix CrashLoopBackoff error due to a missing CLI flag
> Deploy new version of dhfind

- api/v0/httpclient/client.go
This is needed so that go client consumers can see the original error code
> Include http error code into readerror

- assigner/server/server_test.go
- carstore/carwriter_test.go
- command/init_test.go
- config/bootstrap_test.go
- config/config_test.go
- config/init_test.go
- dagsync/announce_test.go
- dagsync/http_test.go
- dagsync/httpsync/maconv/convert_test.go
- dagsync/httpsync/message_test.go
- dagsync/legs_test.go
- dagsync/p2p/protocol/head/head_test.go
- dagsync/subscriber_test.go
- dagsync/sync_test.go
- dagsync/test/util.go
- internal/ingest/ingest_test.go
- internal/registry/policy/policy_test.go
- peerutil/policy_test.go
- server/admin/http/server_test.go
- server/finder/http/protocol_test.go
- server/finder/libp2p/protocol_test.go
- server/finder/test/test.go
- server/ingest/http/handler_test.go
- server/ingest/http/protocol_test.go
- server/ingest/test/test.go
Use the `require` consistently in test code. In some test code it is used in some places and not others.
Use the `require` test utility library in more test code in general to reduce code and have more consistent error messages.
> More consistent use of test library

- announce/receiver.go
- dagsync/subscriber.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/ingest/priority_queue.go
There is some confusion in the indexer about publishers and providers. The terms are sometimes used interchangeably. Publishers and providers are generally the same, so differences are rarely seen, and this generally does not cause any problems. However, the code is confusing about whether a publisher or a provider is being referred to, and on occasion uses the wrong value.
Add comments, change variable names, and update log messages to clarify the use of data pertaining to advertisement publisher and content provider. Add additional comments to clarify indexer behavior and explain advertisement processing workflow.
- Add some minor optimizations
- Fix minor resource leak with pending announce messages from a publisher that is not a provider.
Note: Removed `providerID` type since it was …
> Document code to clarify publisher versus provider

- api/v0/admin/client/http/client.go
- command/admin.go
- server/admin/http/handler.go
Currently there is no functionality for checking whether there are any syncs in progress. That complicates troubleshooting, specifically when the indexer seems to be busy with doing something without writing anything into the datastore. This PR adds:
* a new admin endpoint and respective CLI functionality for fetching a sorted list of currently pending syncs
* it also prevents a sync for the same peer from being submitted while there is one already in-progress.
> Add get pending syncs command

- command/admin.go
Make Publisher ID to be not mandatory flag as it's not required for list-pending command. Instead check it inside the command handler.
> Remove flag from list-pending command

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/metrics/server.go
- internal/registry/errors.go
- internal/registry/registry.go
- test/typehelpers/typehelpers.go
Fixes #1402
Fixes #1404
Fixes #1405 
See the above issues for context.
Cannot process advertisement chain if the first advertisement is missing provider addresses. This is preventing us from ingesting some chains where the first advertisement(s) do not have routable addresses, even if later advertisements do provide routable addresses.
Some non-permanent errors are being incorrectly handled as permanent errors and causing advertisements to be discarded.
This PR fixes #1402 by trying to update using the provider addresses from the head advertisement when ingesting ads deeper in the ad chain.
This PR fixes #1404 by correctly designating errors during ingestion of entry chunks.
Included a test of an ad chain with the first ad missing the provider addresses. Fails without this PR.
Change is …
> Fix missing addr handling

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/internal-service.yaml
So that it is created only in the subnet needed, with enough IPs available.
> Explicitly set subnet for dhstore load balancer

- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/dhstore-snapshot.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/kustomization.yaml
The snapshot is not needed anymore as all data have been reingested in dev
> Delete dhstore snapshot

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/README.md
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/identity.key.encrypted
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/pvc_addata.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/pvc_data.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kustomization.yaml
`inga` is a new production double hashed indexer that writes into production `dhstore`. In this PR:
* create a new node group with the same instance type that is used by `ago` in dev;
* create a new identity for `inga`;
* create a new deployment configuration for `inga`. Note - `inga` won't be mirroring car files into s3 a this is being already done by `ago`.
> Add double hashed indexer - inga

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/deployment.yaml
Fixes k8s error: 
```
0s          Warning   FailedCreate                 replicaset/inga-indexer-59bccc7945                              Error creating: pods "inga-indexer-59bccc7945-" is forbidden: error looking up service account storetheindex/storetheindex: serviceaccount "storetheindex" not found
```
Explicit service account isn't needed as `inga` doesn't need to write to s3.
> Remove explicitly defined sservice account

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#1412
After this change got deployed we've received an upstream latency alert. The latency spike is caused by timeouts in `indexstar`. During scatter-gather half of the times `indexstar` can not resolve `dhfind` host. This is in turn due a lack of free IPs in subnets, which needs to be fixed first.
> Revert "Hook up dhstore to indexstar in prod"

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Replace the old `r6a` nodegroup to span across all subnets.
Create new `c6a` node group in prep for replacing the old ones.
> Replace `r6a` node group and add `c6a` for new subnets

- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
glif API has undergone a set of changes, namely tailing slash in API no longer works. Support for listing state market participants is no longer offered for v0 api.
This version changes the way participants are listed to use list miners endpoint and updates the api endpoint.
> Deploy latest to `heyfil` with lotus v1 support

- go.mod
- go.sum
- server/admin/http/server.go
* Update to the latest version of `go-indexer-core` that supports metrics reporting
* Will switch to the release version before merging this PR
> Report pebble metrics

- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/kustomization.yaml
Upgrade to the latest of `caskadht` and `lookout` in order to rollout support for cascade label list and CID based checking.
Configure `lookout` checker for `cassette` on `dev` to better understand its behaviour.
> Upgrade `caskadht` and `lookout` to latest and add `cassette` checks

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
The mirror configuration has changed with PR #1409 and ago will need the new configuration to continue creating CAR files from ingested advertisement data, if updated with code from #1409 or later.
This PR leaves the old mirror configuration in place in case reverting is necessary.
> New mirror config for ago

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Configure and set YAML config for `cassette` in dev with complete settings and extended set of peers which include known infura nodes.
> Set cassette complete config in `dev` with extra peers

- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Include `cassette` as a backend to `indexstar` on prod and scale it up to 3 nodes.
> Hook up `cassette` to prod load balancer

- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/config.yaml
Add checks to measure lookup coverage when including legacy cascade over
bitswap.
Add an additional explicit check for cassette internal service to help
with debugging.
> Add `lookout` checks for cassette

- dagsync/httpsync/publisher.go
Returning 204 No Content is better than failing with an internal server error.
Fixes #1422
> HTTP publisher returns 204 when nothing to publish

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
Previously, data written to a separate ad datastore was being saved if it was not written to car files. Since the data is never reused if not written to car files, it should not be saved.
> Always remove temp ad data after ad is processed

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Increase number of ingest workers on Inga as dhstore looks underutilised.
> Increase ingest workers on inga

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Increase timeout to dhstore to see whether it'll provide some breathing room to the database and reduce the number of errors
> Increase inga dhstore timeout to 60s

- server/admin/http/server.go
pprof endpoint was broken.  Golang ServeMux requires that the "/" is included for matching anything beyond the `pprof` part of the endpoint.
> Fix pprof endpoint

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Deploy latest to roll out metrics that count messages received per peer.
> Deploy latest `cassette` to add message count metrics per peer

- command/daemon.go
- config/datastore.go
- dagsync/announce_test.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/ingest/option.go
Before the content advertisement mirrors were available, the indexer could be made to keep advertisements and entries data in a separate datastore from the one that other indexer state data is kept in. This datastore could then be copied to other indexers that were starting up to quickly bootstrap indexing.
Now that advertisement mirrors are available as an alternate source of index data, building up advertisements in a datastore is no longer necessary. Any existing ad datastores are no longer needed and can be discarded.
Do not use a separate datastore for temporary ad data
- Use the same datastore instance for temporary data and indexer state
- Remove configuration for separate ad datastore
> No separate ads datastore

- deploy/infrastructure/prod/us-east-2/s3_adstore.tf
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/service-account.yaml
- Configure terraform to create S3 bucker, bucket ACL, iam policy, iam assumable role, and service account.
- Configure inga pod to use new service account for accessing S3 bucket.
> S3 terraform configuration for prod

- dagsync/announce_test.go
- dagsync/http_test.go
- dagsync/httpsync/sync.go
- dagsync/httpsync/sync_test.go
- dagsync/legs_test.go
- dagsync/subscriber.go
- dagsync/subscriber_test.go
- dagsync/sync_test.go
- internal/ingest/hamt_ingest_test.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/invalid_mh_ingest_test.go
- internal/ingest/linksystem.go
- internal/ingest/seg_sync_test.go
- mautil/mautil.go
- mautil/mautil_test.go
- server/admin/http/handler.go
Sync should make use of multiple publisher addresses. Announce messages may contain multiple publisher addresses, and the indexer is only using a single one of these. All should be used. 
Fixes #321
Will also fix this: https://github.com/ipni/index-provider/blob/main/mirror/mirror.go#L236-L238
This changes APIs in a few places to take a peer.AddrInfo instead of a peer.ID and a multiaddr.Multiaddr.
- Updated `ingester.Sync` `dagsync.Subscriber.Sync`, APIs, and `httpsync` and `dtsync` packages to accept multiple publisher addresses
- Updated tests to use updated APIs
Has breaking API changes, so reverting should be avoided after other modules depend on this. Otherwise, revert is OK.
> Sync now accepts multiple addresses

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
* Includes configurable simulation parameters
* Back offs immediately if the simulation channel is full so that doesn't block http thread
> Deploy latest dhfind to dev

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/service-cluster-ip.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Use k8s name instead of load balancer for dhfind to see whether that would reduce a number of find timeouts in dev
> Use k8s name instead of load balancer for dhfind

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
Increase to 200 from the default of 50. The rationale for the change is that dhfind linearly handles requests: all requests are piped into a single channel and picked up by workers. This differs from a regular http server implementation where each request is handled in a goroutine. Considering the current degree of concurrent requests, at around ~1K per second, and the fact that the tasks are wait-heavy increasing the worker count to see impact on round-trip latency from dhfind on prod.
> Increase worker count in `dhfind` on prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Reduce the number of `indexstar` replicas from 5 to 3 in order to decrease the likelihood of race condition where connections to backend compete with each other to complete.
Each indexstar instance opens up to 100 connections per host. The theory is that having 5 instances relative to the current load of ~1.3K requests per second opens too many connections to the backends and therefore slows down the responses rather than speeding things up.
> Reduce `indexstar` replica count to decrease racing condition likelihood

- .github/workflows/ecr-publisher-release.yml
Use a more verbose syntax for stripping `v` suffix from version file.
Only publish images with concrete tag on merge to main
> Fix substitution error for old bash versions and only publish on main

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
These things were for previous versions of storetheindex.
> Remove unused config items from ago config

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
This is needed to give dhstore some breathing room to do compaction and restore LSM tree to healthy state. Just reducing write worker count doesn't seem to be enough as imbalance of LSM tree keeps on growing.
> Temporarily remove dhfind from indexstar in prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/monitor.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
Deploy `heyfil` to dev so that we have better parity with prod environment and can better reason about provider counts since heyfil
makes explicit announcements on behalf of filecoin providers.
> Deploy `heyfil` to dev for better parity with prod environment

- go.mod
- go.sum
Use the tagged versions of dependencies.
Fixes #1512
> Depend on tagged version of go-libipni and go-indexer-core

- internal/ingest/ingest.go
- internal/registry/registry.go
Ingester needs to wait for autosync goroutine to stop before waiting for pending syncs. Otherwise there can be a concurrent read and write to the pending sync WaitGroup.
> Fix race during ingester shutdown

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Inga is configured to save all advertisement data in a separate datastore, and it should not be configured to do this. This PR applies latest fixes and correct the configuration as well.
> Deploy latest fixes to inga in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/pvc_data.yaml
Even though inga is not storing the bulk of indexing data, it is still recording all the advertisements it has processed. Since it is processing all ads for all publishers, this can take considerable space.  The pvc size needs to be expanded.
> Increase pvc size on inga

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/config.yaml
Looks like infura node IPs changed on 1st of April ~2225 UTC. Upon looking up a CID known to be hosted by them, it seems the peer IDs remained the same but the IPs changed. Updating manually.
> Manually update infura IPs

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#1522. Will re-enable it tomorrow as it might cause prod alerts during the night otherwise.
> Revert "Re-enable dhfind in prod"

- deploy/manifests/prod/us-east-2/cluster/kube-system/gp3-storage-class.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/io2-storage-class.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/dido-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/kepa-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/oden-snapshot.yaml
The expropriations on `dido` volume showed that 5K IOPS with 300 MiB/s throughput on `gp3` volume type providers sufficient performance.
Define a storage class with the required IOPS and throughput in order to move production nodes to it.
Instantiate fresh snapshots for nodes as the latest one is 4 days old.
> Add `gp3` storage class with 5K IOPS

- deploy/manifests/base/caskadht/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/caskadht/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/pod-monitor.yaml
Roll out metrics for cascade over DHT on dev and prod.
See:
- https://github.com/ipni/caskadht/pull/31
> Deploy `caskadht` metrics to `dev` and `prod`

- internal/ingest/ingest.go
This PR fixes a concurrency bug that might have caused deadlock in inga as the map in the context was updated outside of the lock
> Fix a bug with autosync mutex

- internal/ingest/ingest.go
- internal/registry/registry.go
- Remove unneeded ingester wait group.
- Rename some variables to clarify use.
> Remove unused variables; rename variables

- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/dhstore-snapshot.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/snapshots/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/dido-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/kepa-snapshot.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/snapshots/oden-snapshot.yaml
Snapshot `dhstore` volume in `dev` in order to move it off `io2` and onto `gp3` volume.
Delete old unused snapshots in `prod`.
> Snapshot `dhstore` in `dev` and delete old snapshots

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/kustomization.yaml
Seems to be redundant, which should roll out newer tagged version.
> Remove `dido` version override

- deploy/manifests/dev/us-east-2/cluster/kube-system/gp3-storage-class.yaml
- deploy/manifests/dev/us-east-2/cluster/kube-system/io2-storage-class.yaml
- deploy/manifests/dev/us-east-2/cluster/kube-system/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/pvc-gp3.yaml
Define `gp3` storage class in `dev` to match `prod` and move `dhstore` to it.
The current `dhstore` `io2` volume to be removed once we confirm the new volume works as expected.
> Move `dhstore` in dev to `gp3`

- internal/ingest/ingest.go
When processing an ad chain takes a long time, another announce or manual sync can cause an overlapped processing of the chain. Overlapped processing may lead to reingesting already ingested ads.  If an ad has already been processed, then do not ingest it again.
In the future, we may need to make fetching ad chains wait until any previous chain from the same publisher has been completely processed. See #1553
> Need to skip already processed ads

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/aws-ebs-csi-driver/patch.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Now that all volumes are moved to `gp3` there is no need for instance types that support `io2` BlockExpress. Destroy them.
Fixes #1039
> Destroy now redundant `r5b` node groups on `prod`

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
Long advertisement chains are iterated and every advertisement is stored in memory until after the chain is processed. This is causing an out-of-memory condition and leading to crash/restart of indexers.
Fix this by not keeping all advertisements in memory at the same time and instead loading each advertisement at the time it is processed.
Fixes issue #1569
No additional tests
> Fix OOM by not keeping all ads in chain in memory

- go.mod
- go.sum
- internal/ingest/ingest.go
A manual sync creates a channel that `adProcessed` events are written to. If multiple events are written to that channel before it is read, this can cause workers to block waiting to write to that channel. If workers are blocked, they will not read SyncFinished events. If SyncFinished events are not read, then dagsync syncs will not complete. When this happens the original manual sync may not finish and the channel will not be read, thereby entering a deadlocked state.
Fixed this by having manual syncs create a channel that cannot fill up and block. This will also help prevent blocking other workers that trying to write adProcessed events.
Manual in dev
> Fix deadlock with manual sync

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/pvc.yaml
DHStore in prod is about to trigger an alert as it's approaching 80% threshold.
> Increase dhstore volume on prod

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
Remove the unneeded goroutine that reads `SyncFinishedEvent`s from dagsync and puts them in another channel that the workers read. Let the workers read the events directly.
Clarified some comments and variable names to document their purpose.
> Workers read SyncFinishedEvents directly

- deploy/infrastructure/dev/us-east-2/saturn-lassie-event-recorder.tf
It is full; increase to 1.5K GiB.
> Increase Saturn Lassie event recorder db size

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
Now that two days or so worth of data is collected, disable the event logs. But leave the S3 bucket to be for now until the data collected is no longer needed.
Relates to:
- https://github.com/ipni/storetheindex/issues/1598
> Disable CloudFront event logs on prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/pdb.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Enable indexstar-canary in prod that will take 33% of the traffic and includes dhfind as one of the backends
> Add canary indexstar in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Play with the number of frontend instances in prod to find the sweet spot for dhfind.
> Set indexstar instances to 3 in prod and 1 in canary

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
Bump up dhfind machine spec in prod to see whether that would help to improve parallelism / performance. 
By the look of it, dhfind's memory utilisation keeps climbing up which means that it's has large waiting queues.
> Bump up dhfind machine spec in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
* cid.contact receives about 24k requests per second
* 6k of them hit dhfind (25%), split across 5 instances - 1.2k per instance
* p99 for processing a find request is 72ms, so a single goroutine can process around 12 of them per second
* 100 coroutines should be enough to cope with that load
* see whether reducing concurrency would improve throughput
> Adjust concurrency in prod dhfind

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/ingress.yaml
Trying to find a sweet spot so that latency percentiles are unaffected
> Reduce canary traffic to 10 percent in prod

- command/daemon.go
- config/ingest.go
- doc/config.md
- internal/counter/index_counts.go
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- internal/metrics/server.go
Track remove and non-remove advertisement counts over indered process lifetime.
- Removed StoreBatchSize config since it is only used for HAMT batching and does not need to be configurable.
- Use atomic.Int64 values instead of operating on int64 with atomic.Int64X functions.
Addresses #1590
> Add counter metrics for remove ads and non-remove ads

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/ingress.yaml
Further reducing canary traffic in prod to be safe overnight before it's clear what causing performance issues.
> Further reduce canary traffic in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
This is done to compare simulation vs non simulation performance and its effect on the lookup metrics against the real traffic
> Switch off dhfind simulation mode in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/ingress.yaml
Switching off simulation mode has improved lookup metrics. Slowly increasing the traffic to the canary channel.
> Increase canary traffic to 10pc in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/kustomization.yaml
Exposing in prod only where it runs in non-simulation mode to verify metrics.
> Expose dhfind for external access in prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
They have been removed by mistake
> Add dhfind and dhstore in dev into lookup path

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/ingress.yaml
Encrypted store has been running ok against 10% for the last 24 hours. Increasing that number to 20%.
> Increase canary traffic to 20%

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
Increase RAM for dhfind as they get OOM killed:
```
State:          Running
Started:      Thu, 27 Apr 2023 11:48:51 +0100
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    137
Started:      Thu, 27 Apr 2023 07:35:46 +0100
Finished:     Thu, 27 Apr 2023 11:48:50 +0100
Ready:          True
Restart Count:  3
```
> Increase dhfind RAM in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/pdb.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/service.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
* Add `dhfind-helga` that points to `dhstore-helga` for lookups. Initially run 2 instances as they will be returning 404s mostly. Scale that up as `dhstore-helga` grows.
* Hookup `dhfind-helga` to `indexstar-canary`
> Add dhfind-helga and hook it up to indexstar-canary

- command/daemon.go
- command/init.go
- config/indexer.go
- go.mod
- go.sum
Note: the release for both go-indexer-core and storetheindex will be cut after the functionality has been tested in dev.
> Add dhstore cluster support

- server/find/http/server.go
"found" flag was always false for streaming requests, which resulted into incorrect success rate reported by the indexers.
> Fix find latency reporting

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
* Further increase canary traffic in prod
* Reduce non-canary indexstar replicas to two so that there are three instances in total (as it was before dhfind rollout)
* Reduce number of dhfind instances down to three as they are underutilised
> Increase canary traffic

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/deployment.yaml
Add inga to the lookup path as dhfind isn't able to satisfy /providers lookups. Inga will return 404s to all double hashed requests.
> Add inga to the canary lookup path

- internal/ingest/ingest.go
Removal ads were not being counted so metric was not being set correctly.
> Fix removal ad counter metric

- internal/ingest/ingest.go
If the first advertisement does not have a provider address, then use the next one available in the ad chain.
This fixes a problem when ingesting long ad chains where the first advertisement received is missing the provider address. When this happened, the indexer would revert to its old behavior of updating the current provider address to whatever is in the ad being ingested. This may be an old and no longer valid address that would not be updated to the current address until ingesting ads later in the chain.
This fix uses the latest provider address in the chain, even if the first ad is missing the provider address.
Manual test, instrumented with debug output.
> Use latest address available in ad chain

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/deployment.yaml
Making `indexstar-canary` to be configured the same as the [main](https://github.com/ipni/storetheindex/blob/main/deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml#L37)
> Bring indexstar-canary config on par with the main

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/config.json
Not peered to kepa-indexer because of misspelling.
> Fix typo in assigner config

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/pvc-gp3.yaml
The new PVC will replace `dhstore-data`. `dhstore-data` needs to be retired because of incorrect size of 20Ti that can not be reduced.
> Create prod `dhstore` PVC from the snapshot

- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Reverting as it affected lookup p50
> Revert "Deploy latest to `prod` environment"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
* if inga is down then dhfind is unable to serve traffic
* with the recent caching improvements, dhfind should be less sensitive to indexstar latency
> Point dhfind to indexstar for provider lookups

- carstore/carreader_test.go
- carstore/carwriter.go
- carstore/carwriter_test.go
- internal/ingest/ingest.go
- internal/ingest/mirror.go
If resyncing, then overwrite any existing CAR file in the mirror for the advertisements that are resynced.
> Overwrite CAR in mirror on resync

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
Had OOM event on dhfind-helga, so increasing memory to match dhfind.
> Increase dhfind-helga memory to match dhfind

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
Lookup traffic seems to have doubled in the last few hours
> Scale up dhfind to 2 instances in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
Reverts ipni/storetheindex#1698
After some hours, it does not seem to make much difference. Putting back to 20 to compare stack traces.
> Revert "Reduce workers on oden from 20 to 10"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Inga is falling behind in some ad chain processing. 
* Increase ingest worker count to see whether that will help to speed up the ingestion
* Bring inga's sti version to the same with the rest of the cluster
> Update inga prod configuration

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar-canary/deployment.yaml
Adding temporary existing backends to canary to backfill for unretrievable ads
> Plug in existing backends to canary

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-helga/deployment.yaml
dhstore-helga now has more data and dhfind-helga has more work to do
It has gotten OOM killed a few times already
> Scale up dhfind-helga

- internal/ingest/ingest_test.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- internal/registry/sequences.go
- server/admin/http/server_test.go
- server/find/test/test.go
- server/ingest/test/test.go
There are really two defects here:
1. A default for `deactivateAfter` is not being set correctly when there is an override.
2. Once an override is encountered, the poll keeps the value of the override for all following providers. It needs to be restored to the previous value for the next provider.
This PR fixes both of these issues.
> Fix poll override causing provider deactivation

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
Poll override was being used to fetch NFT provider updates by polling. Since the HTTP announce is forwarded by the assigner service, this is not needed.
> Remove poll override since announce is relayed by assigner

- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/kustomization.yaml
See:
- https://github.com/ipni/lookout/pull/7
> Roll out lookup coverage check for Internet Archive top CIDs

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Indexstar forwards `/` endpoint to first backend, and this needs to be a storetheindex node.
> Make sti nodes first indexstar backends

- config/ingest.go
- go.mod
- go.sum
- internal/ingest/ingest.go
- version.json
The maximum number of graphsync requests needs to be set to something greater than the graphsync defaults. This PR makes these values configurable by setting config file settings and defaults them to 1024 for both incoming and outgoing requests.
> Fix max in-progress graphsync requests

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
After recent graphsync fix dhstore doesn't seem to be able to cope with 5 concurrent workers.
> Reduce inga worker count to 3

- deploy/manifests/dev/us-east-2/cluster/autoretrieve/event-recorder-cd.yaml
- deploy/manifests/dev/us-east-2/cluster/autoretrieve/kustomization.yaml
Set image repo and selection policy for lassie event recorder in order to automate the image image update and deployment.
This change will eliminate the need to manually restart the event recorder pods in order to reflect the changes of the latest built image.
> Automate image update for `lassie-event-recorder`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
* `dhstore-helga` is 80% full and will trigger an alert soon
* switch writes to the original `dhstore` that is 60% full
* once both dhstores fill up - set up a new one with approx 5TiBs that is going to be used until consistent hashing cluster is fully live and caught up
> Switch writes to the original dhstore

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind/deployment.yaml
dhfind has restarted 11 times due to OOM.
> Increase memory and CPU limits for dhfind

- assigner/server/server.go
- go.mod
- go.sum
Need assigner to use newer `/announce` HTTP endpoint to be compatible with go-libipni HTTP sender.
Fixes https://github.com/ipni/go-libipni/issues/36
> Fix assigner service announce endpoint

- .github/workflows/ecr-publisher.yml
Make a deployable container from `dh-key-sharding` branch for testing the sharding mechanims in dev.
See: https://github.com/ipni/storetheindex/pull/1759
> Build and push images from `dh-key-sharding` for testing

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/dana/pvc_data.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/kustomization.yaml
Deploy a new node called `dana` in `dev` wht the head of #1759 to test out sharding mechanism across dhstore cluster.
The indexer node is configured to read ads from the S3 bucket populated by `ago`.
> Deploy a new indexer in `dev` to test sharding writes

- deploy/infrastructure/dev/us-east-2/eks.tf
Node group is used by indexer nodes and had ha max of 3
> Increase max ASG for r6a nodes in dev

- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
Removed ExtendedProviders additive behaviour. Each ExtendedProviders advertisement will have to have a full set of ExtendedProviders from now on (no deltas). Additive behaviour makes updates and removals harder and is generally counterintuitive.
Context: https://filecoinproject.slack.com/archives/C02T827T9N0/p1684402768677939
> Change ExtendedProviders behaviour to 'replace' instead of 'add'

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
* Read-only dhstore are massively underutilised on the CPU (use 20% at peak)
* Pebble takes 100% of the memory regardless of how much is given. Trying to run read-only instances with lower RAM.
> Turn down read-only dhstore machine metrics

- go.mod
- go.sum
- internal/ingest/linksystem.go
Bubble up the fix in HTTP syncer so that 404s from HTTP publisher are surfaced appropriately. Improve error checking logic to break out early if the error is of kind `ipld.ErrNotExists`.
Relates to:
- https://github.com/ipni/go-libipni/pull/39
Fixes #1771
> Gracefully skip not found content from HTTP publishers

- e2e_test.go
Commands have moved from provider to ipni-cli. This will cause CI tests to fail until this is fixed.
> Use find command from ipni-cli instead of from provider

- command/daemon.go
- internal/freeze/device_unix.go
- internal/freeze/device_windows.go
- internal/freeze/freezer.go
- internal/freeze/freezer_test.go
- internal/ingest/ingest.go
- internal/registry/option.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- server/admin/http/handler.go
Freezer can be created with multiple directories. It will attempt to select one for each separate device, if that information is available. Each selected directory is monitored for disk usage, and freeze happens if any exceeds the usage threshold.
Fixes #1776
> Freezer monitors mulitple directories different devices

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-a/cadi/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-a/saar/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-b/aviv/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-b/dina/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-b/vesa/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-c/bala/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-c/maja/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-cluster/instances/zone-c/zora/kustomization.yaml
The cluster dhstore instances previously participated in a key-sharding experiment using envoy.  We want to delete that data in prep for other experiments using dedicated indexer-dhstore pairs and using FoundationDB.  Before deleting the pvcs, we need to stop the dhstore instances using those pvcs.
> Stop cluster dhstore instances in prep to delete their data

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Disconnect in favour of double hashed data source
> Drum Roll: disconnect old indexers from the read path

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/deployment.yaml
Bump up dhstore-helga CPU as it seems to be the largest contributor to high read latencies
> Bump up dhstore-helga CPU

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Also connect `inga` to indexestar so that it can serve the static page and `/providers` endpoint
> Disconnect old indexers

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#1837
This is to investigate extended providers not appearing as expected on results fetched from double hashed stores. 
Cc @ischasny
> Revert "Disconnect old indexers"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
* Inga has mostly caught up with the rest of indexers so the ingestion profile should get flatter
* Increasing ingest worker count should allow inga to catch up with new ads quicker (dag.house issue)
> Increase ingest worker count in Inga

- deploy/manifests/base/foundationdb/crds/kustomization.yaml
- deploy/manifests/base/foundationdb/namespaced-manager/deployment.yaml
- deploy/manifests/base/foundationdb/namespaced-manager/kustomization.yaml
- deploy/manifests/base/foundationdb/namespaced-manager/rbac.yaml
- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
Deploy FoundationDB CRDs in `dev` cluster.
Define namespaced controller manager manifests in preparation for deploying FDB cluster in `dev` for `storetheindex` namespace.
> Deploy FoundationDB CRDs in dev and define manager manifests

- server/find/http/handler_test.go
- server/find/http/server.go
When an incorrect URL is given to the find API, a blank response body is given with the 404 error code. When used with a user interface like a browser or curl, this is confusing until the error code in the response is inspected. Returning the "Not Found" message eliminates the confusion.
Not much to review here, but the request for review is to double-check that this will not cause any problem for some automation expecting to receive an empty response body for Not Found.
> Return Not Found message with 404

- config/discovery.go
- internal/registry/registry.go
- internal/registry/registry_test.go
When enabling the indexer to use an assigner service, and the indexer already has known providers, then automatically assign the publishers for the providers to this indexer. This makes the publishers immediately eligible for handover if the indexer is frozen.
> When using assigner automatically assign known publishers

- command/daemon.go
- config/indexer.go
- go.mod
- go.sum
Not going to use DH key sharding config
> Remove DH key-sharding config

- Dockerfile
Use more recent image, with go 1.20.x, as build container.
> Build container with go1.20.x

- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdb-cluster/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdb-manager/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdb-manager/pod-monitor.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
Deploy a namespaced FoundationDB controller and a cluster with reasonable configs that are initially tested in a separate namespace.
> Deploy foundation db `dev` cluster

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/pod-monitor.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
Define stateless dhstore manifests hooked up to `fdb-dev` FoundationDB cluster.
> Deploy stateless dhstore manifests

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/pvc_data.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/pvc_data.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/identity.key.encrypted
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/pvc_data.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/kustomization.yaml
New indexer nodes `alva`, `bria`, and `cora`. Each has 100Gi pvc size and are a mirror reader and writer.
> Create new indexer instances

- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Otherwise, coordinator selection fails by the controller.
> Fix FDB cluster name in manifest

- command/daemon.go
- command/update_datastore.go
- config/datastore.go
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ber/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cali/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/dido/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/kepa/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/oden/config.json
- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
- server/admin/server_test.go
- server/ingest/handler_test.go
- server/ingest/protocol_test.go
- Configure indexers to use separate datastore for ad and fsm data.
- Remove old previous version data-transfer fsm records
- Remove current version data-transfer fsm records
- Remove advertisement and entries data blocks
- Record new datastore version string
Fixes #1380
> Store temporary ad data in separate datastore

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/kustomization.yaml
Deploy the new nodes on dev, spread across AZs and point them to the FDB-backed dhstore.
> Deploy new nodes and point to stateless dhstore

- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/config.json
**Not needed if a second assigner #1877 is preferred.**
This configures the existing assigner to assign to only the new indexers.
Notice that the old indexers are still set as peers to assigner. This ensures that rebublisher direct announcements are sent to them.
> Config assigner to use new indexers for FDB valuestore

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/alva/config.json
Increase write batch size on `alva` to experiment with ingest throughput on `dev`.
> Bump `alva` DHStore batch size by 4X

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/bria/config.json
- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/cora/config.json
Tests on `alva` show significant increase in ingest throughput. Bump batch size on remaining nodes.
> Bump DHStore batch size by 4X on remaining `dev` nodes

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/deployment.yaml
In order to have a deterministic and isolated performance analysis explicitly set the resources for `dhstore-stateless` instances. This would make it easier to reason about potential bottlenecks or their absence in the ingest pipeline, since pods would be given the same resources on every deployment and cannot outgrow the limit specified.
> Explicitly set dhstore stateless resources in `dev`

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/deployment.yaml
> Increase `CPU` for `dhstore-stateless` instances

- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Disk IOPS offered by EBS volume is not being fully utilised. Increase the number of storage processes per pod to see the impact on write throughput.
> Increase FDB storage processes per pod to 5

- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
This version has the latest boxo dependency which is the same version as Kubo `0.20.0`.
> Deploy the latest version of cassette in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-manager/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-manager/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Deploy FDB controller manager in `prod` in prep for cluster deployment.
> Deploy FDB controller manager in `prod`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/pvc_data.yaml
That node uses `dhstore` for storage. It is unclear why it's utilising so much disk for provider info. Further investigation needed. For now increase PVC volume to avoid alerts.
> Increase PVC of `inga` to 1Ti

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
These are the instance types that will be used by the new indexers pointed to FDB backed dhstores.
Relates to:
- https://github.com/ipni/storetheindex/pull/1906
> Deploy `r6a.2xl` worker node group on `prod` cluster

- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
IAM role names don't match the ones created.
> Fix typo in prod node workgroup IAM role name

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Leaving oden connected until inga catches up with dag.house. The [provider](https://inga.prod.cid.contact/providers/QmQzqxhK82kAmKvARFZSkUVS6fo9sySaiogAnx5EnZ6ZmC) to watch. 
Also connect inga to not to break `providers` endpoint.
> Disconnect dido and kepa from reads in prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverting as inga on its own is struggling to catch up with new announcements. Will increase ingest worker count to see if that helps Reverts ipni/storetheindex#1912
> Revert "Disconnect dido and kepa from reads in prod"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Inga has caught up with the most of providers. There are a few big providers left (like dag.house) that inga is still crunching through. That blocks all worker-goroutines so that they can not ingest anything from the new providers that are coming in.
> Bump up number of inga's threads

- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/config.yaml
Using default cancel interval of 5s stalls after 10 minutes. Reduce cancellation interval to 2 seconds in prod in order to investigate impact of providers stalling.
Relates to:
- https://github.com/ipni/cassette/pull/30
> Investigate effect of cancelling `WANT`s in `cassette` more aggressively

- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/service-external.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/config.json
Libp2p server is not exposed because the subdomain [assigner.dev](http://assigner.dev/).cid.contact is already in use by ingress for taking in direct announces via HTTP PUT.
The assigner has two different services (HTTP ingest and libp2p). They are handled with two different instances. One uses nginx which handles http, the other uses nlb directly to service. Those two create their own load balancer in aws. Therefore cannot use the same name server record.
This PR gives a new subdomain for the libp2p assigner service, i.e. change the annotation.
> Change dev assigner service hostname

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Reverts ipni/storetheindex#1924
> Revert "Revert "Revert "Temporarily turn inga off to trigger compaction"""

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/deployment.yaml
Inga is failing to schedule in prod. Moving it to the same instance type as other indexer nodes have.
> Move inga to the same instance type as other indexer nodes in prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Deploy latest to cassette which removes the receiver buffer size.
> Deploy latest to `cassette`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/deployment.yaml
Inga has higher concurrency factor now and has been running at 100% CPU lately that has been failing readiness probes.
> Increase number of CPUs on inga

- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Clean up non existing users from K8S `aws-auth` configmap on both `dev` and `prod`.
> Remove redundant users from K8S

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Set up FDB cluster and dhstore on prod. Use 5 storage servers with increased rate keeper limits tuned for write-heavy workload.
> Deploy FDB and stateless dhstore on `prod`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
The allocatable memory left on `c6a8xl` nodes is just over 60Gi after daemonsets run.
Reduce the demand slightly so that it fits on the nodes.
> Reduce FDB memory demand to fit allocatable memory in `c6a.8xl`

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/deployment.yaml
Wrong configmap name for FDB cluster file.
> Fix type in prod stateless dhstore deployment

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Altering knobs here requires tuning of other knobs to make sure storage server MVCC memory is not limiting performance.
For now remove them.
> Remove FDB ratekeeper memory limits

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Increasing CPU have improved the latencies however they are still behind the other instances
> Give prod dhstore more RAM

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/pod-monitor.yaml
Do not reuse `app=dhstore` label in stateless instances to avoid other services selecting stateless instances and routing traffic to them.
> Override `app` label in dhstore stateless to restrict service selectors

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/config.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Set cache expiry to 24 hours with cache size of 1M. The caching memory footprint is unclear just now. Further experimentation is needed to right-size the instance relative to cache size.
Use a reduced cache expiry and size for `dev` environment.
See:
- https://github.com/ipni/cassette/pull/38
> Deploy caching in cassette

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
* Deploy the latest indexstar to prod
* The latest indexstar supports separate backend types for provider, regular and double hashed lookups
> Deploy the latest indexstar to prod

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
Success rate since adding the caching is reduced by 30%. Investigate what causes this by disabling 404 caching.
> Deploy latest to cassette with option to not cache 404s

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Since excluding oden from the backends the rate of 404s returned by indexstar in prod is higher than 200s.
Add it back in to investigate the effect.
Reverts: https://github.com/ipni/storetheindex/pull/1958
> Add `oden` as indexstar backend in prod due to high 404 rate

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
This is to cope with read and write traffic now that they are added to read path.
> Scale up dhstore stateless in prod to 5 replicas

- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/deployment.yaml
> Increase `cassette` memory limit to 10Gi on prod

- command/daemon.go
- command/init.go
- config/indexer.go
- e2e_test.go
- go.mod
- go.sum
- internal/ingest/ingest_test.go
- internal/registry/registry.go
- server/admin/server_test.go
- server/find/protocol_test.go
- server/ingest/protocol_test.go
The new core has dhstore as a valuestore implementation, and not as an option to the engine.
- Use latest core with dhstore valuestore instance.
- Make value store required.
- If valuestore is "" or "none", and DHStoreURL is configured, then use dhstore as valuestore. This makes upgrade compatible with previous configs.
- Update e2e test to have 1st indexer write to pebble and 2nd write to dhstore.
> Update core and has dhstore as a valuestore

- deploy/manifests/base/foundationdb/fdbmeter/deployment.yaml
- deploy/manifests/base/foundationdb/fdbmeter/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdbmeter/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdbmeter/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdbmeter/pod-monitor.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdbmeter/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdbmeter/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdbmeter/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Deploy `fdbmeter` to collect FoundationDB prometheus metrics on `dev` and `prod`.
> Deploy `fdbmeter` to collect FoundationDB prometheus metrics

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Enable write to mirror on inga so that ads ingested by it are not re-downloaded by other nodes.
> Enable write to mirror on `inga`

- deploy/infrastructure/dev/us-east-2/cloudfront.tf
- deploy/infrastructure/prod/us-east-2/cloudfront.tf
cid.contact no longer supports reframe paths. Remove caching config for it.
> Remove redundant reframe routing from cloudfront

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/arya/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/bala/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/cera/config.json
Reduce the batch size on writes to DH store to investigate FDB high storage server lag. This should increase the number of transactions but offer better distribution across servers.
> Investigate high FDB storage lag by reducing dhstore batch to 16

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/deployment.yaml
`inga` is running out of CPU all the time. move it to c6a 12XL nodes.
> Move `inga` to instance types with more CPU

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
`inga` is suffering from high CPU usage, despite reduction of worker count by 10X and increase of CPU resource by ~3X.
This level of CPU consumption seems unreasonable and causes latency
fluctuation in lookups. Further, it causes high rate of 404s due to provider lookups via dhfind instances failing. Therefore it is now excluded as a provider backend.
Include new FDB backed instances as provider backed since they now have 100% coverage of providers.
> Exclude `inga` and add FDB-backed indexers as provider backends

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Inga has extended provider info that is not present on other indexers. Specifically for NFT provider
> Add inga back as a provider backend

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#2010
Now that the ingest high cpu is resolved.
> Revert "Reduce worker count on `inga` to 10"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/deployment.yaml
It is running out of CPU which causes high latency lookups.
> Move dhstore porvy to compute optimised instance types

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
The log process class uses very little storage, but it is given 16Ti volumes. Reduce it to 2Ti and grow as needed.
> Reduce under-utilised storage given to FDB log process class

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Add 3 dedicated coordinators to FDP prod cluster and reduce storage servers per pod to 2 in order to investigate memory contention on storage servers.
> Add dedicated coordinators to FDB prod cluster

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
While load testing FDB backed indexers, exclude them from provider endpoint to avoid incorrect provider info aggregation.
> Exclude FDB backed indexers from provider backend on prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
FoundationDB used AIO with O_Direct interface to interact with disk. The maximum number of outstanding IO operations default to 64. If this value is too low then the ratekeeper limits the accepted write rate which results in a growing lag between memory and disk in log and storage servers.
Bump the max outstanding kob to 256 in order to observe the effect on lag.
> Increase max outstanding IO operations to 256

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
In order to investigate increasing data in move, since there is spare
IOPS on disk increase the parallelism and fetch key parallelism bytes.
> Increase fetch key and relocation parallelism on `prod` FDB

- config/ingest.go
- internal/ingest/ingest.go
When resyncing, sometimes we want to rewrite the mirror, usually we do not.
We may want to rewrite the mirror to get rid of the deleted multihash data that is not needed or to re-encode or compress differently.  Usually, we will only want to read existing CAR files from the mirror when resyncing.
> Make rewriting the mirror when resyncing configurable

- deploy/infrastructure/common/github_actions.tf
Looks like github changed certs, so we need a new fingerprint. Otherwise, ECR builds are failing with error:
"OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint"
I manually added the new fingerprint in the AWS console (IAM > identity providers > token.actions.githubusercontent.com) to see that it fixed the build problem, so now adding it here. The old fingerprint is still there in case this is a temporary situation and github changes back, or some servers still present the old certs.
> Update the github certificate thumbprints

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Indexers at different ingest offset result in inconsistent results when it comes to aggregating extended providers since they may have different provider info.
Now that `inga` is caught up, exclude `oden` to reduce the chances of inconsistent result and make it easier to debug issues.
> Remove `oden` as provider backend since `inga` is caught up

- .github/workflows/ecr-publisher.yml
- go.mod
- go.sum
- internal/ingest/ingest.go
- internal/registry/registry.go
- Do not set LastError on skipped advertisements
- Do not set LastError if db write failure
- Use new go-libipni that does not block SyncFinished events.
> Clear LastError on good sync

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhfind-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago2/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
New dhstore has both dhstore and dhfind functionality.
- Deploy the new dhstore.
- Configure new dhstore with providersURL that points to ago-indexer.
- In indexstar, replace dhfind-ago2 with dhstore-ago2.
> Deploy new dhstore-ago2 and replace dhfind-ago2

- internal/ingest/ingest_test.go
- internal/registry/apiconv.go
- internal/registry/registry.go
LastError was not previously persisted.
Add code to cleanup any errors in stored provider info.
> Persist LastError across restarts

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Reverts ipni/storetheindex#2057
The problem with getting providers has nothing to do with any difference between previous and latest version, so redeploying latest.
> Revert "Revert "Deploy latest to inga""

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
`inga` on prod is suffering from high CPU usage to the extent where it is unresponsive. Reduce worker count to 5 to investigate.
> Investigating high CPU usage: Reduce worker count on inga to 5

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
`inga` was the only provider backend and it down. As a result no providers are being found and therefore no lookups.
Restore old ndoes while investigating.
> Add old indexers as provider backend while investigating `inga` issues

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
Revert back to 0.7.3 as the latest to investigate excessive CPU usage on inga.
> Revert inga to 0.7.3 to investigate excessive CPU usage

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Reverts ipni/storetheindex#2060
`inga` is back up; remove old indexers as provider backend to avoid inconsistent lookup results.
> Revert "Add old indexers as provider backend while investigating `inga` issues"

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
`inga` is back up and operational after working through the CPU flareup.
Increase worker count from 5 to 50 in order to investigate the impact of ingest on CPU spikes. Note that the node is currently running 0.7.3.
Cc @gammazero  for visibility.
> Increase workers on inga to 50 now that CPU usage has settled

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
It seems locking contention in leveldb used by index counter causes high CPU spikes that then results in readiness check failure and ultimately cause all lookups to cid.contact to fail.
To mitigate the issue and restore service, deploy a quick fix where index counter is completely excluded from execution path until appropriate fixes are in place. This will assure that the service is restored in the meantime. However, it means that we may end up with inaccurate index counts for some providers.
This is an acceptable tradeoff since absolute index counts are not as important than lookup service itself or their relative growth.
Relates to #2062
> Disable index counter on `inga` to restore service in `prod`

- version.json
Bump version to release a change that disables index counters by default and makes it configurable. This removes contention on ingest and CPU spike no nodes until there is a more optimal implementation of index counting functionality.
> Bump version to release index counter config

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Investigating MVCC memory issue: reduce disk page cache now that hard
limit bytes is doubled.
> Reduce FDB cache for disk pages

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
In order to utilise all the memory available, increase memory limit to
28GiB since the pod only runs 2 storage server processes.
> Increase storage memory limit to 28GiB

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Bump the default block and block cache. Increase read and compaction parallelism. Remove FDB storage limits to revert back to normal as the RocksDB settings seems to be the prohibiting factor.
> Tune RocksDB storage engine in prod FDB cluster

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
Set up node groups on dev to upgrade FDB such that it matches prod setup.
> Add c6a.8xl node type on dev in prep to upgrade FDB

- deploy/manifests/dev/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
To make testing on dev comparable with prod, configure the dev FDB cluster such that it matches the prod nodes.
> Use the same FDB config as `prod` on `dev`

- deploy/manifests/dev/us-east-2/cluster/autoretrieve/flux-cd.yaml
Suspend the continuous delivery in the autoretrieve namespace to prevent changes to the autoretrieve namespaced manifests from making changes to the current running tornado applications.
> feat: suspend autoretrieve namespace CD

- deploy/infrastructure/dev/us-east-2/kms.tf
- deploy/infrastructure/dev/us-east-2/outputs.tf
- deploy/infrastructure/dev/us-east-2/tornado.tf
Create a dedicated KMS key used to manage encryption and decryption of secrets used by the Tornado team.
> Create KMS key for Tornado team as a tenant

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-qiu/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-qiu/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-qiu/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhfind-qiu/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/pod-monitor.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/kustomization.yaml
Since `dhstore-porvy` is close to fully utilising its given storage, deploy a new dhstore instance with a matching dhfind instance.
Once the services are up, a separate PR will switch `inga` to use the new dhstore instance instead of `porvy`.
> Deploy a new dhstore instance on prod

- deploy/infrastructure/dev/us-east-2/eks.tf
Expand subnets for `dev-ue2a-r6a-xl` as we were running out of IPs and
nodes were not getting scheduled.
> Expand subnets for `dev-ue2a-r6a-xl` node group

- deploy/manifests/base/heyfil/deployment.yaml
- deploy/manifests/base/heyfil/kustomization.yaml
- deploy/manifests/base/heyfil/service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/ingress.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/heyfil/pvc.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/heyfil/pvc.yaml
Deploy the latest HeyFil service on dev and prod that introduces a REST API for querying SP information as well as local storage for quick resumption of metrics on restart.
> Deploy HeyFil API on dev and prod with persistent storage

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
They are under utilised. Reduce the replica count to 2 on dev and prod.
> Reduce dhstore stateless instances to 2

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Run dedicated data distributors on prod for FDB cluster in order to investigate OOM error on storage servers.
> Separate FDB data distributors on prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
This is necessary since there are 17 providers known to the fdb indexers that are not known to inga.
It is no longer necessary to remove these for FDB load testing, because the indexstar provider cache removes any significant query load.
> Use new FDB indexers as providers backends.

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Self-recovery of the FDB nodes on prod was significantly delayed such that it halted ingestion. This was caused by growing write lag on the nodes and eventually knocked out the coordinators which resulted in the cluster being unresponsive.
To fix this, specific storage nodes with large lag were excluded, and the max generations was changed from 0 to 200.
The changes also introduce dedicated ratekeeper nodes to reduce load on storage servers.
> Recover FDB prod cluster from too many old generations

- deploy/manifests/base/foundationdb/namespaced-manager/deployment.yaml
In preparation for upgrading foundation db, add the binaries for two higher versions with the latest patch.
> Add FDB 7.2 and 7.3 binaries to controller in prep for upgrade

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Investigating rocksdb storage engine memory leak problem. Upgrade the production FDB cluster to 7.3.7.
> Upgrade production FDB to 7.3.7

- deploy/manifests/base/foundationdb/namespaced-manager/rbac.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Increase max gen during FDB upgrade so that it can proceed.
Investigate manager  role binding issue in prod by elevating role bindings to cluster level.
> Increase max generations for FDB in prod during upgrade

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
While prod FDB is coming up, disable writes to it and disable replace instances.
> Disable replace in prod fdb and undeploy dhstore stateless

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
It seems the operator does not handle the e notations gracefully.
Reduce memory on storage nodes to investigate sustained high memory usage.
> Replace E-notation in prod FDB config with zeros

- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Refine the prod FDB knobs such that total memory consumption remains below max.
> Refine prod FDB config to stay below max memory

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdbmeter/kustomization.yaml
FDB cluster in prod is back up and running. Resume write traffic. Upgrade fdbmeter and dhstore to use the latest compatible FDB client libraries.
> Resume dhstore stateless on prod and upgrade to FDB client library 7.3.7

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-stateless/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/fdb-cluster/cluster.yaml
Reduce the storage servers to 3 from 5 and move to redwood storage
engine since after the upgrade nodes still go over the max configured
memory limit in rocksdb and get killed.
Disable writes while the data is moving.
> Move prod FDB to Redwood storage engine

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Swap inga's dhstore with one that has free space with no compaction debt
while qiu is recovering.
Set compaction threshold on qui for experimentation and update the the
latest image that understands the new flags.
> Point `inga` to dhstore-helga while dhstore-qiu is recovering

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/kustomization.yaml
To avoid OOM killing of the process move it to larger instances and give it more resource.
While at it, upgrade it to the latest dhstore.
> Move helga to larger instances

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/pvc-gp3.yaml
Increase dhstore PVC to 16Ti so that if we need to switch to it, it has max head room.
> Expand prod dhstore pvc for maximum headroom

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/kustomization.yaml
This reverts commit 47f38668349b716898d6a4949fa8f745e431f6ee.
Bootstrapping in kubo v0.21.0 seems to be broken.
> Revert "Deploy latest indexer to ago (#2153)"

- command/daemon.go
If the bootstrap config function LoadTempBootstrapPeers is not defined, then bootstrapping panics.
This happens here, because a nil function is called: https://github.com/ipfs/kubo/blob/master/core/bootstrap/bootstrap.go#L248
> Fix panic in bootstrap

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/internal-service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/pod-monitor.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/pvc.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/service.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
After it is created and running, a following PR will switch ago-indexer and indexstar to use it.
> Create a new dhstore node in dev since dhstore-ago2 is out of space

- server/find/server.go
- server/find/server_test.go
json.Encoder.Encode already adds a newline after each record: https://pkg.go.dev/encoding/json#Encoder.Encode
> Do not add extra newline after json records

- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
Indexstar star is picking up providers from these indexers, which all have errors writing to the offline FDB storage. This is causing false reporting for provider errors from the providers/ endpoint. This PR updates indexstar to not get provider updates from these indexers.
> Exclude FDB indexers from serving as providers backends

- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
The new telemetry service was added but not included in the kustomization that gets applied by flux CD. Add it to trigger deployment.
> Include telemetry service in dev deploy manifests

- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/config.json
Assigner requires at least one indexer. Until that condition is relaxed
, add a fake indexer sot that the service starts.
See:
- https://github.com/ipni/storetheindex/issues/2168
> Add noop indexer to assigner to avoid crash loopback

- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
- Expand depth limit to 10000
- Use less memory CPU
> Fix telemetry memory use by removing concurrent distance tracking

- command/daemon.go
- go.mod
- go.sum
There is no need for the indexer to persist bootstrap peers. Doing so may lead to unexpected behavior if the indexer connects to peers that it is no longer configured to connect to.
> Do not persist bootstrap peers

- assigner/command/daemon.go
Need this because of https://github.com/ipfs/kubo/issues/10030.
Can be removed when https://github.com/ipfs/kubo/pull/10029 is available.
> Fix panic due to unassigned bootstrap config functions

- assigner/command/daemon.go
- command/daemon.go
- go.mod
- go.sum
- server/admin/server_test.go
- server/ingest/handler_test.go
- server/ingest/protocol_test.go
Need to update go-libipni because it contains a fix for a graphsync deadlock
- Includes fix for graphsync deadlock
- Tests close libp2p hosts
No new tests needed
> Update to latest version of go-libipni

- go.mod
- go.sum
- internal/registry/registry.go
Unspecified addresses, [::] and "0.0.0.0", need to be removed from the publisher addresses in announcement messages and from the provider addresses in advertisements.
This is currently causing sync failures when trying to access these addresses to get advertisements from, now that at least one provider is including such addresses in its announce messages.  Also, these addresses are unusable by retrieval clients that may receive these in index query responses.
Update to a later version of go-libipni that has this address filtering fix.
Tests are included in `go-libipni/mautil`
> Remove unspecified addresses from announcements and ads

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Switch inga from qiu dhstore to helga in order to determine if the slow ingest is caused by dhstore backend or not.
> Switch dhstore backend to investigating degraded ingest

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/deployment.yaml
This value used to be 10 minutes which we hit every time the shutdown took longer than 3 minutes. The most likely cause for this is lingering GraphSync syncs which do not clear after 10 minutes of wait, hence no point to wait that long.
> Reduce termination grace period for indexers to 3 minutes

- deploy/infrastructure/prod/us-east-2/eks.tf
No longer used by the deployemnts and would stop node scheduling if present.
> Remove redundant taints on K8s workgroups

- assigner/core/assigner.go
- command/loadgen/loadgen.go
- config/ingest.go
- doc/ingest.md
- e2e_test.go
- go.mod
- go.sum
- internal/ingest/ingest.go
Use new go-libipni that has package `ipnisync` that replaces `httpsync`.
- Dependency changed
- Minor API change
- New config item `Ingest.MaxAsyncConcurrency`
Test withing go-libipni
> Configurable max async ad syncs concurrency

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
New indexstar and dhstore have separate encrypted and non-encrypted lookup paths.
> Deploy dhstore and indexstar

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
New image has separate encrypted and non-encrypted paths
> Deploy new image to old dhstore instances

- internal/registry/registry.go
- internal/registry/registry_test.go
This simplifies the registry code and makes it more efficient.
Originally, the registry was going to run many functions asynchronously in its own goroutine so that callers would not have to wait for the processing to finish. Over time, all the calls to registry functions became synchronous, so the channel and goroutine were nothing more than a synchronization mechanism. This PR replaces that goroutine with a simpler mutex.
> Replace registry goroutine and channel with mutex

- e2e_test.go
- test/testindexer.go
- test/testipnirunner.go
Ref: https://github.com/ipld/frisbii/pull/36
This doesn't introduce anything new to the test, but exposes pieces in a way to make the runner framework reusable. It turns out that it's probably pretty useful just for generic test environments and maybe should even be its own package. But for now this works for me in Frisbii; see https://github.com/ipld/frisbii/pull/36.
> feat: publicly expose e2e TestIndexerRunner

- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
Experimental indexer and telemetry service. Telemetry pulls provider ingestion rate data from indexer's admin server.
> Deploy new indexer and telemetry

- .github/workflows/ecr-publisher.yml
- admin/client/client.go
- command/admin.go
- e2e_test.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/metrics/server.go
- rate/map.go
- server/admin/handler.go
- server/admin/server.go
Expose new endpoints in admin server to get per-provider ingestion rate data:
- /telemetry/providers
- /telemetry/providers/
Remove per-provider prometheus metrics.
Reset rate stats after they are retrieved from the indexer.
> New telemetry endpoints to get ingestion rate metrics

- command/loadgen.go
- go.mod
- go.sum
- server/find/extended_providers_test.go
- server/find/protocol_test.go
- server/find/server.go
- server/find/server_test.go
The find client FindBatch API, available as `HTTP POST /multihash/` is no longer supported.
> Drop support for batch find API

- deploy/manifests/dev/us-east-2/tenant/storetheindex/instances/ago/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- internal/ingest/ingest.go
- internal/registry/registry.go
- internal/registry/registry_test.go
When polling (auto-sync) begins, there are typically more providers to attempt to sync with than there are indexer workers available. This leads to starving working providers by polling mostly unresponsive providers.
Fixes #2294
- Polling attempts to poll a fraction  (1/2) of the workers on each polling retry.
- The providers polled each time are the least recently polled.
- The polling retry period may also is set to a longer time.
Manual
> Do not consume all workers with polling

- internal/ingest/ingest.go
- internal/ingest/ingest_test.go
- internal/ingest/linksystem.go
Do not show the details of an internal error in the provider information LastError field.
Fixes #2135
Before this PR a LastError would have this value:
```
"error while ingesting ad baguqeerakox7bxasaugzzryydb2i5wjc7ryx44eyciur7t3amcqif6b7rrsq: indexerErr: failed to remove provider context: Delete \"http://dhstore-helga.internal.prod.cid.contact/metadata/AUvZrCRZAnyeqeZrnsNsP5knEbdKa1dx6TGGQyQga3jZ\": dial tcp 20.10.3.212:80: i/o timeout"
```
Ingestion errors caused by a failure of the indexer itself have a `errInternal` in their error chain. This acts as a tag for these errors, and the error text is changed to "internal error" when it is put into the provider information.
After this PR it would have:
```
"error while ingesting ad …
```
> Do not show internal errors in provider information

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
When a request for ad entries if made, then advertisement provider builds its entries chain at the time the request is made. If the entries chain is long, as it the case for at least one provider, then the response is not sent for some time. This may cause the indexer to time out waiting for a response.
> Increase http timeout to 3m

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Temporary fix to clients that do not respond to entry requests until entries chain is built.
> Very long http timeout

- internal/httpserver/util.go
- server/admin/handler.go
If a manual synce request is given when there is already a sync in progress, the WaitGroup is being incremented even though a new goroutine is not started. This causes the server shutdown to hang waiting for the WaitGroup.
> Fix shutdown failure after manual sync

- internal/ingest/ingest.go
- server/admin/handler.go
An explicit (manual) sync will do nothing if all the advertisements have been synced, but their entries have not yet been synced. This means that either a new advertisement or an explicit resync is required to process the partially synced advertisements.
A common reason for doing a manual sync is to restart a sync that failed or was interrupted due to some error. A new advertisement may not be available to restart processing the advertisement chain, and ipnisync will not send a new advertisement notification because it has already seen the latest advertisement.
Auto-sync suffers from the same problem. If a sync is interrupted after the advertisement chain is synced, but before all the entries are synced, then subsequent polls will do nothing until a new advertisement is published.
This …
> Explicit sync continues from last fully-processed ad

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Done experimenting with HTTP timeouts, so setting this to something somewhat more reasonable.
> Set smaller http sync timeout

- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
Now there there is no more Rhea traffic, reduce the caskadht instances to 1 in order to reduce cost.
> Scale in `caskadht` in prod

- deploy/infrastructure/prod/us-east-2/eks.tf
The size was increased last week as part of investigating deployment issues.
Since then the issue has been resolved. Reduce to avoid excessively large number of nodes.
> Reduce max ASG size for prod worker node group

- deploy/manifests/dev/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/lookout/config.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/cassette/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/config.yaml
The primary use of Bitswap cascading lookup offered by cassette was Rhea which is no longer generating traffic.
Reduce replicas of cassette to zero in preparation for sunsetting the service.
> Reduce cassette replicas to zero due to reduced bitswap cascade traffic

- deploy/manifests/dev/us-east-2/cluster/ingress-nginx/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/ingress-nginx/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Due to reduced traffic, instances seem under utilised. Reduce replica count from 3 to 2 for both nginx ingress controller and indexstar.
> Reduce ingress and indexstar replicas to 2

- deploy/infrastructure/dev/us-east-2/eks.tf
- deploy/infrastructure/dev/us-east-2/saturn-lassie-event-recorder.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
No deployment explicitly demands this instance type in dev; remove this node group.
Fix manually edited lassie event recorder DB params in infra-as-code.
> Remove c6a8xl node group from dev and fix terraform

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-ravi/deployment.yaml
The read-only dhstore instances barely use any CPU. Move them to much cheaper memory optimised instances.
> Move read-only dhstores to memory optimised instance types

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/deployment.yaml
* Move to cheaper instances while the ingest pipeline is out since the previous one was underutilised.
* The worker group associated with the new instance type has spare IPs, which should resolve the scheduling problem.
> Move inga to c6a-8xl instances with more subnet IPs

- deploy/infrastructure/prod/us-east-2/eks.tf
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
No longer needed as inga is migrated off to c6a8xl. This should also bring us cost savings going forward.
> Remove redundant c6a-12xl working group

- command/daemon.go
These are building up over time to take up significant space and do not serve any purpose since there is no need to resume data-transfer sessions across restarts.
> Remove temporary data-transfer fsm records at startup

- go.mod
- go.sum
- server/admin/handler.go
- version.json
The admin sync command causes panic when no address is given. Fixed by avoiding nil multiaddr.
Update go-libp2p to fix timer leak.
Fixes #2388
> Fix admin sync with no address specified

- command/daemon.go
- command/datastore.go
- command/datastore_test.go
- command/update_datastore.go
- config/datastore.go
Temporary data, that has been abandoned, may accumulate over time. It may be desirable to get rid of it between indexer runs.
Adds a new config file option to remove temporary data at start time.
Unit tests to check that feature works correctly
> Config option to remove all temporary data at startup

- internal/registry/registry.go
- internal/registry/registry_test.go
When an indexer receives handoff from another frozen indexer it remembers the source of the handoff. This is persisted across restarts, but was not being loaded correctly, and the source was not loaded after a restart.
Reload persisted data correctly from datastore.
Added unit test to check that handoff data is loaded after a restart.
> Fix error loading persisted handoff data

- admin/client/client.go
- command/admin.go
- internal/ingest/ingest.go
- server/admin/handler.go
- server/admin/server.go
- server/admin/server_test.go
This allows explicitly marking an advertisement as processed to avoid processing an advertisement or those before it.
> Add API to administratively mark advertisement as processed

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago2/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/kustomization.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
Latest is already running on write instance, so this only deploys the read instances.
> Deploy dhstore on dev that supports index deletion

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- ipni-gc/reaper/reaper.go
Empty advertisements should not be saved to mirror since they do not help index ingestion. Advertisements may have no multihash entries when:
1. The ad removes a context ID
When ingesting ads, the indexer does not read removal ads from the mirror since there is no entry data to get.
2. The ad only updates metadata or provider information
The indexer stores the metadata, but does not read mirror since there are no entries
3. The ad was deleted by a removal ad later in the chain
Once an ad is known to be deleted, that ad will never be read from the mirror since its content is deleted
4. The publisher is not serving entries data
This is treated like a no-content ad, as in case 2, but means that at some point in the past the ad had entry data. There is or should be a pending unpublished …
> Do not save empty advertisements to mirror

- command/daemon.go
- config/ingest.go
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
- doc/config.md
- internal/ingest/ingest.go
A new boolean config option `Ingest.Skip500EntriesError` allows the indexer to skip advertisements when the publisher returns a 500 response with "failed to sync first entry". This value is run-time reloadable.
The purpose of this is to skip ads that to publisher will never deliver content for. There is an issue with providers where they will not return entries from some advertisements, and permanently return a 500 result when trying to sync the entries.
If the option is enabled, then skip ads that result in a 500 error when syncing the first entries block.
Manual testing with providers exhibiting this behavior. Also, tested changing this value in the config file is reloadable.
> Configurable option to skip ads with 500 error on first entries block

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
This provider publishes large numbers of advertisements, with each ad having a single multihash. Then publishing separate removal advertisements to delete each of those. Indexing cannot be done like this. It is not only incredibly inefficient but will fill up the indexer's local datastore with remembering processed ad CIDs.
Blocking publisher at both assigner and indexer.
> Block bad publisher

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/config.json
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
Reverts ipni/storetheindex#2500.
PeerID not used anymore, no need to block.
> Revert "Block bad publisher"

- config/ingest.go
- go.mod
- go.sum
- internal/ingest/ingest.go
A new config item `FirstSyncDepth` sets the advertisement chain depth to sync on the first sync with a new provider. To sync a new provider with only the most recent advertisement, set this to 1. A value of 0, the default, means unlimited depth.
This option is useful to avoid syncing advertisement chains back to the beginning of time.
Unit tests in `go-libipni` test that is feature works, and manual testing with storetheindex was also done.
> Configurable first sync depth

- deploy/manifests/base/assigner/deployment.yaml
FYI, looks like assigner is now failing:
```
cannot write to /data/storetheindex: permission denied
```
Reverting last change to assigner startup.
> Revert assigner startup config change

- .github/workflows/publish-ghcr.yml
- deploy/manifests/base/assigner/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
Assigner startup command change needs to be accompanied by new container image.
> Fix assigner start and deploy with new image

- scripts/cross_announce/main.go
Implement a utility script that announces providers from one indexer to another.
> Implement script to cross announce providers across indexers

- carstore/carreader.go
- carstore/carreader_test.go
- carstore/carwriter.go
- carstore/carwriter_test.go
- internal/ingest/ingest.go
- internal/ingest/linksystem.go
- internal/ingest/mirror.go
This prevents checking if the CAR file already exists in the mirror, unless `noOverwrite` is specifically asked for.
> Avoid mirror head check if CAR was read from write mirror

- Dockerfile
Looks like `ipnigc` executable cannot find shared lib:
```shell
/home/nonroot $ /usr/local/bin/ipnigc
sh: /usr/local/bin/ipnigc: not found
/home/nonroot $ ls -l /usr/local/bin/ipnigc
-rwxr-xr-x    1 root     root      53153192 Feb 15 17:28 /usr/local/bin/ipnigc
```
Build without CGO
> Build ipnigc without CGO in Docker image

- config/policy.go
- internal/registry/policy/policy.go
- internal/registry/policy/policy_test.go
- internal/registry/registry_test.go
This allows each provider to have its own policy for which publishers are allowed to publish advertisements on behalf of that provider. The previous publisher policy serves as the default when there is no policy configured for a specific provider.
> Allow configuration of per-provider publishers policy

- deploy/infrastructure/common/github_actions.tf
- deploy/infrastructure/dev/us-east-2/index-provider.tf
- deploy/infrastructure/dev/us-east-2/kms.tf
- deploy/infrastructure/prod/us-east-2/kms.tf
- deploy/manifests/dev/us-east-2/cluster/kube-system/aws-auth.yaml
- deploy/manifests/prod/us-east-2/cluster/kube-system/aws-auth.yaml
Remove redundant access to resources and clean up permissions.
This is in prep for phasing out the AWS environment.
> Clean up old users and permissions

- deploy/manifests/dev/us-east-2/cluster/kustomization.yaml
Undeploy K6 controller and foundation DB CRDs from dev. They are no longer in-use.
> Undeploy underused CRDs from dev

- deploy/manifests/dev/us-east-2/cluster/monitoring/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/kustomization.yaml
Reduce grafana dashboard replcia count to zero as it is unused.
> Undeploy grafana dashboard from K8S clusters

- deploy/manifests/dev/us-east-2/cluster/flux-system/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/monitoring/kustomization.yaml
- deploy/manifests/dev/us-east-2/cluster/monitoring/patch.yaml
- deploy/manifests/dev/us-east-2/cluster/monitoring/prometheus-patch.yaml
- deploy/manifests/prod/us-east-2/cluster/flux-system/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/kustomization.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/patch.yaml
- deploy/manifests/prod/us-east-2/cluster/monitoring/prometheus-patch.yaml
To reduce resource usage, undeploy or reduce unused cluster-level controllers.
> Reduce cluster controller replicas

- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago3/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago4/deployment.yaml
- deploy/manifests/dev/us-east-2/tenant/storetheindex/dhstore-ago5/deployment.yaml
Remove dedicated taint requirement for a specific instance type.
This allows dhstore on dev to use any available resource for better infra utilisation.
> Allow dhstore on dev to use any available node

- deploy/manifests/dev/us-east-2/tenant/storetheindex/kustomization.yaml
Experimentally deploy indexer with no data-transfer/graphsync support to see if it still exhibits worker deadlock issues.
> Deploy indexer without graphsync to dev

- internal/ingest/ingest.go
- internal/ingest/linksystem.go
In some places context cancelation was not handled during ingestion. This caused the indexer to be unresponsive to a shutdown request. This change will include context cancelation when selecting to read or write channels.
Adds additional debug logging.
> Handle context concelation during ingestion

- command/updatemirror.go
- e2e_test.go
- internal/ingest/linksystem.go
- main.go
When multihashes are read from a CAR file in the read mirror, the CAR that gets written to the write mirror is missing those multihash entries.
See issue #2598 
Write entries block data to temporary datastore same as if it were read from index-provider.
Manual testing also confirmed that CAR written to storage mirror is identical to CAR read from retrieval mirror, by sha1 hash.
e2e test includes test that read and write mirrors end up with identical CAR.
> Write complete CAR file when index content read from CAR file

- deploy/manifests/dev/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
Update to the latest tagged release of indexstar on dev and prod.
Most notable change is the update to delegated routing peer discovery schema.
> Deploy the latest indexstar with tagged release

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/pvc-gp3.yaml
The current primary dhstore, where new data is written to, is nearly out of space. The oldest dhstore is only 61% full, so prepare it to become the primary.
Storage IOPS and throughput will be scaled up administratively with AWS volume management.
This also scales down dhstore-seka. dhstore-tetra will be scaled down after prod is using the new (refurbished) dhstore.
> Scale up old dhstore in prep for making it primary

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-ravi/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-tetra/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
New dhstore has updated libp2p (v0.35.1) and pebbe (v1.1.1)
> Deploy the latest dhstore to prod

- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/config.json
The current primary is close to full saturation which results in high origin latency on ingress traffic and consequential high 404 rate.
Switch the primary dhstore to `qiu`, the instance with least disk saturation.
> Switch to least saturated dhstore backend as primary write

- server/find/server.go
- server/find/server_test.go
Currently, find only support decoding B58 multihash strings. We are adding support for Hex strings as well.
Currently, find only support decoding B58 multihash strings. We are adding support for Hex strings as well.
NA
Yes
> feat: decode multihash string for B58 and Hex

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/deployment.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/deployment.yaml
Main dhstore needs to have largest instance. Writes were previously failing.
> Allocate larger instance to primary write dhstore

- assigner/core/assigner_test.go
- internal/registry/registry_test.go
Do not read timer channel after call to Stop.
This PR only affects tests. It will still work for go1.22- because the timers do not fire before getting stopped or reset.
> Update timers for go1.23

- assigner/config/config.go
- config/config.go
- fsutil/fsutil.go
- fsutil/fsutil_test.go
- go.mod
- go.sum
This repo is archived, no longer needed, and no longer maintained.
> Stop using github.com/mitchellh/go-homedir

- config/indexer.go
- internal/freeze/freezer.go
- internal/freeze/freezer_test.go
- internal/registry/errors.go
- internal/registry/registry.go
- server/admin/handler.go
Freezing may be disabled after an indexer becomes frozen to prevent the indexer from freezing again. Unfreezing the indexer should still work even if freezing is disabled. This PR makes this possible, whereas previously an indexer could not be unfrozen if freezing was disabled.
Closes #2670
This PR also allows disk usage to be queried even when freezing is disabled.
> Unfreeze even if freezing is disabled.

- assigner/config/config.go
- assigner/server/server_test.go
- config/config.go
- e2e_test.go
- gc/reaper/option.go
Expand leading ~ in config paths to user's home directory.
> Do home directory expansion for config paths

- FUNDING.json
This is used to associate a funding address for drips with the project. This is the project account used for retroPGF rounds so far.
> claim ownership of project for drips

- deploy/manifests/prod/us-east-2/tenant/storetheindex/assigner/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/caskadht/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-porvy/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-qiu/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-ravi/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-seka/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-tetra/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/indexstar/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/instances/inga/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/lookout/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/storetheindex/telemetry/kustomization.yaml
Scale all aws deployments down to zero, in preparation for tear down. State is left for a further grace period time to pass.
> Scale down all AWS deployments in prep for tear down

- deploy/manifests/prod/us-east-2/tenant/storetheindex/dhstore-helga/pvc.yaml
It seems the PVC volume for helga was expanded to 16Ti directly. Reflect
it in specs.
> Fix manually expanded PVC volume

- gc/reaper/reaper.go
- go.mod
- go.sum
- internal/ingest/ingest.go
channelqueue was renamed to chanqueue
> update channelqueue renamed to chanqueue

- deploy/manifests/prod/us-east-2/cluster/ingress-nginx/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/ipni/berg-ingress.yaml
- deploy/manifests/prod/us-east-2/tenant/ipni/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/ipni/namespace.yaml
- deploy/manifests/prod/us-east-2/tenant/ipni/sf-ingress.yaml
move the services
that handle request proxies for sf and berg to cloudfront onto a dedicated namespace.
> Set up dedicated routing for berg and sf in a fresh namespace

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
Switch to SF as primary until Berg hardware is repaired and memory expanded.
> Switch to SF as primary

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
- deploy/manifests/prod/us-east-2/tenant/ipni/kustomization.yaml
- deploy/manifests/prod/us-east-2/tenant/ipni/sf2-ingress.yaml
Cache the delegated rouding paths in cloudfront using the default cache policy.
Update cloudfront origin to add the new sf2 endpoint.
> Cache delegated routing paths and add sf2 origin

- deploy/infrastructure/prod/us-east-2/cloudfront.tf
Add the sampling API to the cache behaviour of cloudfront.
> Cache sampling API responses
